#!/usr/bin/ksh
#################################################################
# FILE: cvt_globalinstall
#
# Script to install CVT into /usr/local/bin
# 
# Must be exectued from the cvt source code directory
# after cvt is compiled
#
# Must be logged in with administrative permissions
#
################################################################

CVT_INSTALL_DIR=/usr/local/bin

#make sure the CVT_INSTALL_DIR directory exists
if [[ ! -d ${CVT_INSTALL_DIR} ]] then 
    mkdir -p ${CVT_INSTALL_DIR}  
    print creating directory ${CVT_INSTALL_DIR}
fi


print "\nINSTALLING CVT TO ${CVT_INSTALL_DIR}"

rm -f ${CVT_INSTALL_DIR}/cvt
cp -p ${ARCH}/cvt ${CVT_INSTALL_DIR}/cvt
chmod a+x ${CVT_INSTALL_DIR}/cvt

print "\nDONE"