/*
 * RCS info
 * $Author: steves $
 * $Locker:  $
 * $Date: 2012/09/13 19:48:43 $
 * $Id: help_functions.c,v 1.3 2012/09/13 19:48:43 steves Exp $
 * $Revision: 1.3 $
 * $State: Exp $
 */

/* help_functions.c */

#include "help_functions.h"



void packet_definitions() {
  /* display a listing of packet ID's and definitions */
  fprintf(stderr,"\n");
  fprintf(stderr,"=================== ICD Packet Code Listing ======================= \n");
  fprintf(stderr,"From the ICD for RPG to Class 1 User, Document 2620001              \n");
  fprintf(stderr,"Packet                                                        ICD   \n");
  fprintf(stderr,"Code     Enumerated Structure Name                          Figure  \n");
  fprintf(stderr,"------------------------------------------------------------------- \n");
  fprintf(stderr,"1        TEXT_AND_SPECIAL_SYMBOL_TEXT_NO_VALUE              3 - 8b  \n");
  fprintf(stderr,"2        TEXT_AND_SPECIAL_SYMBOL_SYMBOL_NO_VALUE            3 - 8b  \n");
  fprintf(stderr,"3        MESOCYCLONE_DATA                                   3 - 14  \n");
  fprintf(stderr,"4        WIND_BARB_DATA                                     3 - 13  \n");
  fprintf(stderr,"5        VECTOR_ARROW_DATA                                  3 - 12  \n");
  fprintf(stderr,"6        LINKED_VECTOR_NO_VALUE                             3 - 7   \n");
  fprintf(stderr,"7        UNLINKED_VECTOR_NO_VALUE                           3 - 8   \n");
  fprintf(stderr,"8        TEXT_AND_SPECIAL_SYMBOL_TEXT_UNIFORM_VALUE         3 - 8b  \n");
  fprintf(stderr,"9        LINKED_VECTOR_UNIFORM_VALUE                        3 - 7   \n");
  fprintf(stderr,"10       UNLINKED_VECTOR_UNIFORM_VALUE                      3 - 8   \n");
  fprintf(stderr,"11       CORRELATED_SHEAR_MESO (3D)                         3 - 14  \n");
  fprintf(stderr,"12       TVS_DATA                                           3 - 14  \n");
  fprintf(stderr,"13       POSITIVE_HAIL_DATA                                 3 - 14  \n");
  fprintf(stderr,"14       PROBABLE_HAIL_DATA                                 3 - 14  \n");
  fprintf(stderr,"15       STORM_ID_DATA                                      3 - 14  \n");
  fprintf(stderr,"16       DIGITAL_RADIAL_DATA_ARRAY                          3 - 11c \n");
  fprintf(stderr,"17       DIGITAL_PRECIP_DATA_ARRAY                          3 - 11a \n");
  fprintf(stderr,"18       PRECIP_RATE_DATA_ARRAY                             3 - 11b \n");
  fprintf(stderr,"19       HDA_HAIL_DATA                                      3 - 14  \n");
  fprintf(stderr,"20       POINT_FEATURE_DATA                                 3 - 14  \n");
  fprintf(stderr,"21       CELL_TREND_DATA                                    3 - 15  \n");
  fprintf(stderr,"22       CELL_TREND_VOLUME_SCAN_TIME                        3 - 15a \n");
  fprintf(stderr,"23       SCIT_PAST_POSITION_DATA                            3 - 14  \n");
  fprintf(stderr,"24       SCIT_FORECAST_POSITION_DATA                        3 - 14  \n");
  fprintf(stderr,"25       STI_CIRCLE_DATA                                    3 - 14  \n");
  fprintf(stderr,"26       ETVS_DATA                                          3 - 14  \n");
  fprintf(stderr,"27       SuperOb Wind Data Packet                           3 - 15b \n");
  fprintf(stderr,"28       Generic Data Packet                                3 - 15b \n");
  fprintf(stderr,"         Supported Components: area, radial, text, table - Appendix E \n");
  fprintf(stderr,"Hexadecimal Product Codes (must include the trailing 'x')           \n");
  fprintf(stderr,"0802x    CONTOUR_VECTOR_COLOR                               3 - 8a  \n");
  fprintf(stderr,"0E03x    CONTOUR_VECTOR_LINKED                              3 - 8a  \n");
  fprintf(stderr,"3501x    CONTOUR_VECTOR_UNLINKED                            3 - 8a  \n");
  fprintf(stderr,"AF1Fx    RADIAL_DATA_16_LEVELS                              3 - 10  \n");
  fprintf(stderr,"BA07x    RASTER_DATA_7                                      3 - 11  \n");
  fprintf(stderr,"BA0Fx    RASTER_DATA_F                                      3 - 11  \n");
  fprintf(stderr,"\n");

}



void quick_help() {
  /* CVT quick reference screen */
  fprintf(stderr,"\n======================= CVT Command Quick Reference ==========================\n");
  fprintf(stderr," \n");
  fprintf(stderr," More extensive information can be obtained with 'cvt help'\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- CODEview Text Informational Commands\n");
  fprintf(stderr,"  ------------------------------------\n");  
  fprintf(stderr,"cvt help             Listing of CODEview Text command line arguments & options\n");
  fprintf(stderr,"cvt h                An abbreviated version of 'cvt help' \n");
  fprintf(stderr,"cvt version          Display version and release date information\n");
  fprintf(stderr,"cvt packets          Listing of ICD Packet Codes & Definitions\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Linear Buffer Inventory Commands\n");
  fprintf(stderr,"  --------------------------------\n");
  fprintf(stderr,"cvt i                Provide an inventory of the main products\n");
  fprintf(stderr,"                         database linear buffer\n");
  fprintf(stderr,"cvt i LBNAME         Provide an inventory of the specific product linear\n");
  fprintf(stderr,"                         buffer with the path 'LBNAME' (under $ORPGDIR)\n");
  fprintf(stderr,"cvt slb L            Search the products database linear buffer for a\n");
  fprintf(stderr,"                         specific linear buffer ID 'L' (product ID) \n");
  fprintf(stderr,"cvt req LBNAME       Show the inventory of one of the request linear\n");
  fprintf(stderr,"                         buffer with the path 'LBNAME' (under $ORPGDIR)\n");
  fprintf(stderr," \n");
  fprintf(stderr," -------------------------------------------------------------------------------\n");
  fprintf(stderr,"                   TWO SOURCES OF PRODUCT MESSAGES:\n");
  fprintf(stderr,"cvt msg X <arguments>                       Access message 'X' from LB \n");
  fprintf(stderr,"                                              (product from the database)\n");
  fprintf(stderr,"cvt load FNAME [-nohdr|-wmohdr] <arguments> Load product from a binary file with\n");
  fprintf(stderr,"                                               relative/absolute path 'FNAME'\n"); 
  fprintf(stderr," \n");
  fprintf(stderr,"                          CONSISTENCY CHECKS \n");
  fprintf(stderr," Product display can be forced with a failure of either the block length check \n");
  fprintf(stderr," or the ICD product check by using the '-f' option (force load)\n");
  fprintf(stderr,"      cvt msg X -f <additional command line arguments>\n");
  fprintf(stderr,"      cvt load FNAME -f <additional command line arguments>\n");
  fprintf(stderr," -------------------------------------------------------------------------------\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Product Information & Header Display Commands\n");
  fprintf(stderr,"  ---------------------------------------------\n");    
  fprintf(stderr,"cvt msg X summary    Access message 'X' in the products database linear buffer\n");
  fprintf(stderr,"                         then print a message summary.\n");
  fprintf(stderr,"cvt msg X            Same as the command: 'cvt msg X summary' \n");
  fprintf(stderr,"                         (this shortcut does not work with 'cvt load FNAME')\n");
  fprintf(stderr," \n");
  fprintf(stderr,"cvt msg X check      Print a verbose product consistency check \n");
  fprintf(stderr," \n");
  fprintf(stderr,"cvt msg X hdr        Print the pre-ICD product header \n");
  fprintf(stderr,"cvt msg X mhb        Print the message header block \n");
  fprintf(stderr,"cvt msg X pdb        Print the product description block \n");
  fprintf(stderr,"cvt msg X sym        Print the symbology block header \n");
  fprintf(stderr,"cvt msg X fullhdr    Print all header blocks \n");
  fprintf(stderr," \n"); 
  fprintf(stderr," -------------------------------------------------------------------------------\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Basic Data Display Commands\n");
  fprintf(stderr,"  ---------------------------\n");
  fprintf(stderr,"cvt msg X layer C    Print the contents of layer C \n");
  fprintf(stderr,"     Command modifiers, 'radial' and 'row' can be used to control the \n");
  fprintf(stderr,"     output of layers containing radial and raster data. \n");
  fprintf(stderr," \n");
  fprintf(stderr,"cvt msg X generic    Print the entire contents of a generic product \n");
  fprintf(stderr,"     Command modifiers can be used to control the output of generic products.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"cvt msg X tab        Print the contents of the Tabular Alphanumeric Block\n");
  fprintf(stderr,"          tabv       Print the MHB and PDB included within the TAB \n");
  fprintf(stderr,"cvt msg X gab        Print the contents of the Graphic Alphanumeric Block\n");
  fprintf(stderr," \n");
  fprintf(stderr,"cvt msg X satap      Print the contents of the Stand Alone Tabular Alpha Product\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Radial/Raster Data Display Commands\n");
  fprintf(stderr,"  -------------------------------------\n"); 
  fprintf(stderr,"cvt msg X [layer C] radial <modifier list>       for radial products\n");
  fprintf(stderr,"cvt msg X [layer C] row <modifier list>          for raster products\n");  
  fprintf(stderr," \n");
  fprintf(stderr,"- Radial/Raster Modifier List Structure\n");
  fprintf(stderr,"  -----------------------\n");
  fprintf(stderr,"           [<content selector>]   [<format selector>]    [<decode selector>]\n");
  fprintf(stderr,"           ---------------------  -------------------  -----------------------\n");
  fprintf(stderr,"   radial  {A | A B | all} [deg]     [rle | bscan]     {fdecode | pdecode} [D]\n");
  fprintf(stderr,"      row  {A | A B | all}           [rle] \n");
  fprintf(stderr," \n");
  fprintf(stderr," -------------------------------------------------------------------------------\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Generic Product Display Commands\n");
  fprintf(stderr,"  -------------------------------------\n");  
  fprintf(stderr,"cvt msg X generic <generic modifier list>\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Generic Modifier List Structure\n");
  fprintf(stderr,"  -----------------------\n");
  fprintf(stderr,"  Any combination of the following optional modifiers in any order: \n");
  fprintf(stderr,"                               [<component list>]\n");
  fprintf(stderr,"---------------------------------------------------------------------------------\n");
  fprintf(stderr,"list_all | list_area | list_rad | list_text | list_table | list_grid | list_event\n");
  fprintf(stderr," \n");
  fprintf(stderr,"                               [<component print>]\n");
  fprintf(stderr,"  ----------------------------------------------------------------------------\n");
  fprintf(stderr,"  print_area | print_rad | print_text | print_table | print_grid | print_event\n");
  fprintf(stderr,"  print X\n");
  fprintf(stderr," \n");
  fprintf(stderr,"                               [<parameter print>]               \n");
  fprintf(stderr,"                 ----------------------------------------------- \n");
  fprintf(stderr,"                 no_pparams | no_cparams | no_pparams no_cparams \n");
  fprintf(stderr," \n");
  fprintf(stderr," For radial components:    [<radial content selector>]  \n");
  fprintf(stderr,"                          -----------------------------\n");
  fprintf(stderr,"                          radial  {A | A B | all} [deg] \n");
  fprintf(stderr," \n");
  fprintf(stderr," For radial/grid components:   [<decode selector>]\n");
  fprintf(stderr,"                             ----------------------- \n");
  fprintf(stderr,"                             {fdecode | pdecode} [D] \n");  
  fprintf(stderr," \n");  
  fprintf(stderr," -------------------------------------------------------------------------------\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Product Extraction Commands\n");  
  fprintf(stderr,"  ---------------------------\n");
  fprintf(stderr,"cvt msg X extract [-nohdr] [-nodc] [-in LBNAME] [-out FILENAME] \n");
  fprintf(stderr,"cvt msg X hexdump [-nohdr] [-nodc] [-in LBNAME] [-out FILENAME] \n");
  fprintf(stderr," \n");
  fprintf(stderr," -------------------------------------------------------------------------------\n");
 
}



void help_screen() {
  /* CODEview Text help screen */
  fprintf(stderr,"\n\n");
  fprintf(stderr,"CODEview Text for National Weather Service WSR-88D ICD Formatted Products\n");
  fprintf(stderr," \n");
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n");
  fprintf(stderr,"Key to use of Letters within the following help listing\n");
  fprintf(stderr,"-------------------------------------------------------\n");
  fprintf(stderr,"  L        Represents a Linear Buffer ID\n");
  fprintf(stderr,"  LBNAME   Is the name of the Linear Buffer File in the form of a relative\n");
  fprintf(stderr,"               path under $ORPGDIR (.lb extension optional)\n");
  fprintf(stderr,"  X        Represents the message sequence number of a product found within\n");
  fprintf(stderr,"               a Linear Buffer. A message sequence number can be found in the\n");
  fprintf(stderr,"               left-most column of an inventory or database search output\n");
  fprintf(stderr,"  FNAME    Is the name of the a single product binary file. This can be a path \n");
  fprintf(stderr,"               relative to the current working directory or a full path name.\n");
  fprintf(stderr,"  A B      Represent radial numbers/degrees or row numbers\n");
  fprintf(stderr,"  C        Is a layer number. In used when displaying messages where more \n");
  fprintf(stderr,"               than one layer is present.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- CODEview Text Informational Commands\n");
  fprintf(stderr,"  ---------------------------- -------\n");  
  fprintf(stderr,"cvt help             Listing of CODEview Text command line arguments & options\n");
  fprintf(stderr,"cvt h                An abbreviated version of 'cvt help' \n");
  fprintf(stderr,"cvt version          Display version and release date information\n");
  fprintf(stderr,"cvt packets          Listing of ICD Packet Codes & Definitions\n");
  fprintf(stderr," \n");  
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Linear Buffer Inventory Commands\n");
  fprintf(stderr,"  --------------------------------\n");
  fprintf(stderr,"cvt i                Provide an inventory of the main product\n");
  fprintf(stderr,"                         database linear buffer\n");
  fprintf(stderr,"cvt i LBNAME         Provide an inventory of the specific product linear\n");
  fprintf(stderr,"                         buffer with the path 'LBNAME' (under $ORPGDIR)\n");
  fprintf(stderr,"cvt slb L            Search the products database linear buffer for a specific\n");
  fprintf(stderr,"                         linear buffer ID 'L' (product ID) \n");
  fprintf(stderr,"cvt req LBNAME       Show the inventory of one of the request linear\n");
  fprintf(stderr,"                         buffer with the path 'LBNAME' (under $ORPGDIR)\n");
  fprintf(stderr," \n");
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n");    
  fprintf(stderr,"- Two basic sources of product messages:\n");
  fprintf(stderr,"  -------------------------------------\n");    
  fprintf(stderr,"1. Normally product messages are loaded from the product database.  The \n");
  fprintf(stderr,"   location of the product, that is its message sequence number 'X', is  \n");
  fprintf(stderr,"   determined with one of the inventory commands. \n");
  fprintf(stderr,"   This form of the cvt command is: \n");
  fprintf(stderr," \n");    
  fprintf(stderr,"         cvt msg X <additional command arguments> \n");
  fprintf(stderr," \n");
  fprintf(stderr,"   By default, cvt uses the product database linear buffer configured for the \n");
  fprintf(stderr,"   OR PG account currently in use.  An alternate database can be temporarily \n");
  fprintf(stderr,"   substituted with the CVT_DB environmental variable (complete path name).\n");
  fprintf(stderr," \n");    
  fprintf(stderr,"2. A second source of product messages are single product binary files. \n");
  fprintf(stderr,"   The product in file 'FNAME' is loaded with the command: \n");
  fprintf(stderr," \n");
  fprintf(stderr,"         cvt load FNAME [-nohdr|-wmohdr] <additional command arguments> \n");
  fprintf(stderr," \n");
  fprintf(stderr,"   By default, it is assumed that the product in the file includes the \n");
  fprintf(stderr,"   internal 96-byte header. \n");
  fprintf(stderr,"     If the product was received by an external user (AWIPS or the nbtcp tool) \n");
  fprintf(stderr,"       it will not contain the internal header.  In this case the command must \n");
  fprintf(stderr,"       include the '-nohdr' option.\n");
  fprintf(stderr,"     If the file was obtained from the central server (e.g., the NCDC web site),\n");
  fprintf(stderr,"       the WMO header must be stripped off with the '-wmohdr' option.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"   NOTE: The two extraction commands ('extract' and 'hexdump') do not work when\n"); 
  fprintf(stderr,"       loading a product from a binary file.  The 'summary' option must be used\n");
  fprintf(stderr,"       to get the summary output when loading from a binary file. \n"); 
  fprintf(stderr," \n");  
  fprintf(stderr,"==============================================================================\n");  
  fprintf(stderr," \n");    
  fprintf(stderr,"- CVT Product Consistency Checks\n");
  fprintf(stderr,"  ------------------------------\n"); 
  fprintf(stderr,"  When CVT begins any display command two checks are performed.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"1. A check is made of the first 120 bytes to determine if the product appears\n");
  fprintf(stderr,"   to be a valid final product (ICD format). The results are displayed and the\n");
  fprintf(stderr,"   command terminated if a valid ICD product not detected. \n");  
  fprintf(stderr," \n");
  fprintf(stderr,"   The -f option (force load) can be used to continue with the desired\n");
  fprintf(stderr,"   CVT command.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"         cvt msg X -f <additional command arguments>\n");
  fprintf(stderr,"         cvt load FNAME -f <additional command arguments>\n");
  fprintf(stderr," \n");
  fprintf(stderr,"2. If the product is a final product (ICD), CVT compares specific product data\n");
  fprintf(stderr,"   fields for consistency.  These are: number of blocks, block offsets, product\n");
  fprintf(stderr,"   length, block lengths, and layer / page lengths.  The results are displayed.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"   A more verbose output can be obtained with the 'cvt msg X check' command.\n");
  fprintf(stderr," \n");  
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n"); 
  fprintf(stderr,"- Product Information & Header Display Commands\n");
  fprintf(stderr,"  ---------------------------------------------\n");    
  fprintf(stderr,"cvt msg X summary    Access message 'X' in the products database linear buffer\n");
  fprintf(stderr,"                         then print a message summary.  This includes a list\n");
  fprintf(stderr,"                         of all Symbology Block layers in the product and the\n");
  fprintf(stderr,"                         presence of a GAB / TAB. \n");
  fprintf(stderr,"cvt msg X            Same as the command: 'cvt msg X summary' \n");
  fprintf(stderr,"                         (this shortcut does not work with 'cvt load FNAME')\n");
  fprintf(stderr,"\n");
  fprintf(stderr,"cvt msg X check      Print a verbose product consistency check  \n");
  fprintf(stderr,"\n");
  fprintf(stderr,"cvt msg X hdr        Print the pre-ICD product header of message 'X'\n");
  fprintf(stderr,"cvt msg X mhb        Print the message header block of message 'X'\n");
  fprintf(stderr,"cvt msg X pdb        Print the product description block of message 'X'\n");
  fprintf(stderr,"cvt msg X sym        Print the symbology block header of message 'X'\n");
  fprintf(stderr,"cvt msg X fullhdr    Print all header blocks of message 'X'\n");
  fprintf(stderr," \n");  
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n"); 
  fprintf(stderr,"- Basic Data Display Commands\n");
  fprintf(stderr,"  ---------------------------\n");
  fprintf(stderr," The first step in displaying data is determining how many layers are\n");
  fprintf(stderr," present in the symbology block and the presence of a GAB or TAB.  The  \n");  
  fprintf(stderr," number of layers can be determined using the summary command: \n");
  fprintf(stderr," \n");
  fprintf(stderr,"     cvt msg X summary\n");
  fprintf(stderr," \n");
  fprintf(stderr," A particular data layer 'C' can be displayed with the basic command (using \n");
  fprintf(stderr," a value of 0 for 'C' will result in all layers being displayed): \n");
  fprintf(stderr," \n"); 
  fprintf(stderr,"     cvt msg X layer C \n");
  fprintf(stderr," \n");
  fprintf(stderr," For Traditional Products, special command modifiers, 'radial' and 'row', \n");
  fprintf(stderr," control the display of layers containing radial and raster data packets. \n");
  fprintf(stderr," \n");
  fprintf(stderr," For Generic Products the entire product can be displayed using the 'layer 1' \n");
  fprintf(stderr," command. The command 'generic' permits use of additional command modifiers \n");
  fprintf(stderr," to control the display. \n");
  fprintf(stderr," \n");
  fprintf(stderr,"     cvt msg X generic \n");
  fprintf(stderr," \n");
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- TAB, GAB, and Stand Alone Product Display Commands\n");
  fprintf(stderr,"  --------------------------------------------------\n");   
  fprintf(stderr,"cvt msg X tab        Print the contents of the Tabular Alphanumeric Block\n");
  fprintf(stderr,"          tabv       Print the MHB and PDB included within the TAB \n");
  fprintf(stderr,"cvt msg X gab        Print the contents of the Graphic Alphanumeric Block\n");
  fprintf(stderr," \n");
  fprintf(stderr,"cvt msg X satap      Print the contents of the Stand Alone Tabular Alpha Product\n");
  fprintf(stderr," \n");
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Radial/Raster Data Display Commands\n");
  fprintf(stderr,"  -------------------------------------\n");  
  fprintf(stderr," If the data layer contains radial / raster data packets, the following forms of\n");
  fprintf(stderr," the display command are used to print the radials/rows in message 'X' layer 'C'\n");
  fprintf(stderr," \n");
  fprintf(stderr,"cvt msg X layer C radial <modifier list>         for radial products\n");
  fprintf(stderr,"cvt msg X layer C row <modifier list>            for raster products\n");  
  fprintf(stderr," \n");
  fprintf(stderr," For products with only one data layer (containing radial / raster packets): \n");
  fprintf(stderr," \n");
  fprintf(stderr,"cvt msg X radial <modifier list>                 for radial products\n");
  fprintf(stderr,"cvt msg X row <modifier list>                    for raster products\n");
  fprintf(stderr," \n");
  fprintf(stderr," The <modifier list> provides flexibility in displaying the data. The entire \n");
  fprintf(stderr," data packet is displayed with default behavior if no <modifier list> is used.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Radial/Raster Modifier List Structure\n");
  fprintf(stderr,"  -----------------------\n");
  fprintf(stderr," A Radial/Raster Modifier list consists of an optional <content selector>  \n");
  fprintf(stderr," followed by and an optional <format selector> and an optional <decode selector>.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"    {} == required parameters           [] == optional parameters \n");
  fprintf(stderr," Possible choices of parameter values are separated by '|' \n");
  fprintf(stderr," \n"); 
  fprintf(stderr," Modifiers for Radial and Raster Based Products:\n");
  fprintf(stderr," \n");
  fprintf(stderr,"           [<content selector>]   [<format selector>]    [<decode selector>]\n");
  fprintf(stderr,"           ---------------------  -------------------  -----------------------\n");
  fprintf(stderr,"   radial  {A | A B | all} [deg]     [rle | bscan]     {fdecode | pdecode} [D]\n");
  fprintf(stderr,"      row  {A | A B | all}           [rle] \n");
  fprintf(stderr," \n");
  fprintf(stderr," The <format selector> (rle and bscan) are only used with traditional products \n");
  fprintf(stderr," (not used with the generic radial component).\n");
  fprintf(stderr," \n");
  fprintf(stderr," Default Behavior:\n");
  fprintf(stderr," \n");
  fprintf(stderr," If no <content selector> is provided, all radials / rows are selected.  The\n");  
  fprintf(stderr," default behavior of the <content selector> is to select radials and rows by \n");
  fprintf(stderr," their ordinal value. For radial data a 'deg' option is provided to select \n");
  fprintf(stderr," radials by degrees.\n");
  fprintf(stderr," \n");  
  fprintf(stderr," If a <format selector> is not used, the data are displayed in Decimal notation\n");
  fprintf(stderr," and RLE data are decoded (if appropriate). The 'rle' option prevents RLE data  \n");
  fprintf(stderr," from being decoded and displays the values in Hexadecimal notation  (this \n");
  fprintf(stderr," parameter has no effect on data that are not RLE).  The 'bscan' option (for \n");
  fprintf(stderr," radial based products only) formats the output in a unique tabular format. \n");
  fprintf(stderr," SPECIAL NOTE: the 'bscan' option overrides the <content selector> and displays \n");
  fprintf(stderr," all radials.  The 'bscan' option does not work with a generic radial component.\n");
  fprintf(stderr," \n");
  fprintf(stderr," The <decode selector> is used with digital radial data (packet 16). If a  \n");
  fprintf(stderr," <decode selector> is not used, the data (including reflectivity, velocity and \n");
  fprintf(stderr," spectrum width) remain encoded as in the product. The optional modifier 'D'  \n");
  fprintf(stderr," states the number of digits after the decimal point (0-6).  If the modifier is  \n");
  fprintf(stderr," not used the default is 3 digits.\n");
  fprintf(stderr," \n");
  fprintf(stderr," The 'fdecode' option uses Scale-Offset parameters that are either already\n");
  fprintf(stderr," included in CVT or are contained in a user provided file. The file must be  \n");
  fprintf(stderr," placed into the ~/.cvt/ directory with a name 'decode_params.<product id>'\n");
  fprintf(stderr," The 'pdecode' option uses Scale-Offset parameters within the product itself.\n");
  fprintf(stderr," \n"); 
  fprintf(stderr,"- Examples of the Use of Output Modifiers\n");
  fprintf(stderr,"  ---------------------------------------\n");
  fprintf(stderr," \n");
  fprintf(stderr,"    radial A             Print contents of radial A from message 'X'\n");
  fprintf(stderr,"    radial A deg         Print contents of radial A degrees from message 'X'\n");
  fprintf(stderr,"    radial A B           Print contents of radials from A to B inclusive\n");
  fprintf(stderr,"    radial A B deg rle   Print contents of radial A degrees to B degrees\n");
  fprintf(stderr,"                             inclusive leaving data in RLE format\n");
  fprintf(stderr,"    radial all bscan     Print contents of all radials using the bscan format\n");
  fprintf(stderr,"    radial all           Print all radial data from message 'X' in default\n");
  fprintf(stderr,"                             (decimal) format\n");
  fprintf(stderr,"    row A B              Print data from row A to B inclusive from message 'X'\n");
  fprintf(stderr,"    row all              Print data from all rows in default (decimal)format\n");
  fprintf(stderr,"                             in run length encoded (rle) format\n");
  fprintf(stderr,"    layer C radial A     Print data from radial A within layer C\n");
  fprintf(stderr,"                             Layer numbers can be found using the summary option\n");
  fprintf(stderr,"                             and must be used if more than 1 layer exists\n");
  fprintf(stderr," \n");
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Generic Product Display Commands\n");
  fprintf(stderr,"  -------------------------------------\n");  
  fprintf(stderr," Current guidance limits generic products to a single data packet 28 in layer 1\n");
  fprintf(stderr," and no GAB and TAB.  The basic form for display of a generic product is: \n");
  fprintf(stderr," \n");
  fprintf(stderr,"     cvt msg X generic <generic modifier list>\n");
  fprintf(stderr," \n");
  fprintf(stderr," If a generic product modifier list is not used then the entire product is \n");
  fprintf(stderr," displayed (with no decoding of any unsigned integer data arrays).\n");
  fprintf(stderr," \n");
  fprintf(stderr," If the generic product contains a generic radial component, the radial \n");
  fprintf(stderr," modifier can be used with a <content selector> to display selected radials:\n");
  fprintf(stderr," \n");
  fprintf(stderr,"     cvt msg X generic radial <content selector>\n");  
  fprintf(stderr," \n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Generic Product Modifier List Structure\n");
  fprintf(stderr,"  -----------------------\n");
  fprintf(stderr," A Generic Product Modifier list consists of optional selectors: <component list>\n");
  fprintf(stderr," selector, <component print> selector, <parameter print> selector, and <decode \n");
  fprintf(stderr," selector>. These can be used in any order though use of a <component list> \n");
  fprintf(stderr," selector will render the <component print> selector non-functional.  \n");
  fprintf(stderr," The possible values for the selectors are: \n");
  fprintf(stderr," \n");
  fprintf(stderr,"                               [<component list>]\n");
  fprintf(stderr,"---------------------------------------------------------------------------------\n");
  fprintf(stderr,"list_all | list_area | list_rad | list_text | list_table | list_grid | list_event\n");
  fprintf(stderr," \n");
  fprintf(stderr," The list selector provides a simple listing of components with an index into \n");
  fprintf(stderr," the component array. 'list_all' causes all components to be listed.  The other \n");
  fprintf(stderr," commands create a listing of all components of a particular type.  Using any \n");
  fprintf(stderr," list selector disables the component print selectors. \n");
  fprintf(stderr," \n");
  fprintf(stderr,"                               [<component print>]\n");
  fprintf(stderr,"  ----------------------------------------------------------------------------\n");
  fprintf(stderr,"  print_area | print_rad | print_text | print_table | print_grid | print_event\n");
  fprintf(stderr," \n");
  fprintf(stderr,"  print X\n");
  fprintf(stderr," \n");
  fprintf(stderr," By default, all components are printed unless a component print selector or\n");
  fprintf(stderr," component list selector is used.  The print selector has two forms.  The first\n");
  fprintf(stderr," causes all components of a particular type to be displayed.  The second form \n");
  fprintf(stderr," 'print X' causes the component with an index 'X' to be printed.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"                               [<parameter print>]               \n");
  fprintf(stderr,"                 ----------------------------------------------- \n");
  fprintf(stderr,"                 no_pparams | no_cparams | no_pparams no_cparams \n");
  fprintf(stderr," \n");
  fprintf(stderr," A The parameter print selector controls whether the product parameters and \n");
  fprintf(stderr," parameters associated with individual components are printed.  The default is \n");
  fprintf(stderr," all parameters printed.  Both values can be used together to eliminate the \n");
  fprintf(stderr," printing of all parameters.\n");
  fprintf(stderr," \n");

  fprintf(stderr,"                            [<radial content selector>] \n");
  fprintf(stderr,"                           -----------------------------\n");
  fprintf(stderr,"                           radial  {A | A B | all} [deg] \n");
  fprintf(stderr," \n");
  fprintf(stderr," The radial content selector can be used with generic radial components.  If \n");
  fprintf(stderr," no selector is provided, all radials are selected.  The default behavior of \n");
  fprintf(stderr," the radial content selector is to select radials by their ordinal value. A  \n");
  fprintf(stderr," 'deg' option is provided to select radials by degrees (the input is in whole \n");
  fprintf(stderr," degrees and the radials are selected inclusively).\n");
  fprintf(stderr," \n");
  fprintf(stderr,"                                [<decode selector>]\n");
  fprintf(stderr,"                             ----------------------- \n");
  fprintf(stderr,"                             {fdecode | pdecode} [D] \n");
  fprintf(stderr," \n");
  fprintf(stderr," The decode selector causes the data values in the unsigned integer arrays \n");
  fprintf(stderr," (associated with radial and grid components) to be decoded using Scale-Offset \n");
  fprintf(stderr," parameters.  The optional modifier 'D' states the number of digits after the  \n");
  fprintf(stderr," decimal point (0-6).  If the modifier is not used the default is 3 digits. \n");
  fprintf(stderr," \n");  
  fprintf(stderr," The 'fdecode' option uses Scale-Offset parameters that are either already\n");
  fprintf(stderr," included in CVT or are contained in a user provided file. The file must be  \n");
  fprintf(stderr," placed into the ~/.cvt/ directory with a name 'decode_params.<product id>'\n");
  fprintf(stderr," The 'pdecode' option uses Scale-Offset parameters within the product itself.\n");
  fprintf(stderr," \n");  
  fprintf(stderr,"- Examples of the Use of Output Modifiers\n");
  fprintf(stderr,"  ---------------------------------------\n");
  fprintf(stderr," \n");
  fprintf(stderr,"generic                       Print entire generic product\n");
  fprintf(stderr,"generic no_pparams no_cparams Print entire generic product, omitting both \n");
  fprintf(stderr,"                                  product parameters and component parameters\n");
  fprintf(stderr,"generic list_all              Print a listing of all components\n");
  fprintf(stderr,"generic list_area             Print a listing of all area components\n");
  fprintf(stderr,"generic list_area no_pparams  Print a list of all area components, omit product\n");
  fprintf(stderr,"                                  parameters\n");
  fprintf(stderr,"generic print X               Print the component with the index 'X' in the\n");
  fprintf(stderr,"                                  component listing\n");
  fprintf(stderr,"generic print_area            Print all area components in the generic product\n");
  fprintf(stderr,"generic print_area no_cparams Print all area components, omit area component\n");
  fprintf(stderr,"                                  parameters\n");
  fprintf(stderr,"generic print_radial          Print all radial components \n");
  fprintf(stderr,"generic print_radial radial A Print all radial components but only print data\n");
  fprintf(stderr,"                                  for radial A\n");
  fprintf(stderr,"generic radial A deg          Print entire generic product except only print\n");
  fprintf(stderr,"                                  data for radial A degrees in radial component\n");
  fprintf(stderr,"generic radial A B            Print entire generic product except only print\n");
  fprintf(stderr,"                                  data from radial A to radial B inclusive\n");
  fprintf(stderr," \n");
  fprintf(stderr," For generic products containing radial components, the modifier 'generic' can\n");
  fprintf(stderr," be omitted if the 'radial' modifier is used. However without the 'generic'  \n");
  fprintf(stderr," modifier the [<component list>], [<component print>], and <parameter print>] \n");
  fprintf(stderr," selectors will not function.\n");
  fprintf(stderr," \n");
  fprintf(stderr,"==============================================================================\n");
  fprintf(stderr," \n");
  fprintf(stderr,"- Product Extraction Commands\n");  
  fprintf(stderr,"  ---------------------------\n");
  fprintf(stderr," \n");
  fprintf(stderr," CVT can extract ICD formatted final product messages from the product database\n");
  fprintf(stderr," linear buffer. In addition, CVT can extract intermediate product messages from\n");
  fprintf(stderr," either the product database linear buffer (if warehoused) or the individual \n");
  fprintf(stderr," linear buffer.  The basic form of the product extraction commands are:\n");
  fprintf(stderr," \n");  
  fprintf(stderr,"cvt msg X extract    Extracts the contents of message 'X' from the \n");
  fprintf(stderr,"                          product database linear buffer (default) into the\n");  
  fprintf(stderr,"                          file $HOME/graphic/buffer.out (binary output)\n");
  fprintf(stderr,"cvt msg X hexdump    Extracts the contents of message 'X' from the \n");
  fprintf(stderr,"                          product database linear buffer (default) into the\n");  
  fprintf(stderr,"                          file $HOME/graphic/hexdump.out (ASCII dump in Hex)\n");
  fprintf(stderr," \n");  
  fprintf(stderr," The default output file is $HOME/graphic/buffer.out for the extract command\n");
  fprintf(stderr," and $HOME/graphic/hexdump.out for the hexdump command.\n");
  fprintf(stderr," \n");
  fprintf(stderr," The basic extraction commands use the product database linear buffer \n"); 
  fprintf(stderr," ($ORPGDIR/pdist/product_data_base.lb) as the default input source.\n");  
  fprintf(stderr," \n");
  fprintf(stderr,"- Redirecting Extraction input and output\n");
  fprintf(stderr,"  ---------------------------\n");
  fprintf(stderr," \n");
  fprintf(stderr," The '-in' and '-out' options can be used to redirect the input and output from\n");
  fprintf(stderr,"  their default locations.\n");
  fprintf(stderr," \n");  
  fprintf(stderr," -in LBNAME          Extracts contents of message 'X' from the linear buffer\n");
  fprintf(stderr,"                          file $ORPGDIR/LBNAME rather than the product database\n");
  fprintf(stderr," -out FILENAME       Outputs the results of the extract / hexdump to a file\n");
  fprintf(stderr,"                          named $HOME/FILENAME rather than the default file\n");
  fprintf(stderr," \n");
  fprintf(stderr," The default extraction includes a 96 byte header created by the OR PG. To remove\n");
  fprintf(stderr," this \"Pre-ICD\" header, use the following flag:\n");
  fprintf(stderr," \n");
  fprintf(stderr," -nohdr              Causes the extract command to skip over the first 96 byte\n");
  fprintf(stderr,"                          header (which leaves the ICD compatible product)\n");
  fprintf(stderr," \n");
  fprintf(stderr," -nodc               CVT automatically decompresses compressed products. This\n");
  fprintf(stderr,"                          option skips decompression during extraction.\n");  
  fprintf(stderr," \n");
  fprintf(stderr," The complete form of the product extraction command, optional parts in [], is:\n");
  fprintf(stderr," \n");  
  fprintf(stderr,"     cvt msg X extract [-nohdr] [-nodc] [-in LBNAME] [-out FILENAME]\n");
  fprintf(stderr,"     cvt msg X hexdump [-nohdr] [-nodc] [-in LBNAME] [-out FILENAME]\n"); 
  fprintf(stderr," \n"); 
  fprintf(stderr,"==============================================================================\n");

}



void version_information() {
  /* show program version and credit information */
  /* CV is defined inside cvt.h */
  fprintf(stderr,"\nCODEview Text for the WSR-88D Open Systems RPG\n");
  fprintf(stderr,"-----------------------------------------\n\n");
  
  fprintf(stderr,"%s\n",CV);
  fprintf(stderr,"Release Date: %s\n\n",DATE);
  
  fprintf(stderr,"Provided to the NWS Office of Science & Technology by\n");
  fprintf(stderr,"     Noblis, Inc. of Falls Church, Virginia \n\n");

  fprintf(stderr,"Techncal Contact:  Brian Klein  brian.klein@noaa.gov\n");
  fprintf(stderr,"\n");

}


