# RCS info
# $Author: eforren $
# $Locker:  $
# $Date: 2000/01/26 15:27:13 $
# $Id: makefile,v 1.1 2000/01/26 15:27:13 eforren Exp $
# $Revision: 1.1 $
# $State: Exp $

include $(MAKEINC)/make.common
include $(MAKEINC)/make.$(ARCH)

BINMAKEFILES =  le_pipe.mak 

include $(MAKEINC)/make.parent_bin

