

Product {
    prod_code	19    2
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 8242 -1 -1 -1
}

Product {
    prod_code	20    4
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 5 -1 -1 -1
}

Product {
    prod_code	27	15
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 5 -1 -1 -1
}

Product {
    prod_code	27	15
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 24 -1 -1 -1
}

Product {
    prod_code	26	13
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 5 -1 -1 -1
}

Product {
    prod_code	25	11
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 15 -1 -1 -1
}

Product {
    prod_code	18	7
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 15 -1 -1 -1
}

Product {
    prod_code	38	25
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	55	69
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	0 0 15 -1 -1 -1
}

Product {
    prod_code	26	13
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 15 -1 -1 -1
}

Product {
    prod_code	19	2
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 43 -1 -1 -1
}

Product {
    prod_code	56	68
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 24 -1 -1 -1
}

Product {
    prod_code	30	10
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 5 -1 -1 -1
}

Product {
    prod_code	61	80
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	33	58
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	58	51
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	27	15
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 34 -1 -1 -1
}

Product {
    prod_code	46	59
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	0 0 15 -1 -1 -1
}

Product {
    prod_code	44	62
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	0 0 5 -1 -1 -1
}

Product {
    prod_code	27	15
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 43 -1 -1 -1
}

Product {
    prod_code	43	60
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	0 0 5 -1 -1 -1
}

Product {
    prod_code	60	42
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	31	56
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 1 -1 -1 -1 -1
}

Product {
    prod_code	80	107
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	35	24
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	55	69
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	0 0 5 -1 -1 -1
}

Product {
    prod_code	48	35
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	59	33
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	90	117
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	62	49
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 -1 -1 -1 -1
}

Product {
    prod_code	87	114
    flag	0x8000
    seq_number	0
    num_prods	-1
    interval	1
    vol_date	0
    vol_time	0
    params	-1 -1 ALG -1 -1 -1
}
