# RCS info
# $Author: aamir $
# $Locker:  $
# $Date: 1998/06/08 14:55:33 $
# $Id: make.script,v 1.1 1998/06/08 14:55:33 aamir Exp $
# $Revision: 1.1 $
# $State: Exp $

# This is the generic "include" make description file for installing scripts.
#

install:: $(TARGET).script
	@if [ -d $(SCRIPTDIR) ]; then set +x; \
	else (set -x; $(MKDIR) $(SCRIPTDIR)); fi
	$(INSTALL) $(INSTBINFLAGS) $(TARGET).script $(SCRIPTDIR)/$(TARGET)

