#!/usr/bin/ksh
#
# RCS info
# $Author: cheryls $
# $Locker:  $
# $Date: 2007/10/23 20:13:58 $
# $Id: create_sample_maps,v 1.3 2007/10/23 20:13:58 cheryls Exp $
# $Revision: 1.3 $
# $State: Exp $
#################################################################
# create_sample_maps
#################################################################

print "Creating a few sample map files, wait one moment \n"

if [[ -f us_map.dat.bz2 ]] then
    if [[ -f us_map.dat ]] then
        cp -f us_map.dat us_map.dat.OLD
    fi
    print "Decompressing map data file: us_map.dat"
    bunzip2 -f us_map.dat.bz2
fi

if [[ -f ak_map.dat.bz2 ]] then
    if [[ -f ak_map.dat ]] then
        cp -f ak_map.dat ak_map.dat.OLD
    fi
    print "Decompressing map data file: ak_map.dat"
    bunzip2 -f ak_map.dat.bz2
fi

if [[ -f hi_map.dat.bz2 ]] then
    if [[ -f hi_map.dat ]] then
        cp -f hi_map.dat hi_map.dat.OLD
    fi
    print "Decompressing map data file: hi_map.dat"
    bunzip2 -f hi_map.dat.bz2
fi


map_cvg -D kbmx -I us_map.dat


map_cvg -D kbox -I us_map.dat


map_cvg -D kbuf -I us_map.dat


map_cvg -D kffc -I us_map.dat


map_cvg -D kftg -I us_map.dat


map_cvg -D khgx -I us_map.dat


map_cvg -D klix -I us_map.dat


map_cvg -D klwx -I us_map.dat


map_cvg -D kmlb -I us_map.dat


map_cvg -D kmtx -I us_map.dat


map_cvg -D ktlx -I us_map.dat


