#!/usr/bin/ksh
#
# RCS info
# $Author: cheryls $
# $Locker:  $
# $Date: 2007/10/23 20:13:57 $
# $Id: create_all_cvg_maps,v 1.3 2007/10/23 20:13:57 cheryls Exp $
# $Revision: 1.3 $
# $State: Exp $
#################################################################
# create_all_cvg_maps
#################################################################

print "\nCREATING CVG BACKGROUND MAP FILES \n"

print "This script must be executed from the directory containing "
print "the CVG map data files (us_map.dat, etc.) which are normally"
print "installed in the $HOME/tools/cvg_map directory.\n"

print "This script can create all or selected cvg map files."
print "The data are limited to US NEXRAD sites. \n"

print "If you wish to customize the map filenames, select a map range"
print "other than 250 NM, or specify a custom center Lat Long, then"
print "select 'n' at the prompt and execute 'map_cvg' with no arguments.\n"

print "Simply uncomment the lines for the NEXRAD sites "
print "for which you wish to create a map file, then execute "
print "this script and enter 'y' \n"

print "If you have not modified the script or are in the incorrect"
print "directory, enter 'n' \n"

print "DO YOU WISH TO PROCEED, 'y/n' \n"

read ans

if [[ "$ans" == "y" || "$ans" == "Y" ]]
then

if [[ -f us_map.dat.bz2 ]] then
    if [[ -f us_map.dat ]] then
        cp -f us_map.dat us_map.dat.OLD
    fi
    print "Decompressing map data file: us_map.dat"
    bunzip2 -f us_map.dat.bz2
fi

if [[ -f ak_map.dat.bz2 ]] then
    if [[ -f ak_map.dat ]] then
        cp -f ak_map.dat ak_map.dat.OLD
    fi
    print "Decompressing map data file: ak_map.dat"
    bunzip2 -f ak_map.dat.bz2
fi

if [[ -f hi_map.dat.bz2 ]] then
    if [[ -f hi_map.dat ]] then
        cp -f hi_map.dat hi_map.dat.OLD
    fi
    print "Decompressing map data file: hi_map.dat"
    bunzip2 -f hi_map.dat.bz2
fi

#map_cvg -D kabr -I us_map.dat
#map_cvg -D kabx -I us_map.dat
#map_cvg -D kakq -I us_map.dat
#map_cvg -D kama -I us_map.dat
#map_cvg -D kamx -I us_map.dat
#map_cvg -D kapx -I us_map.dat
#map_cvg -D karx -I us_map.dat
#map_cvg -D katx -I us_map.dat
#map_cvg -D kbbx -I us_map.dat
#map_cvg -D kbgm -I us_map.dat
#map_cvg -D kbhx -I us_map.dat
#map_cvg -D kbis -I us_map.dat
#map_cvg -D kblx -I us_map.dat
#map_cvg -D kbmx -I us_map.dat
#map_cvg -D kbox -I us_map.dat
#map_cvg -D kbro -I us_map.dat
#map_cvg -D kbuf -I us_map.dat
#map_cvg -D kbyx -I us_map.dat
#map_cvg -D kcae -I us_map.dat
#map_cvg -D kcbw -I us_map.dat
#map_cvg -D kcbx -I us_map.dat
#map_cvg -D kccx -I us_map.dat
#map_cvg -D kcle -I us_map.dat
#map_cvg -D kclx -I us_map.dat
#map_cvg -D kcrp -I us_map.dat
#map_cvg -D kcxx -I us_map.dat
#map_cvg -D kcys -I us_map.dat
#map_cvg -D kdax -I us_map.dat
#map_cvg -D kddc -I us_map.dat
#map_cvg -D kdfx -I us_map.dat
#map_cvg -D kdgx -I us_map.dat
#map_cvg -D kdix -I us_map.dat
#map_cvg -D kdlh -I us_map.dat
#map_cvg -D kdmx -I us_map.dat
#map_cvg -D kdox -I us_map.dat
#map_cvg -D kdtx -I us_map.dat
#map_cvg -D kdvn -I us_map.dat
#map_cvg -D kdyx -I us_map.dat
#map_cvg -D keax -I us_map.dat
#map_cvg -D kemx -I us_map.dat
#map_cvg -D kenx -I us_map.dat
#map_cvg -D keox -I us_map.dat
#map_cvg -D kepz -I us_map.dat
#map_cvg -D kesx -I us_map.dat
#map_cvg -D kevx -I us_map.dat
#map_cvg -D kewx -I us_map.dat
#map_cvg -D keyx -I us_map.dat
#map_cvg -D kfcx -I us_map.dat
#map_cvg -D kfdr -I us_map.dat
#map_cvg -D kfdx -I us_map.dat
#map_cvg -D kffc -I us_map.dat
#map_cvg -D kfsd -I us_map.dat
#map_cvg -D kfsx -I us_map.dat
#map_cvg -D kftg -I us_map.dat
#map_cvg -D kfws -I us_map.dat
#map_cvg -D kggw -I us_map.dat
#map_cvg -D kgjx -I us_map.dat
#map_cvg -D kgld -I us_map.dat
#map_cvg -D kgrb -I us_map.dat
#map_cvg -D kgrk -I us_map.dat
#map_cvg -D kgrr -I us_map.dat
#map_cvg -D kgsp -I us_map.dat
#map_cvg -D kgwx -I us_map.dat
#map_cvg -D kgyx -I us_map.dat
#map_cvg -D khdx -I us_map.dat
#map_cvg -D khgx -I us_map.dat
#map_cvg -D khnx -I us_map.dat
#map_cvg -D khpx -I us_map.dat
#map_cvg -D khtx -I us_map.dat
#map_cvg -D kict -I us_map.dat
#map_cvg -D kicx -I us_map.dat
#map_cvg -D kiln -I us_map.dat
#map_cvg -D kilx -I us_map.dat
#map_cvg -D kind -I us_map.dat
#map_cvg -D kinx -I us_map.dat
#map_cvg -D kiwa -I us_map.dat
#map_cvg -D kiwx -I us_map.dat
#map_cvg -D kjan -I us_map.dat
#map_cvg -D kjax -I us_map.dat
#map_cvg -D kjgx -I us_map.dat
#map_cvg -D kjkl -I us_map.dat
#map_cvg -D klbb -I us_map.dat
#map_cvg -D klch -I us_map.dat
#map_cvg -D klix -I us_map.dat
#map_cvg -D klnx -I us_map.dat
#map_cvg -D klot -I us_map.dat
#map_cvg -D klrx -I us_map.dat
#map_cvg -D klsx -I us_map.dat
#map_cvg -D kltx -I us_map.dat
#map_cvg -D klvx -I us_map.dat
#map_cvg -D klwx -I us_map.dat
#map_cvg -D klzk -I us_map.dat
#map_cvg -D kmaf -I us_map.dat
#map_cvg -D kmax -I us_map.dat
#map_cvg -D kmbx -I us_map.dat
#map_cvg -D kmhx -I us_map.dat
#map_cvg -D kmkx -I us_map.dat
#map_cvg -D kmlb -I us_map.dat
#map_cvg -D kmob -I us_map.dat
#map_cvg -D kmpx -I us_map.dat
#map_cvg -D kmqt -I us_map.dat
#map_cvg -D kmrx -I us_map.dat
#map_cvg -D kmsx -I us_map.dat
#map_cvg -D kmtx -I us_map.dat
#map_cvg -D kmux -I us_map.dat
#map_cvg -D kmvx -I us_map.dat
#map_cvg -D kmxx -I us_map.dat
#map_cvg -D knkx -I us_map.dat
#map_cvg -D knqa -I us_map.dat
#map_cvg -D koax -I us_map.dat
#map_cvg -D kohx -I us_map.dat
#map_cvg -D kokx -I us_map.dat
#map_cvg -D kotx -I us_map.dat
#map_cvg -D kpah -I us_map.dat
#map_cvg -D kpbz -I us_map.dat
#map_cvg -D kpdt -I us_map.dat
#map_cvg -D kpoe -I us_map.dat
#map_cvg -D kpux -I us_map.dat
#map_cvg -D krax -I us_map.dat
#map_cvg -D krgx -I us_map.dat
#map_cvg -D kriw -I us_map.dat
#map_cvg -D krlx -I us_map.dat
#map_cvg -D krtx -I us_map.dat
#map_cvg -D ksfx -I us_map.dat
#map_cvg -D ksgf -I us_map.dat
#map_cvg -D kshv -I us_map.dat
#map_cvg -D ksjt -I us_map.dat
#map_cvg -D ksox -I us_map.dat
#map_cvg -D ksrx -I us_map.dat
#map_cvg -D ktbw -I us_map.dat
#map_cvg -D ktfx -I us_map.dat
#map_cvg -D ktlh -I us_map.dat
#map_cvg -D ktlx -I us_map.dat
#map_cvg -D ktwx -I us_map.dat
#map_cvg -D ktyx -I us_map.dat
#map_cvg -D kudx -I us_map.dat
#map_cvg -D kuex -I us_map.dat
#map_cvg -D kvax -I us_map.dat
#map_cvg -D kvbx -I us_map.dat
#map_cvg -D kvnx -I us_map.dat
#map_cvg -D kvtx -I us_map.dat
#map_cvg -D kyux -I us_map.dat
#map_cvg -D pabc -I ak_map.dat
#map_cvg -D pacg -I ak_map.dat
#map_cvg -D paec -I ak_map.dat
#map_cvg -D pahg -I ak_map.dat
#map_cvg -D paih -I ak_map.dat
#map_cvg -D pakc -I ak_map.dat
#map_cvg -D papd -I ak_map.dat
#map_cvg -D phki -I hi_map.dat
#map_cvg -D phkm -I hi_map.dat
#map_cvg -D phmo -I hi_map.dat
#map_cvg -D phwa -I hi_map.dat
#map_cvg -D kbix -I us_map.dat
#map_cvg -D drx1 -I us_map.dat
#map_cvg -D ncdc -I us_map.dat
#map_cvg -D kvwx -I us_map.dat

else

   print "\nSCRIPT ABORTED, NO MAPS CREATED \n"
   
fi