#!/usr/bin/ksh
#################################################################
# FILE: cvg_globalinstall
#
# Script to install CVG into /usr/local/bin
# 
# Must be exectued from the cvg source code directory
# after cvg is compiled
#
# Must be logged in with administrative permissions
#
################################################################

# to change the location of the installed executables
# modify the value of CVG_INSTALL_DIR

CVG_INSTALL_DIR=/usr/local/bin


#make sure the CVG_INSTALL_DIR directory exists
if [[ ! -d ${CVG_INSTALL_DIR} ]] then 
    mkdir -p ${CVG_INSTALL_DIR}  
    print creating directory ${CVG_INSTALL_DIR}
fi

print "\nINSTALLING CVG TO ${CVG_INSTALL_DIR}"

rm -f  ${CVG_INSTALL_DIR}/cvg
cp -p ${ARCH}/cvg ${CVG_INSTALL_DIR}/cvg
chmod a+x ${CVG_INSTALL_DIR}/cvg

rm -f  ${CVG_INSTALL_DIR}/cvg_color_edit
cp -p ${ARCH}/cvg_color_edit ${CVG_INSTALL_DIR}/cvg_color_edit
chmod a+x ${CVG_INSTALL_DIR}/cvg_color_edit

rm -f  ${CVG_INSTALL_DIR}/cvg_read_db
cp -p ${ARCH}/cvg_read_db ${CVG_INSTALL_DIR}/cvg_read_db
chmod a+x ${CVG_INSTALL_DIR}/cvg_read_db

rm -f  ${CVG_INSTALL_DIR}/map_cvg
cp -p ${ARCH}/map_cvg ${CVG_INSTALL_DIR}/map_cvg
chmod a+x ${CVG_INSTALL_DIR}/map_cvg

print "\nDONE"
