/*
 * RCS info
 * $Author: cheryls $
 * $Locker:  $
 * $Date: 2007/04/03 21:14:59 $
 * $Id: logos.h,v 1.3 2007/04/03 21:14:59 cheryls Exp $
 * $Revision: 1.3 $
 * $State: Exp $
 */
/* logos.h */

#ifndef _LOGOS_H_
#define _LOGOS_H_


/* XPM */
static char *faa_logo[] = {
/* width height num_colors chars_per_pixel */
"   110   105       71            2",
/* colors */
".. c #c0c0c0",
".# c #555555",
".a c #efd6c6",
".b c #e7e7d6",
".c c #669900",
".d c #999900",
".e c #cc9900",
".f c #66cc00",
".g c #99cc00",
".h c #cccc00",
".i c #000033",
".j c #330033",
".k c #333333",
".l c #663333",
".m c #006633",
".n c #336633",
".o c #666633",
".p c #996633",
".q c #009933",
".r c #339933",
".s c #669933",
".t c #999933",
".u c #cc9933",
".v c #33cc33",
".w c #66cc33",
".x c #99cc33",
".y c #cccc33",
".z c #000066",
".A c #330066",
".B c #003366",
".C c #333366",
".D c #663366",
".E c #006666",
".F c #336666",
".G c #666666",
".H c #996666",
".I c #339966",
".J c #669966",
".K c #999966",
".L c #cc9966",
".M c #33cc66",
".N c #cccc66",
".O c #ffcc66",
".P c #333399",
".Q c #336699",
".R c #663399",
".S c #996699",
".T c #669999",
".U c #999999",
".V c #66cc66",
".W c #99cc99",
".X c #cccc99",
".Y c #ffcc99",
".Z c #66cc99",
".0 c #ccff99",
".1 c #ffff99",
".2 c #666699",
".3 c #9999cc",
".4 c #cc99cc",
".5 c #99cccc",
".6 c #cccccc",
".7 c #ffcccc",
".8 c #ccffcc",
".9 c #ffffcc",
"#. c #ccccff",
"## c #ffccff",
"#a c #ccffff",
"#b c #dddddd",
"#c c #f1f1f1",
"#d c #fffbf0",
"#e c #ffffff",
/* pixels */
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.b.b.9.6.9.6.9.9.b.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.9.6.O.N.O.X.1.1.9.7.9.9.9.X.Y.N.O.N.7.8#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.N.N.Y#e#d.9.Y.X.O.N.N.Y.Y.1.6.9.9.Y.X.X.N.N.X.1.8#e#e.X.O.7.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.9.N.N#d#d.9.X.N.X.9.9#e#e#e#e#e#e#e#e#e#e#e#e#e#e.9.a.X.N.X.9#e.9.N.N.7#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.N.Y#e#e.N.N.Y.9#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.9.X.N.9#d#d.0.Y#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.Y.N#e.8.Y.N#d#e#e#e#e#e#e#e.6.3.3.2.2.2.P.G.R.2.2.U.3#.#e#e#e#e#e#e#e.X.N.Y.9.9.N.X#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.Y.9#e.Y.O.9#e#e#e#d#..U.R.C.A.C.A.A.C.A.C.C.C.A.C.z.A.C.A.C.C.C.A.B.C.R.3.6#e#e#e#e.1.N.Y#e.O.X#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.N.1.X.N.0#e#e#e#e#b.G.A.C.A.A.C.A.C.A.C.z.C.B.A.C.A.C.z.C.A.B.C.A.C.A.A.C.A.C.3.b#e#e#e#d.0.O#e.9.N.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.X.O#d.b.Y#e#e#e#e.6.2.C.A.C.A.C.C.A.B.A.A.C.A.C.A.C.z.C.A.A.C.C.A.A.B.A.C.A.B.A.C.A.C.2.6#e#e#e#d.N.9#e.O#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.9#e.X.O#e#e#e#e.2.A.A.C.B.A.C.C.C.C.A.C.B.C.A.C.C.A.C.C.z.A.C.A.C.A.C.A.C.C.C.A.C.C.A.C.A.6#e#e#e.9.N.X#d.N.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.X.1#e.O#d#e#e#..T.C.A.A.C.A.A.#.t.C.A.A.C.A.C.C.A.C.A.C.A.C.A.C.A.C.A.C.C.C.p.t.H.C.A.o.C.A.C.A.A.C.A.U#e#e#e#e.X#e.1.X#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N.9#c.N#e#e#e#e.C.A.A.C.C.z.C.C.C.e.C.C.B.C.A.C.A.C.C.z.A.C.z.C.A.A.C.B.A.A.o.t.C.t.A.C.G.A.C.A.C.C.A.C.z.3#e#e#e.1.N.b.9#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.9.a.N.9#e#e#..2.A.C.C.A.D.C.A.B.C.p.G.C.C.A.B.A.A.C.A.C.C.A.C.C.A.A.C.A.C.o.u.G.A.t.C.z.o.z.C.A.B.G.A.C.C.C.2###d#e.7.N.9.N.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.N.9.N.9#e#e.6.C.C.B.C.A.C.t.o.C.C.C.D.d.C.C.A.C.A.A.C.z.C.C.B.j.C.A.A.C.A.C.u.o.t.t.d.C.C.H.C.A.C.D.p.C.z.C.C.A.C.6#e#e.9.N#d.N.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.N#c.1#d#e#e##.A.C.z.C.A.B.A.C.D.C.p.t.C.A.t.o.C.C.C.C.C.A.C.A.A.C.A.C.z.A.C.A.G.C.A.C.A.t.C.C.H.C.C.u.o.A.C.t.l.A.C.A.C.2#e#e#e.N.Y#e.O#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N#d.Y.X#e#e#..G.C.A.C.A.A.C.A.C.#.C.p.x.G.C.D.t.p.t.o.A.z.C.A.C.A.B.C.A.C.C.A.C.C.C.A.C.A.t.l.A.s.D.d.G.A.C.p.t.C.B.C.A.B.A.2###e#e.X.1#c.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.1.N#e#e#b.2.A.C.C.p.t.C.C.A.C.t.t.p.C.t.t.C.t.G.C.C.A.A.C.A.C.C.A.C.k.A.B.A.C.A.A.B.C.A.o.D.C.p.t.D.C.A.D.t.C.z.A.C.A.C.C.A.F#.#e#e.N.Y.N#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N.Y.X#e#e.6.C.A.C.#.t.o.G.t.A.B.A.t.D.C.A.C.o.C.C.C.A.C.z.G.2.U.3.6#c.6.L#a.6.4.T.2.C.A.C.A.C.C.A.t.D.C.C.z.e.G.A.C.C.C.o.o.A.C.A.G#e#e#e.N.9.N#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.Y.0.9#e#e#e#c.A.B.A.C.u.C.C.A.u.C.C.A.t.C.A.C.C.C.C.C.6#e#e#e#e#e#e#e#e#e.e.e.6#e#e#e#e#e#e#e#e.2.P.C.A.C.z.C.D.C.A.C.o.t.D.G.t.C.A.C.C.2#c#e#e.N.9.Y.X#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.N#e.N#e#d##.2.A.C.C.A.p.t.C.C.t.C.A.C.d.A.B.A.A.C.3#.#e#e#e#e#e#e#e#e#e.6.h.d.y#e#e#e#e#e#e#e#e#e#e.4.C.A.C.A.t.C.G.d.u.C.C.p.o.A.C.C.z.A.2#e#e.9.N#e.O#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N#d.Y.Y#e#e.2.A.A.o.t.A.A.t.p.C.u.t.t.o.C.C.A.C.3#e#e#e#e#e#e#e#e#e#e#e#e.u.h.d.e#e#e#e#e#e#e#e#e#e#e#e#e.C.C.A.C.t.t.D.C.p.C.e.P.C.D.t.D.z.C.2#e#e.Y.0#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.Y.9.N#e#e.3.C.C.G.u.C.A.A.C.t.t.C.C.D.G.C.A.C.2#e#e#e#e#e#e#e#e#e#e#e#e.b.9.t.e.X#d#e#e#e#e#e#e#e#e#e#e#e#e.3.C.C.A.C.A.C.s.u.t.A.A.C.o.t.A.C.A.3#e#e.N.7.X#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N.N.9#e#e.P.C.A.C.p.C.A.C.o.C.A.C.o.A.C.A.2#e#e#e#e#e#e#e#e#e#e#e#e#e#e.u.X.L.d.d.u.X.e.9#e#e#e#e#e#e#e#e#e#e#e#e#e.A.C.A.C.A.h.C.C.G.e.G.A.D.C.A.C#e#e#e.9#d.N#c#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.7.0.N#e#e#e.A.C.A.B.t.t.C.t.A.C.A.C.C.C.z.C#e#e#e#e#e#e#e#e#e#e#e#e#e#e.6.d.W.J.d.d.K.W.t.6#e#e#e#e#e#e#e#e#e#e#e#e#e.4.C.C.A.D.t.A.C.d.G.C.C.B.A.C.A.S#e#e#e.9.Y.0#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.y#e#e#e#e.6.C.A.C.A.C.p.u.p.B.A.G.p.C.A.C.6#e#e#e#e#e#e#e#e#e#e#d#..J.r.r.s.s.v.u.d.s.r.s.s.I.W#c#e#e#e#e#e#e#e#e#e#e#e#..C.C.G.o.C.G.D.C.A.A.o.t.C.C.C.6#e#e.N#e.N.b#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e.X.9.Y#e#e#e.P.C.A.C.C.C.A.s.t.C.D.d.C.C.C.6#e#e#e#e#e#e#e#e#e#c.W.J.r.r.J.s.r.s.r.e.d.s.s.r.s.r.s.r.J.5#e#e#e#e#e#e#e.X#e#d#..D.A.C.H.e.C.A.B.C.u.C.A.C.C.R#e#e.Y.0.7.Y#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e.X.9.X.9#e#..C.C.C.t.t.p.t.p.C.A.e.D.C.A.6#e#e#e#e#e#e#e#e#d.5.s.s.r.J.r.r.m.s.r.I.r.e.d.s.n.r.r.I.s.r.w.s.r.J.6.b.u.u.b#e#e#e#e#e.C.C.A.C.C.p.t.#.C.A.C.z.A.B.C###e.9.Y.9#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e.N.9.N#d#e.U.C.A.t.o.A.C.C.t.o.C.C.C.A.C#e#e#e#e#e#e#e#e#c.J.r.J.V.r.r.r.r.J.q.E.r.m.d.e.s.r.I.r.s.r.I.r.I.t.s.d.d.N#e#e#e#e#e#e#e.6.C.A.B.t.t.C.C.o.t.p.G.A.C.A.U#e#e.N.9#c#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e.9.Y.8#e#..C.A.C.t.C.A.C.C.C.u.C.C.z.C.U#e#e#e#e#e#e#e#e.r.s.r.r.r.n.I.r.n.m.n.m.F.r.e.t.s.r.s.s.s.t.d.t.d.d.e.h.d.6#e#e#e#e#e#e#e#e.3.C.A.G.A.C.o.o.D.o.t.C.A.C.C#e#e.1.6.X#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N#e#e.U.C.A.C.D.A.C.z.A.C.t.C.A.C.R#e#e#e#e#e#e#e#e.W.r.r.I.s.I.n.r.r.s.r.r.n.c.t.d.e.d.e.d.d.e.d.e.d.e.e.d.e.d.r.5#e#e#e#e#e#e#e#e.2.A.A.C.D.t.C.A.C.A.t.A.C.A#e#e#e.N.N#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e.N.N#d#e#d.C.C.z.C.o.u.o.C.C.C.t.C.C.U#e#e#e#e#e#e#e.T.r.s.r.s.r.I.J.s.r.s.d.d.e.e.h.e.h.t.h.y.d.d.e.t.h.d.u.e.d.e.s.r.J.s.5#e#e#e#e#e#e#e.6.C.A.t.C.C.A.C.C.t.C.A.C.3#e#e.9#e.N#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e.N.O#e#e#e.A.C.C.A.C.C.t.u.C.p.o.C.Q#e#e#e#e#e#e#e.W.r.J.r.r.r.r.s.r.s.t.d.e.h.d.y.d.d.e.d.e.e.d.e.d.h.e.h.d.h.d.d.s.r.r.r.r#e#e#e#e#e#e#e#e.A.C.t.G.A.C.A.C.t.l.C.A.G#e#e#e#e.N#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e.6.Y.6#e#d#..A.C.o.C.C.A.C.D.t.u.C.C.6#e#e#e#e#e#e#e.I.r.r.s.r.r.J.w.s.s.d.h.h.t.h.e.u.d.e.y.h.y.e.g.y.d.d.d.u.d.e.t.w.s.r.I.n.8#e#e#e#e#e#e#e.C.A.G.o.C.A.B.A.t.C.A.B.C#.#e#e.Y.1.7#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e.N#d#d#e#e.U.C.C.u.C.C.C.C.A.o.D.C.A#e#e#e#e#e#e#e.8.s.r.I.r.s.w.r.s.s.d.e.e.h.e.d.e.e.h.g.e.d.d.h.e.d.h.u.h.d.h.t.s.r.w.r.r.r.J#e#e#e#e#e#e#e.U.A.C.t.C.C.A.C.p.C.A.C.A.U#e#e.N#e.N#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e.9.X.9#e#e.6.B.C.t.C.C.t.D.B.A.G.C.A.2#e#e#e#e#e#e.6.r.I.r.J.r.r.r.r.r.e.d.e.h.g.e.y.e.e.d.d.h.e.h.d.e.d.y.d.h.d.x.s.s.I.w.r.r.s.I.s.8#e#e#e#e#e#e.S.A.C.D.G.o.D.C.A.C.z.A.C.6#e.7.9.X.9#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e.X.9.N#e#e.3.A.C.e.t.G.t.C.C.C.D.A.C.3#e#e#e#e#d#a.J.r.r.s.v.s.s.s.I.r.d.e.h.t.h.e.g.u.d.y.e.h.d.e.e.d.e.d.e.d.e.s.r.s.w.r.I.r.J.r.r.J#e#e#e#e#e#d#a.A.B.C.A.C.A.C.l.G.p.C.A.3#e.9.N.9.X#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e.N#d.N#e#d.2.C.C.C.o.t.t.l.C.D.C.C.C#e#e#e#e#e#e.U.r.s.r.J.r.J.I.r.r.s.d.h.e.h.e.x.e.d.h.e.g.u.h.d.h.t.h.e.h.t.e.r.I.r.J.r.s.s.v.s.I.r.6#e#e#e#e#e#e.D.C.C.C.o.G.t.t.u.d.A.C.2#e#e.N#e.N#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#c.O#d.N#e#c.C.A.A.C.A.C.o.t.u.t.A.A.2#e#e#e#e#e#e.I.w.r.r.w.s.r.s.r.J.r.e.y.d.e.e.e.d.e.t.h.d.e.d.e.d.e.d.d.e.d.d.s.r.r.r.J.r.J.s.s.r.r.J#e#e#e#e#e#e.3.A.o.t.t.p.C.#.t.G.C.A.C#c#e.Y.9.N#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.a.1.X.9#e.3.A.B.t.A.C.C.C.A.C.A.A.C###e#e#e#e#e.J.n.r.r.s.v.J.r.r.M.s.s.e.g.e.h.e.d.h.t.h.h.u.d.e.e.t.e.h.e.d.t.r.r.s.s.I.I.s.J.r.s.v.s.r#e#e#e#e#e#e#e.P.A.A.C.A.t.G.C.A.C.A.C.3#e.9.X.6#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.6.9.N#e#e.2.C.A.t.A.C.G.C.C.z.C.B.2#c#e#e#e#e#e.r.I.r.J.M.s.s.r.s.s.r.s.e.y.d.h.d.d.e.e.d.e.d.h.d.d.h.d.e.e.t.s.r.s.v.J.s.r.s.v.J.J.r.s.M#e#e#e#e#e#e#e.S.A.C.C.C.p.A.C.z.A.C.A.T#e#d.N.9#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.N#e.N#e#d.2.A.C.H.C.A.p.A.A.C.C.C.S#e#e#e#e#e#e.s.r.r.r.s.s.I.s.s.I.w.s.g.e.d.e.e.d.h.d.d.u.h.d.e.e.e.g.e.e.g.d.s.I.s.s.v.r.I.s.r.s.v.s.s#b#e#e#e#e#e#e.4.z.C.A.t.C.C.D.o.F.A.C.R#e#e.O#d#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.O#e.N#e#e.C.C.A.t.x.d.u.G.C.C.A.A.6#e#e#e#e#e#e.r.r.J.r.I.r.w.r.s.r.s.s.e.d.h.y.e.y.d.e.h.d.e.t.e.d.d.e.h.e.d.s.w.s.v.J.s.w.r.r.J.I.s.I.w.W#e#e#e#e#e#e#a.C.C.t.t.t.t.t.p.C.A.C.C#e#e.N#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.N.b.0#e.6.A.C.A.C.A.C.A.A.C.C.C.C#e#d#e#e#e#e#e.r.I.s.w.J.s.r.r.r.r.r.r.d.h.u.e.d.e.t.h.h.t.h.e.h.h.d.e.d.g.h.d.s.r.s.I.s.s.r.r.I.J.s.I.r.J#e#e#e#e#e#e#c.C.C.A.C.C.A.A.C.C.C.A.C#e#e.1.a#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.N.9.Y#e.6.A.C.B.C.A.C.A.A.C.A.A.D#c#e#e#e#e#e.8.r.w.s.r.v.J.r.r.s.J.r.s.d.h.e.g.t.h.d.e.d.h.e.g.e.d.e.d.e.e.d.r.I.M.s.w.r.r.V.s.r.s.v.s.I.r#e#e#e#e#e#e#e.C.A.C.A.A.C.C.z.C.z.C.A#e#e.X.9#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.N.9.6#e.6.z.C.A.z.C.A.B.C.A.B.C.Q#e#e#e#e#e#e.6.r.J.r.V.r.s.r.J.s.r.s.M.d.e.d.e.e.e.h.x.h.d.t.e.e.e.t.h.d.t.s.r.s.s.I.s.r.s.r.J.r.s.r.r.r.I.b#e#e#e#e#e#e.A.C.C.A.C.A.C.A.A.C.A.C#e#e.9.7.b#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.X.Y.9#e.3.C.A.C.C.C.A.C.A.C.A.C.2#e#e#e#e#e#e.6.r.r.s.r.v.J.r.r.s.M.s.s.g.e.y.d.e.x.e.h.d.e.e.h.d.d.h.e.d.g.t.s.r.w.s.r.V.M.s.v.s.s.I.r.J.r.8#e#e#e#e#e#e.A.C.z.C.C.A.C.A.A.C.A.B#e#e.9.X.b#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.Y.X.9#e.U.A.C.A.B.A.C.A.A.C.C.A.2#e#e#e#e#e#e.5.s.s.r.s.v.J.r.s.r.V.r.s.t.d.h.u.d.d.e.h.d.e.h.e.d.d.u.h.e.d.e.s.s.s.r.s.w.J.w.r.V.m.s.v.J.s.5#e#e#e#e#e#e.C.A.C.C.C.A.C.C.C.B.A.C#e#e.a.1.9#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.0.Y.9#e.3.C.A.C.C.A.C.C.C.A.C.z.2#e#e#e#e#e#e.5.I.w.I.w.s.r.r.J.J.s.r.V.t.d.e.d.u.h.t.e.u.d.d.h.u.e.g.e.d.d.s.w.s.s.M.s.I.v.s.s.r.I.r.s.s.s#a#e#e#e#e#e#e.B.A.C.A.A.C.A.C.C.A.C.A#e#e.9.X.8#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.Y.X.9#e.5.A.C.z.A.C.C.C.C.A.C.A.R#e#e#e#e#e#e.6.s.s.r.s.r.J.r.s.s.r.w.s.s.h.d.h.d.e.h.g.d.h.u.g.e.e.y.d.h.e.h.d.t.r.s.s.w.s.J.r.I.s.r.J.r.r#b#e#e#e#e#e#e.C.A.B.A.C.o.C.A.A.C.A.C#e#e.a.1#c#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.N.9.6#e.4.z.C.C.C.A.t.D.z.C.C.A.G#e#e#e#e#e#e.6.r.J.w.r.s.r.r.V.w.s.s.s.c.d.u.h.d.e.d.e.h.e.h.e.y.g.e.h.e.h.u.h.e.s.s.s.s.w.s.r.s.r.r.r.s.r#e#e#e#e#e#e#e.C.A.C.A.C.u.o.C.A.C.B.A#e#e.9.X.b#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.N.9.X#e.6.C.A.B.t.e.h.e.o.A.C.A.C.X.X.N.L.y.u.t.d.d.e.g.e.d.d.h.h.d.e.d.d.e.g.u.e.d.h.d.g.e.d.d.t.t.e.d.e.d.e.g.e.d.e.d.e.e.g.u.g.d.e.d.h.d.u.u.t.u.X.L.X.C.A.B.A.d.e.h.p.B.A.C.A#e#e.0.a#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.N.9.Y#e#a.A.C.A.A.t.d.h.A.C.A.C.A#.#e#e#e#e#e#e.J.s.s.s.s.s.s.d.d.x.d.t.d.y.d.h.g.u.h.e.e.d.e.d.e.e.h.x.e.e.x.e.d.g.u.g.t.g.t.d.t.s.s.s.s.W#e#e#e#e#e#e#e.C.C.A.C.t.x.e.G.A.C.A.C#e#e.Y.9#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.N#d.N#e##.C.C.z.A.t.t.t.C.A.C.A.A.6#e#e#e#e#e#e.r.w.I.w.w.s.I.s.s.r.s.v.s.s.s.s.s.s.t.d.t.h.e.t.h.d.t.d.t.s.t.s.s.s.r.r.r.J.r.w.r.s.V.r.r.5#e#e#e#e#e#e#..C.A.C.A.t.D.#.t.C.A.B.D#e#e.N#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.N#d.N#e#e.D.C.A.C.G.A.C.C.A.B.A.z.U#e#e#e#e#e#e.I.r.s.s.J.r.r.r.r.V.s.J.J.r.w.r.s.r.r.I.r.y.d.h.e.s.s.v.s.r.w.r.w.m.r.s.J.w.r.J.s.s.r.s.r#e#e#e#e#e#e#e...A.B.A.C.C.C.A.C.C.A.C.P#e#e.N#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.6.9.N#d#e.S.C.B.C.A.C.C.C.A.C.A.A.C#.#e#e#e#e#e.U.r.r.s.s.s.r.r.J.w.I.s.s.r.w.s.r.I.s.I.I.e.e.d.e.s.s.I.s.I.r.r.s.s.r.r.J.w.r.s.J.V.r.r.r#e#e#e#e#e#e#e.G.B.C.A.C.A.C.A.C.A.C.A.U#e#d.Y.X#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e.b.O.0.7#e.3.C.A.z.C.A.C.C.A.B.A.A.C.6#e#e#e#e#e#a.r.J.r.I.r.V.r.w.r.s.w.s.I.s.I.J.r.r.w.v.e.x.e.y.I.r.r.r.s.s.J.v.I.r.s.s.J.s.v.s.s.r.J.r#e#e#e#e#e#e#..A.A.C.z.C.C.A.C.A.A.C.A.5#e.9.X.1#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e.N.7.0#e#..C.A.C.A.C.A.A.C.A.C.C.A.2#e#e#e#e#e#e.J.s.I.r.r.r.n.s.r.I.s.s.r.w.r.r.r.I.r.I.d.e.d.h.s.r.J.s.I.w.r.J.w.s.r.I.r.s.r.J.I.s.r.W#e#e#e#e#e#e.U.B.C.A.C.A.A.B.A.C.C.z.C###e.X.9.N#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e.N#d.O#e#d.C.C.C.z.C.C.B.C.A.C.A.C.C#e#e#e#e#e#e.6.r.w.J.s.r.r.r.I.s.r.r.I.r.I.r.s.n.r.r.d.y.e.d.V.r.w.r.s.r.s.w.J.r.r.w.w.I.w.r.s.r.I#c#e#e#e#e#e#e.R.C.C.C.A.C.C.C.A.C.A.C.D#e#e.N#e.N#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e.b.Y.X#e#e.4.C.C.A.C.A.A.C.z.C.C.A.C.2#e#e#e#e#e#e#c.s.J.w.r.s.r.J.v.s.V.r.I.w.w.s.r.r.r.t.h.d.h.r.w.r.s.r.J.s.v.V.r.r.s.s.I.r.J.w.J#e#e#e#e#e#e#e.2.C.C.C.A.C.C.C.A.C.A.A.C.4#e.9.X.Y.8#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e.N.9#e#e#..C.C.A.C.C.C.k.A.C.A.C.z.A#e#e#e#e#e#e#e.5.s.I.s.r.r.r.s.J.r.w.s.s.s.v.J.r.s.s.e.e.g.s.s.V.r.r.w.r.J.r.s.I.r.r.s.r.s.r.5#e#e#e#e#e#e#c.C.A.C.C.A.C.z.A.C.C.A.A.C#a#e.X.9.N#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e.N.9#e#e#d.2.A.B.A.C.C.A.C.A.A.C.C.A#c#e#e#e#e#e#e#e.w.r.w.J.r.J.v.s.J.r.s.v.I.s.s.r.w.s.h.t.e.v.s.r.s.s.r.J.v.I.s.r.r.r.J.v.J.W#e#e#e#e#e#e#e.2.C.A.C.C.C.A.C.B.A.C.A.C.2#e#e.O.b.N#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e.a.9.b#e#e.5.C.C.A.C.C.A.B.A.z.C.A.B.6#e#e#e#e#e#e#e.I.J.s.r.s.r.r.J.s.s.r.J.s.s.M.s.s.s.e.e.h.s.r.V.r.J.w.s.r.r.r.I.s.w.r.s.s#e#e#e#e#e#e#e#e.C.C.A.C.C.A.B.A.C.A.C.A.A.4#e#e.X.Y.9#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e.X.N#e#e#e.A.C.A.C.C.C.z.C.C.z.C.A.A.U#e#e#e#e#e#e#e.8.J.r.V.s.r.r.r.s.r.s.J.r.J.s.r.s.e.t.h.w.r.w.s.I.r.r.J.s.r.I.s.s.r.I#a#e#e#e#e#e#e#e.6.A.C.A.C.B.A.C.C.C.A.C.A.2#e#e#e.9.N#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e.b.Y.9#e#e.C.A.C.C.C.A.C.A.A.C.C.A.A.C###e#e#e#e#e#e#e.6.I.r.r.J.r.v.J.v.J.s.w.r.V.r.J.g.e.d.I.s.I.r.r.r.s.v.V.r.r.s.r.I###d#e#e#e#e#e#e#c.C.B.A.C.A.A.C.A.C.C.A.C.z.6#e#e.9.X.9#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e.9.N#e#e.2.A.B.A.A.B.A.C.i.C.A.C.C.C.C#e#e#e#e#e#e#e#e#b.I.r.r.r.r.r.s.r.r.J.r.s.r.r.e.d.u.r.r.r.s.s.V.s.I.r.s.I.r.J#c#e#e#e#e#e#e#e#e.2.A.C.A.C.B.C.A.B.A.z.C.A.C#e#e#e.N.N#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e.0.N.9#e.6.C.A.C.C.A.C.z.A.C.A.C.C.A.C.S#e#e#e#e#e#e#e#e.K.r.J.r.I.s.r.I.r.r.r.r.r.E.d.h.d.I.s.J.v.r.s.r.w.I.r.r.n#e#e#e#e#e#e#e#e#e.3.C.C.C.A.C.A.C.A.C.C.C.C.A.C#e#e.9.X.X#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e.7.Y.N#e#e.3.C.A.A.C.A.C.B.A.C.A.A.C.A.C.6#e#e#e#e#e#e#e#e#e#e.Z.r.r.s.V.s.w.r.s.r.J.g.e.d.r.J.r.V.r.s.r.r.J.5#c#e#e#e#e#e#e#e#e#e.C.A.A.C.t.t.A.C.C.A.k.z.A.C.C.6#e.9.N.7#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N.9.N#e#e.2.C.z.C.A.B.A.C.A.C.t.o.C.A.C.6#e#e#e#e#e#e#e#e#e#e.U.I.r.r.r.s.I.w.w.r.t.e.t.r.w.s.r.r.I.r.I#a#e#e#e#e#e#e#e#e#e#e#a.A.C.B.A.A.t.e.C.z.C.A.C.A.C.R#c#e.X.9.N#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e.X.9.N#e#e.6.A.A.C.C.A.C.o.t.e.t.t.A.C.A.P.6#e#e#e#e#e#e#e#e#e#e#c.5.J.s.r.w.s.s.J.f.e.s.r.I.r.I.I.J.6#e#e#e#e#e#e#e#e#e#e#e#b.D.C.A.C.A.z.C.G.e.C.A.C.A.z.C#b#e.9.N.7.X#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N.7#e#e#e.U.C.A.C.o.e.e.G.C.u.C.C.A.A.C.A.6#e#e#e#e#e#e#e#e#e#e#e#e.5.W.F.I.q.r.s.e.s.r.J.J.W#d#e#e#e#e#e#e#e#e#e#e#e#e##.C.z.C.t.o.o.D.C.A.o.l.C.B.A.A.U#e#e.N.9.N#c#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.X.N#e#e#e.C.C.A.C.C.A.t.H.D.A.C.t.G.C.B.A.2#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.6.e.X#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.A.B.A.C.A.G.t.G.A.C.A.C.o.C.A.C.4#e#e.9.9.N#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.9.N#e#e.2.C.A.B.C.A.C.d.C.C.t.p.t.o.A.C.C.C.6#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.7.d.9#e#e#e#e#e#e#e#e#e#e#e#e#e#e.6.R.C.A.#.t.g.t.p.u.C.A.C.C.A.C.C.A#e#e#e.X.N#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.Y.N.9#e#e.2.C.A.z.C.C.t.A.o.t.C.C.u.C.C.C.A.C.2#e#e#e#e#e#e#e#e#e#e#e#e#e#e.9.d.a#e#e#e#e#e#e#e#e#e#e#e#e#c.3.C.C.C.o.t.G.A.D.t.t.p.C.C.A.C.A.z.2#e#e.9.N.X#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.X.9.N.9#e#..C.C.C.A.G.t.G.u.C.A.C.D.t.A.A.C.A.C.3#e#d#e#e#e#e#e#e#e#e#e#e#e#e.d#e#e#e#e#e#e#e#e#e#e#e#e#e.D.A.A.C.C.u.C.A.A.C.C.e.t.p.C.C.A.C.C###e.b.N.9#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.N.1#e#e#e.3.A.C.C.D.G.A.C.A.C.C.u.#.t.A.C.C.C.A.C.C.6#e#e#e#e#e#e#e#e#e#e.t#e#e#e#e#e#e#e#e#e.S.C.C.A.A.C.o.G.t.G.C.A.C.A.B.o.A.A.C.A.C.3#e#e.X.1.X.7#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.X.Y.Y#e#e#d.C.C.A.#.l.C.C.A.A.p.t.t.o.C.A.B.C.z.C.A.A.C.S.5#c#e#e#e#e#e#e.u#e#e#e#e#e##.6.T.R.B.A.C.A.o.t.K.e.p.o.A.C.C.A.C.p.C.C.z.C.3#e#e#e.N.Y.X#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.X.N.9#e#e.2.C.A.C.u.o.C.C.o.t.p.t.G.C.A.C.C.C.A.C.C.C.A.A.R.2.U.4#..b#a.L#a.6.3.3.2.C.A.A.C.A.C.C.G.e.G.A.o.D.t.C.C.C.A.C.y.A.C.A.C#e#e#e.9.9.N#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.9.N.7#e#e.U.C.A.C.t.u.t.t.G.t.D.l.C.A.C.p.t.G.C.C.z.C.C.B.C.A.C.C.A.A.G.A.C.A.C.A.A.B.C.A.C.C.A.t.t.o.C.C.D.t.t.D.C.G.t.o.C.z.C.3#e#e.9.N.N#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.N.9.N#e#e#e.3.C.A.C.A.C.u.C.A.C.A.G.t.t.G.t.p.e.C.C.A.C.C.C.A.C.A.B.A.C.C.C.D.C.G.C.C.A.t.t.t.C.A.t.p.C.t.p.C.C.D.C.A.C.C.4#e#d.a.N.9.N#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.N.7.9#e#e#e.C.C.A.C.t.o.C.C.C.t.t.D.t.D.t.#.t.G.A.B.e.G.t.C.t.t.G.p.t.t.t.e.t.t.t.o.A.t.A.t.p.C.C.t.C.C.t.D.A.A.C.A.B.6#e#e#e.N.7.N.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.N.N.Y#e#e#..2.A.B.C.C.A.C.t.p.C.C.G.o.p.G.l.t.A.C.t.o.t.p.C.p.t.o.G.C.D.t.A.A.D.t.C.t.C.A.t.C.C.p.p.A.G.o.C.C.A.C.2#e#e#e.7.1.N.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.Y.0.Y#e#d#d.U.C.C.A.C.C.o.C.A.p.A.u.F.p.C.t.C.C.p.G.p.t.C.C.p.C.C.C.C.t.C.C.C.t.D.t.D.t.t.p.C.D.t.C.C.A.C.A.C.3#c#e#e.X.N.N#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.X.O.9.9#e#e#e.S.C.C.A.A.C.o.p.t.G.l.t.A.G.t.C.C.t.D.C.t.t.C.C.A.C.A.p.J.d.u.D.C.t.C.A.C.C.p.#.C.C.C.z.C#e#e#e#e.N.1.X.X#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.N.N.X#e#e#e#..2.C.C.A.C.C.p.C.G.t.C.A.t.H.C.e.C.A.C.G.e.C.C.G.A.G.t.p.t.C.A.d.C.A.C.C.z.C.A.z.C.S#.#e#e#d.X.7.N.9#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c.1.Y.N.9#e#d#e.6.A.C.C.A.C.A.p.#.C.A.o.t.C.u.C.G.A.C.t.D.A.D.C.C.e.C.p.t.C.t.A.C.A.A.C.A.B.2.6#e#d#e.9.N.Y.N#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.X.N.9.N.9#e#e#e.6.2.A.C.C.A.C.C.A.C.C.h.C.u.F.e.A.C.u.C.C.o.A.C.u.C.C.o.t.D.C.z.C.C.A.C.2#e#e#e#e.N.N.9.N#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.X.1.N.X#e#e#e#e.6.2.C.A.A.C.A.C.C.A.C.A.l.C.C.A.C.C.A.C.A.C.A.C.A.A.C.C.2#e#e#e#e#e.Y.N.Y.N.9#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.7.N.Y.1.Y.9#e#e#e#e#e.5.Q.C.A.C.C.z.C.A.A.C.A.C.A.C.z.C.A.A.B.A.C.U.6###e#e#e#e.9.N.1.X.N#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.6.N.1.X.N.Y#e#e#e#e#e#c.6.3.2.R.C.C.A.B.A.C.z.A.C.C.C.S.3.6###e#e#e#e.b.9.N.X.Y.N.7#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N.N.9.X.O.8#e#e#e#e#e#e#d#c#a###..6.6.3#b#.#c#e#e#e#e#e#e#e#e#e.9.O.X.9.O.8#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.N.N.X.1.X.N.O.N.0.9#e#e#e#e#e#e#e#e#e#c.9.Y.N.N.N.9.Y.X.O.9#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.9.6.N.Y.X.1.7.Y.N.N.N.N.O.N.N.N.N.N.X.8.9.1.Y.N.8.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.9.6.N.N.O.N.0.Y.0.7.X.N.O.N.O.N.7.8.b#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.b.b.a.9.b#c#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e",
"#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e"
};




/* XPM */
static char *nws_logo[] = {
/* width height num_colors chars_per_pixel */
"    93    94      168            2",
/* colors */
".. c #000000",
".# c #808000",
".a c #000080",
".b c #008080",
".c c #c0c0c0",
".d c #c0dcc0",
".e c #111111",
".f c #222222",
".g c #555555",
".h c #424242",
".i c #ff5050",
".j c #ccecff",
".k c #efd6c6",
".l c #e7e7d6",
".m c #ada990",
".n c #330000",
".o c #990000",
".p c #cc0000",
".q c #003300",
".r c #333300",
".s c #663300",
".t c #993300",
".u c #cc3300",
".v c #336600",
".w c #666600",
".x c #996600",
".y c #669900",
".z c #999900",
".A c #cc9900",
".B c #ff9900",
".C c #66cc00",
".D c #99cc00",
".E c #cccc00",
".F c #ffcc00",
".G c #ccff00",
".H c #000033",
".I c #330033",
".J c #990033",
".K c #cc0033",
".L c #003333",
".M c #333333",
".N c #663333",
".O c #993333",
".P c #cc3333",
".Q c #ff3333",
".R c #006633",
".S c #336633",
".T c #666633",
".U c #996633",
".V c #cc6633",
".W c #009933",
".X c #339933",
".Y c #669933",
".Z c #999933",
".0 c #cc9933",
".1 c #ff9933",
".2 c #33cc33",
".3 c #66cc33",
".4 c #99cc33",
".5 c #cccc33",
".6 c #ffcc33",
".7 c #ccff33",
".8 c #ffff33",
".9 c #000066",
"#. c #330066",
"## c #660066",
"#a c #003366",
"#b c #333366",
"#c c #663366",
"#d c #cc3366",
"#e c #ff3366",
"#f c #006666",
"#g c #336666",
"#h c #666666",
"#i c #996666",
"#j c #cc6666",
"#k c #009966",
"#l c #339966",
"#m c #669966",
"#n c #999966",
"#o c #cc9966",
"#p c #ff9966",
"#q c #33cc66",
"#r c #99cc66",
"#s c #cccc66",
"#t c #ffcc66",
"#u c #ccff66",
"#v c #009999",
"#w c #000099",
"#x c #333399",
"#y c #660099",
"#z c #006699",
"#A c #336699",
"#B c #663399",
"#C c #996699",
"#D c #cc6699",
"#E c #339999",
"#F c #669999",
"#G c #999999",
"#H c #cc9999",
"#I c #ff9999",
"#J c #66cc66",
"#K c #99cc99",
"#L c #cccc99",
"#M c #ffcc99",
"#N c #66cc99",
"#O c #ccff99",
"#P c #ffff99",
"#Q c #0000cc",
"#R c #330099",
"#S c #003399",
"#T c #3333cc",
"#U c #6633cc",
"#V c #0066cc",
"#W c #3366cc",
"#X c #666699",
"#Y c #9966cc",
"#Z c #ff6699",
"#0 c #0099cc",
"#1 c #3399cc",
"#2 c #6699cc",
"#3 c #9999cc",
"#4 c #cc99cc",
"#5 c #ff99cc",
"#6 c #00cccc",
"#7 c #33cccc",
"#8 c #66cccc",
"#9 c #99cccc",
"a. c #cccccc",
"a# c #ffcccc",
"aa c #99ffcc",
"ab c #ccffcc",
"ac c #ffffcc",
"ad c #3300cc",
"ae c #0033cc",
"af c #3333ff",
"ag c #6633ff",
"ah c #3366ff",
"ai c #6666cc",
"aj c #9966ff",
"ak c #0099ff",
"al c #3399ff",
"am c #6699ff",
"an c #9999ff",
"ao c #cc99ff",
"ap c #00ccff",
"aq c #33ccff",
"ar c #66ccff",
"as c #99ccff",
"at c #ccccff",
"au c #ffccff",
"av c #66ffcc",
"aw c #99ffff",
"ax c #ccffff",
"ay c #ff6666",
"az c #ffff66",
"aA c #6666ff",
"aB c #66ffff",
"aC c #777777",
"aD c #868686",
"aE c #b2b2b2",
"aF c #dddddd",
"aG c #f1f1f1",
"aH c #fffbf0",
"aI c #ff0000",
"aJ c #ffff00",
"aK c #0000ff",
"aL c #ffffff",
/* pixels */
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#HaLaLaLaLa#.u#jaLaLaL.p.p.p.K.p.PaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#I#j.p.p.p#jaLaLaLaL.P#j.p#jaLaLaLaL#D.PaLa#aLaLaL.p#HaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.u.P.P#Ha#aLaLaLaLac.P#5.p.PaLaLaLaL.P.PaLaLaLaL#4.p#IaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#j.paLaLa#.oa#aLaL#5aLaLaL#j.oaL#j.u.kaLaLaL.P#jaLaLaLaL.u#jaLaLaG.P.PaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.P.paLaLaL.P.o.K.u.P.kaLaL.K.u.P.p.P.paLaLaL.Pa#aLaLaLaL.u#ja.aL#j.paGaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#.o.paL.k.P#HaLaLa#.oaLaLaLaLaLaL.u#jaLaLaL.Pa#aLaL.PaLaLaLaL#j.K#j.P.p.P.oaLaLaL.V.uaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#.u.K#HaL.P.PaLaLaG.uaLaLaLau#Ma#.pa.aLaLaL.o#jaLaL.paLaLaLaG.p#jaLaL.P.p.PaLaL#H.p.P.Pa#aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#aLaL.p#j.p#jac.uaLaLaL.p.P.p.u.p.PabaLaHaLaLaLaLaLaLaLa#aLaLaL.P.paLaLaL#j.Pa#aLaL.p.PaL.V.p#jaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#.K.uaL.p.uaL.p.p.Pa#aLaL.P#HaGaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaHaLaLaL.pa#aLaL.o.u.pa#aLaL.PaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.u.K#I#j.KaL#H.P.p#jaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.uaLaL.l.p#H.P.paLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#.p#M.P#IaLaL.PaGaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.u#jaLaL#H.p#HaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaG.u.K.paLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa..p#jaLaLaLaLaLaLa..u.PaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.P.u.uaHaLaLaLaLaLaLaLaLaLaLaLaL#9at#2#A#W#2#2ata.aLaLaLaLaLaLaLaLaLaLaLaLaL#j.u#daLaLaLaLay.u.O.p.VaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#9#S#S#W#8#2awar#Aawasam#2#W#S#SataLaLaLaLaLaLaLaLaLaLa#.V#jaLaL.P.p.PaLa..p#HaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLat#S#zasawawawawawaw#8#Aawawawawawawaw#8#S#SauaLaLaLaLaLaLaLaLaLaL#H.p.P#H.pa#aLa#.PaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLat#Samawawawawawawawaw#8aeawawawawawawawawaw#2#SaLaLaLaLaLaLaLaLaLaL.u.K#IaL.V.PaL#D.paLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#2aiaiai#2#2#W#S#Sawawawawawawawawawawar#Aawawawawawawawawawaw#8#1#Sa.aLaLaLaLaLaLaLaLacaLaL.P.V.o.pa#aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLau#2aLaLaLaLaLaL#Wawawawawawawawawawar#Vawawawawawawawawaw#Vawawaw#2#2aLaLaLaLaLaLaLaLaL#H.Pa#aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaL.P#HaLaLaLaLaLa#a#aLaLaLaLaLaLaL#zaiaLaLaLaLaL#8awawawawawawawawar#xawawawawawawawaw#Aamawawawawas#SaLaLaLaLaLaLaLaL.P.paLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaL.p.ua#aLaLaLaL.P.paLaLaLaLaLaLaL#S#AataLaLaLaL#Aarawawawawawawaw#8#Wawawawawawawawaw#Wawawawawawawar#xaLaLaLaLaLaLaL#d.uaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaL#j.p.PaLaLa#.Pa.aLaLaLaLaLaL#Sawawaw#AaLaLaLaLatawawawawawawaw#9#Sawawawawawawaw#2awawawawawawawawaw#AaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.P.p.P.paLaLaLaLaLaLax#Sawawawawaw#8#xaLaLaL#3#8#2#W#1#2aw#8#Aawawawawawawaw#Wawawawawawawawawaw#2#3aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.l.u.K.oaLaLaLaLaLaL#A#xawawawawawawaw#AaLaLaL#S#S#S#S#S#zar#Saw#8#1#2#1#8awaaawawawawawawawawawaw#S#9aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#aLaLaLaLaLaL#3arawawawawawawawaw#9#w#AaLaL#X#S#S#S#S#S#S#S#S#S#S#S#S#S#S#Aawawawawawawawawawaw#WaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaFa#a##I#I#HaLaLaLaLaLaL#Sawawawawawawawawaw#S#S#S#SataL#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#Sawawawawawawawawaw#AaLaLaLaLaLaLaLaLaLaLaLaLaL#H#IaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaL#j.P.P.u.K.p.u.p#jaLaLaLaLaLaL#S#1awawawawawawaw#2#S#S#S#SaGaLa.#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#8awawawawaw#A#S#SaLaLaLaLaLaLaLaLaLa#a#aL.p.P.paLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaL.p.P#Ha#a..pa.aLaLaLaLaLaLaL#Sawawar#Aawawawaw#2#S#Saia.aLaLaL#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#Aawaw#W#1awawaw#3aLaLaLaLaLaLaLa#.P.uaG.uaL#o.PaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLa#.o#HaL.paLaLaLaLaLaLaL#S#1awawawaw#2#Saw#2#S#S#SaLaLaLaLaLax#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#W#Sawawawawaw#S#3aLaLaLaLaLaL.P#HaLa..uaLaL.uaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaL.P.p.P.PaLaLaLaLaLaLaL#Sawawawawawawaw#S#S#S#S#S#WaLaLaLaLaL#A#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#2awawawawaw#A#WaLaLaLaLaLaL.P#5aLaG.KaLau.KaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaL#I.o.KaLaLaLaLaLaLaL#2ar#S#S#S#S#S#S#S#S#S#S#S#S#SaiaLaLaLaHat#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#Saw#9awawawaw#SaLaLaLaLaLaL#I.pa##I.paL#d#jaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaL.p#jaLaLaLaLaL#X#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#XaLaLaLat#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#Sawaw#WataLaLaLaLaLaL.P.u.ta#aLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaGaLaLaLaLaLaLaLaLaLaLaLau#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaxaLaL#3#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaL.K.P.P#j#I#H#LaLaLaLaLaL#X#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#x#3aLaL#2#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SataLaLaLaLaLaLaGaca#a##jaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaHa.#D#I#d.u.K.KaLaLaLaLai#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaLaL#W#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaLaLaL#j.p.p.K.u.K.P.PaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaL.k.u.u.PaLaLaLaLaL#x#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaL#z#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaLaLaL#j.uaLaL.PauaL.pa#aLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaL#j.u.p#HaLaLaLaLaLaL#2#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#9aL#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaLaLaL#I.paLaL.pa.aL.Ka.aLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaL#H.p.p#jaLaLaLaLaLaLaLaLaL#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#WaLaLax#3ai#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaLaLaL#I.KaLaL.K#HaL.p#HaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaL.P.p.p.u.p.p.u.taLaLaLaLaL#A#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaiaLaLaLaL#2#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SataLaLaLau.uaLaL#j#IaL.u#IaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLa#a.#H#H#p#jaLaLaLaL#W#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SataLaLaLaL#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#4aLaLaLaLa#.PaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#xaxaLaLaL#A#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#3aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLa##j.p.u.KaLaLaLaL#A#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#AaLaLaL#A#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaHaLaLaLaLaL#j.p.p.V#Ha#aLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaL.u.K.J.K.u.PaLaLaL#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#3aLaLax#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaLaLaLaLaLaL#o.p.t.u.p.P.P#jaHaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaL.P.Pa#aLaLaL.Pa#aLaL#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#Sa.aLa.#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#Sai#AaLaLaLaLaLaLaLaLaL#j#H#M#j.PaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaL.uaLaLaLaLaL#H.VaLaLai#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaLaL#S#S#S#S#S#S#S#S#S#S#3aLaLaLaL#2aLaLaLaLaLaLaLaLaL#5.uaLaL#j#IaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaL.uaHaLaLaLaL.P#jaLaLaL#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#AaL#S#S#S#S#S#S#S#S#S#xaLaLaLat#SaLaLaLaLaLaLaL.K.u.u.oaLaL.Ka#aLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaL.K#jaLaLaLaL.P.kaLaLaLa.#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#Sa.#2#S#S#S#S#S#S#S#S#WaLaLaL#3#SaLaLaLaLaLaLaL.p.P#I.P#d#H.uaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaL.p.u.u.P.p#jaHaLaLaLaLaLaL#SaiaLaLaLaL#A#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#9aLaLaLaL#S#S#S#S#S#S#SaLaLaLaL#S#3aLaLaLaLaLaLa#aLaLaLaL.P.p#HaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLa.aLaLaLaLa#aLaLaLaLaLaL#SaLaLaLaLaLaLai#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#SaLaLaLaLaL#S#S#Sai#S#S#xaLaLaLaLat#9aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.P.VaLaLaLaLaLaL#3axaLaLaLaLaLaL#3#x#S#S#Sai#3#S#S#S#S#S#S#S#S#S#S#S#S#WaLaLaLaLaL#S#xaLaGaxaLaLaLaLaL#WaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLac.P.o.K.Ka#aLaLaLaLaLaLaL#SaLaLaLaLaLaLaLaLaHaLaLaLaL#9#S#S#S#S#S#S#S#S#S#S#S#S#S#AaLaLaLataLaLaLaLaLaLaLaLaL#xaLaLaLaLaLaLaL#5.p.P#j#jaya#a#aLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaL#H.p.u.P#HaLaLaLaLaLaLaLaLaLaL#3#3aLaLaLaLaLaLaLaLaLaLaLaLaLaLat#x#S#S#S#S#S#S#S#SaiaLaLaiataLaLa.#2aLaLaLaLaLax#xaLaLaLaLaLaLaLaL.P.p#j#j.P.o.K.paLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaL.u#jaLaLaLaLaLaLaLaLaLaLaLaLaL#SataLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#2#Aai#S#x#3ataLaLaLaL#A#2aLaL#3aLaLaLaLaL#A#SaLaLaLaLaLaLaLaLaG.P#HaLaLa##H#IaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.PaLaLaLaLaLaLat#SaxaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaiaLaL#3aLaLaL#3#3aLaLaLaLaLaLaLaLaLaLaL.K.uaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaL#IaGaLaLa#.p.P.PaLaLaLaLaLaLaLaL#Sa.aLaLaLaLaLaLaLaLaL#9arasaLaLaLaLaLaLaLaLaLasaw#9aLaLaLaLaL#2aL#2#9#9#AaLaLaLaLaLaLaLaL#jaLaLaLaH#j.KaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaL#j#jaLaL.P.P.paLaLaLaLaLaLaLaLaL#2#2arasaLaLaLaLaLaH#9awawawas#9aLaLaLaLau#9arawawaw#9aLaLaLaLaL#AaLai#WaLaLaLaLaLaLaLaLaL.p#IaLaLaLaL.u.PaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaL.o.P.p.PaLaLaLaL.paLaLaLaLaLaLaL#3#Sawawawawawawawawawawawawawawawawawawawawawawawawawawawawawaw#1#x#2aLaLaLaLaLaLaLaLaL#M.K.p#IaLaLaL.uaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaL#H.pa#aLaLaLaL.K.uaLaLaLaLaLaLaLaLaL#W#8awawawawawawawawawawawawawawawawawawawawawawawawawawaw#2#3aLaG#AaLaLaLaLaLaLaLaLaLaLa#.u.p#HaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLa..paLaLaLa..P.paLaLaLaLaLaLaLaLaLaL#3#z#2awawawawawawawawawawawawawawawawawawawawawawaw#1#SataLaLaLaL#2aLaLaLaL.P.P.p.paLaLaL.P.P#HaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaL.uaLaLaL.P.t.paLaLaLaLaLaLaLaLaLaLaLai#Sarawawawawawawawawawawawawawawawawawawawawaw#2#Aa.aLaLaLaLaLaLaLaLaL.P.K#o.P.P#IaLaLaL#jaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.uaLa#.pau#Ha#aLaLaLaLaLaLaLaLaL#9#S#Aawawawawawawawawawawawawawawawaw#8#S#SaLaLaLaLaLaLaLaLaLaLaL.P.paLaLaLa#.u.KaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#.P#ja##j.p.u.K#oaLaLaLaLaLaLaLaLaLaLaLaLa.#S#S#1#8arawawawawawar#2#W#S#xaxaLaLaLaLaLaLaLaLaLaLaLaLaL.P.uaLaLaLaL.P.paLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#j.P#j.p.p.u#D.kaL#j#jaLaLaLaLaLaLaLaLaLaLaLaLa.#A#S#S#S#S#W#S#S#S#S#AataLaLaLaLaLaLaLaLaLaLaLaLaLaGaL#j.KaLaLaLaL.V.KaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#.P.Pa#aLaLaLaLaG.P.paLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#o.u.paLaLaLaLaLaLaL.K.uaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.p.t.KaLaLaGaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.p.P#L.K#jaLaLaL.P.K.p#jaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#.u.P.paLaL.V#jaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#.P.PaGaL#j.paLaLaL#o.P#HaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#j.Pa..P.uaL.u.paLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#HaLaLa#.P.O#jaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#.o.PaL.u.K#o.P#HaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.P.P#jaL.t.PaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.k.Pa#aL.K.u.K#jaLaLaLaLaLaLaLataLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLataLaLaLaLaLaLaLaL.p#HaLaL.K.paLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.o.P.OaLaLaLaLaLaLaLaL#SaLaLaLaLaLaLaLaLaL.iaLaLaLaLaLaLaL#SataLaLaLaLaLaLaLaLaLaL.u.Pa#aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL.P.paLaLaLaLaLaLaLat#S#S#SaHaLaLaHaL#M#M#eaIa#a##IaLaLaL#A#S#SataLaLaLaLaLaLaL.u.oa#aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#S#A#2aLaLaLaLaLa#aIaIaIaIa#aLaLaLaL#2#A#SaLaLaLaLaLaLaLaL.laLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL#3aL#AaLaLaLaLaLaL.QaIaI.iaLaLaLaLaL#XaLa.aHaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaIaI.Q.QaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLa#aLaL#IaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL",
"aLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaLaL"
};




/* XPM */
static char *noblis_jpg_logo[] = {
"117 41 338 2",
"  	c #FFFFFF",
". 	c #FFFFFD",
"+ 	c #FEFEFE",
"@ 	c #FFFEFC",
"# 	c #FEFFFF",
"$ 	c #FDFFFC",
"% 	c #FFFEFF",
"& 	c #FDFEFF",
"* 	c #FFFFFB",
"= 	c #FEFFFD",
"- 	c #FDFFFE",
"; 	c #F6F6DE",
"> 	c #DCE191",
", 	c #FCFFFF",
"' 	c #FCFFFD",
") 	c #FFFEFD",
"! 	c #FEFEFF",
"~ 	c #FDF9EE",
"{ 	c #D0D465",
"] 	c #D0D360",
"^ 	c #FFFDFE",
"/ 	c #DCE1E5",
"( 	c #CED7DC",
"_ 	c #D1D8DE",
": 	c #CFD8DF",
"< 	c #D1D9DC",
"[ 	c #E6EBEE",
"} 	c #D0D8DB",
"| 	c #D3D8DC",
"1 	c #CFD6DC",
"2 	c #CFD8DD",
"3 	c #F3F4F6",
"4 	c #FEFEFC",
"5 	c #FAFAF2",
"6 	c #DBDB81",
"7 	c #BBBF13",
"8 	c #FFFEFB",
"9 	c #748A98",
"0 	c #45637B",
"a 	c #44627A",
"b 	c #46647C",
"c 	c #476178",
"d 	c #A1B1BE",
"e 	c #74899A",
"f 	c #436277",
"g 	c #45657C",
"h 	c #47637B",
"i 	c #E1E6A4",
"j 	c #BCC325",
"k 	c #B5B90A",
"l 	c #CFD460",
"m 	c #74899C",
"n 	c #476379",
"o 	c #446378",
"p 	c #456479",
"q 	c #9FB1BD",
"r 	c #72899B",
"s 	c #45637D",
"t 	c #446479",
"u 	c #D0D9DE",
"v 	c #ECEEBF",
"w 	c #C9CC41",
"x 	c #B5BB03",
"y 	c #B6BA03",
"z 	c #CFD261",
"A 	c #F4F6DE",
"B 	c #F3F3D1",
"C 	c #738A9A",
"D 	c #A3B1BC",
"E 	c #758A9D",
"F 	c #466278",
"G 	c #FCFAEE",
"H 	c #CCD151",
"I 	c #B5BA05",
"J 	c #B3BB05",
"K 	c #B5B805",
"L 	c #D1D365",
"M 	c #FBF8EF",
"N 	c #D6D972",
"O 	c #D0D362",
"P 	c #738A9C",
"Q 	c #A0B1BB",
"R 	c #44647D",
"S 	c #FDFFFA",
"T 	c #FFFDFD",
"U 	c #C0C630",
"V 	c #B3BA08",
"W 	c #B5BA06",
"X 	c #CCD055",
"Y 	c #D9DC81",
"Z 	c #B7BD11",
"` 	c #D1D463",
" .	c #466277",
"..	c #44647B",
"+.	c #DDE093",
"@.	c #B6B906",
"#.	c #B6BA05",
"$.	c #B9BC15",
"%.	c #D0D55F",
"&.	c #FFFDFF",
"*.	c #B3BB06",
"=.	c #F0F1CF",
"-.	c #D2D260",
";.	c #FAFAEE",
">.	c #758C9C",
",.	c #A2B0BB",
"'.	c #D9DC85",
").	c #B9BA07",
"!.	c #BABD14",
"~.	c #C7CB42",
"{.	c #B6BB07",
"].	c #DDE091",
"^.	c #43637A",
"/.	c #436179",
"(.	c #A1B2BC",
"_.	c #D0DADC",
":.	c #EEEDBF",
"<.	c #B2BA02",
"[.	c #B7BB06",
"}.	c #B5B807",
"|.	c #748B9D",
"1.	c #46627A",
"2.	c #CED9DB",
"3.	c #E4E5A3",
"4.	c #B7B900",
"5.	c #CDD8DA",
"6.	c #F2F2D0",
"7.	c #D9DC83",
"8.	c #ECEDC1",
"9.	c #FFFEFA",
"0.	c #FFFDFC",
"a.	c #E5EAEE",
"b.	c #C5D0D6",
"c.	c #8093A2",
"d.	c #738899",
"e.	c #718B9C",
"f.	c #486376",
"g.	c #5D768A",
"h.	c #738997",
"i.	c #8B9DAB",
"j.	c #BBC4CB",
"k.	c #F1F5F8",
"l.	c #E7EBEE",
"m.	c #ACBAC5",
"n.	c #8092A0",
"o.	c #678094",
"p.	c #70899D",
"q.	c #7F94A5",
"r.	c #AFB9C3",
"s.	c #E7ECF0",
"t.	c #9FB2C0",
"u.	c #E6EBEF",
"v.	c #B0B9C2",
"w.	c #97A7B4",
"x.	c #758A9B",
"y.	c #718A9E",
"z.	c #8193A1",
"A.	c #DDE2E6",
"B.	c #CFD9DB",
"C.	c #FEFFFB",
"D.	c #A1B2BA",
"E.	c #A3B1BA",
"F.	c #A3AFBD",
"G.	c #9EB3B8",
"H.	c #BBC3CE",
"I.	c #C4CDD4",
"J.	c #8A9CAA",
"K.	c #678295",
"L.	c #476378",
"M.	c #516C81",
"N.	c #96A7B1",
"O.	c #EAEBEF",
"P.	c #98A6B1",
"Q.	c #5C778A",
"R.	c #486378",
"S.	c #42647D",
"T.	c #E7ECF2",
"U.	c #42647F",
"V.	c #556A7B",
"W.	c #678192",
"X.	c #C3CDD6",
"Y.	c #D0D9E0",
"Z.	c #46617C",
"`.	c #5C7589",
" +	c #476476",
".+	c #41637E",
"++	c #607586",
"@+	c #C4CED7",
"#+	c #43637C",
"$+	c #4F6B80",
"%+	c #C4CFD5",
"&+	c #BAC4CD",
"*+	c #4E6C84",
"=+	c #DAE1E7",
"-+	c #D0D7DD",
";+	c #B9C3CC",
">+	c #48647A",
",+	c #526C7D",
"'+	c #8B9DA9",
")+	c #B8C5CE",
"!+	c #F2F6F7",
"~+	c #879CAD",
"{+	c #41637C",
"]+	c #B8C5CD",
"^+	c #7F92A0",
"/+	c #C5CED5",
"(+	c #F4F6F5",
"_+	c #C2CFD7",
":+	c #516D83",
"<+	c #5D7788",
"[+	c #C6CDD3",
"}+	c #F5F4F2",
"|+	c #748B9B",
"1+	c #44627C",
"2+	c #5B778D",
"3+	c #AFBAC0",
"4+	c #B7C3CF",
"5+	c #8093A4",
"6+	c #A2B2BF",
"7+	c #FBFFFF",
"8+	c #DDE1E4",
"9+	c #BAC3CA",
"0+	c #AABAC7",
"a+	c #506C81",
"b+	c #768B9C",
"c+	c #A0B2C0",
"d+	c #4F6B81",
"e+	c #5E7489",
"f+	c #48647C",
"g+	c #8C9DA7",
"h+	c #E5EAED",
"i+	c #BBC5CF",
"j+	c #44637F",
"k+	c #DCE1E7",
"l+	c #A2B0B9",
"m+	c #95A7B5",
"n+	c #728999",
"o+	c #C4CDD6",
"p+	c #5B7689",
"q+	c #F6F4F5",
"r+	c #A0B0BD",
"s+	c #ADBAC3",
"t+	c #DEDFE3",
"u+	c #486479",
"v+	c #F1F6F9",
"w+	c #A4B1BA",
"x+	c #A3B0B9",
"y+	c #45657E",
"z+	c #46657A",
"A+	c #C3CED4",
"B+	c #899CAA",
"C+	c #A2B0BD",
"D+	c #97A9B7",
"E+	c #94A7B6",
"F+	c #7E93A4",
"G+	c #AFB9C2",
"H+	c #F0F5F9",
"I+	c #516B82",
"J+	c #AEBBC3",
"K+	c #96A6B5",
"L+	c #728C9D",
"M+	c #5A768C",
"N+	c #D0D7DF",
"O+	c #BBC4CD",
"P+	c #8093A1",
"Q+	c #8A9DAC",
"R+	c #718B9A",
"S+	c #466077",
"T+	c #5C798B",
"U+	c #506C82",
"V+	c #708A9B",
"W+	c #F3F5F4",
"X+	c #5C778C",
"Y+	c #F2F6F9",
"Z+	c #DBE0E6",
"`+	c #94A7B5",
" @	c #476277",
".@	c #BAC5CB",
"+@	c #D2D7DA",
"@@	c #F3F4F8",
"#@	c #6B8091",
"$@	c #E7EBEC",
"%@	c #F5F5F5",
"&@	c #8292A1",
"*@	c #7F92A1",
"=@	c #95A7B3",
"-@	c #698092",
";@	c #F4F4F2",
">@	c #D2D7DB",
",@	c #5A758A",
"'@	c #526D80",
")@	c #8A9DAB",
"!@	c #E8ECEF",
"~@	c #DEDFE1",
"{@	c #ADBAC2",
"]@	c #486279",
"^@	c #7E94A2",
"/@	c #446377",
"(@	c #95A8B7",
"_@	c #ADBBC6",
":@	c #E4EBF1",
"<@	c #456177",
"[@	c #FEFDFF",
"}@	c #42627B",
"|@	c #46647E",
"1@	c #DDE0E7",
"2@	c #486177",
"3@	c #AEBBC4",
"4@	c #F4F5F7",
"5@	c #BBC5CE",
"6@	c #F6F5F3",
"7@	c #7F95A3",
"8@	c #4E6D81",
"9@	c #B0BAC3",
"0@	c #5B768B",
"a@	c #E7EAF1",
"b@	c #697F8C",
"c@	c #B9C6CE",
"d@	c #889DAE",
"e@	c #738A98",
"f@	c #C4CDD2",
"g@	c #506C84",
"h@	c #476275",
"i@	c #516D82",
"j@	c #EEF6F9",
"k@	c #708B9E",
"l@	c #DDE2E8",
"m@	c #436378",
"n@	c #8194A3",
"o@	c #E9EAEE",
"p@	c #768998",
"q@	c #526D82",
"r@	c #879DAB",
"s@	c #526B7F",
"t@	c #8B9CAC",
"u@	c #668091",
"v@	c #BAC4CE",
"w@	c #C5CED7",
"                                                                                                  .   +     @ #                                 # .   #         $ % @ % % &   *   # = # % % . - ; > %   . . # =                           ",
"                                                                                                , + -       .                                                 #     ' + ) . !   =     % . # ~ { ] # , # - % %                             ",
"                                                                                                ^ ) / ( _ : < [                                 + # . . / } | 1 2 3 # #   + . . # % % 4 5 6 7 ] # 8 % + . . % !                           ",
"                                                                                                . 4 9 0 a b c d                                 .   . # e 0 f g h } * % .   . # % # # i j k l   # .     %   . .                           ",
"                                                                                                & # m a n o p q                                   # *   r s 0 a t u   =   +     ! v w x y z - A B , # 4 #     +                           ",
"                                                                                                .   C a 0 a n D                                   #   + E F 0 h p 2   % %   ! G H I J K L M N O = ^ %   4   # =                           ",
"                                                                                                %   P n 0 0 o Q                                   -   # P 0 R 0 h } %   S ' T U I V W X Y Z ` + . %     . # @ .                           ",
"                                                                                                %   P n o p 0 D                                     %   P a R  ...} % #     +.W @.#.W $.W %.^ #   #           &.                          ",
"              +     +   . .     !               # #           +                           .   # # + e F p 0 o D         %       .             +         C 0 p 0 0 2 . ^     6 J @.J *.W ` =.-.;.  % + #   % ^ # # #     .                 ",
"  + # &   . 4         # #       . .                     . .     +               .   &         % +   >.o a a 0 ,.+ +       +         . . .     .         C 0 p 0 p : +   * # '.).W #.y !.~.{.].  .   # -   +       % % @       .           ",
"    . %   +   +             # # #     # # + . + .     #     # #             . . .   # - #           r 0 ..^./.(.. .   & # & # #       #   % + ,         C 0 p 0 s _.    !   :.<.x I [.}.I z   % #     . .   # , .   + # - # # #           ",
"            +     ! #       . .   + % . . .           +     @ .             & #       % . +   ^ + + |.b ^.0 o D       % .                     .         C 0 p 0 1.2.  + . +   3.V 4.@.I O *   .   .   - # . . . .   #   .     .           ",
"        @ . + & +     . .   # & . # # @ . # # . #   @ .   #               + +     # #       + .   + P a p F n ,.% %   +         @ # , + .     .         C 0 p 0 n 5.. . %   '   6.7.'.8.  . % #   + # # # #   .     % . ^   +             ",
"    +   # &   . .   +   # & # #   +   # &   +         + + #     # +     . . . .   9.* # ,     &     P p F n F (.            !     @ %         #         C 0 p 0 a u &.        .   % . # + * . % )     0.. # # . + # # #   . %             ",
"# # # a.b.(.c.d.e.f.n 0 o g.h.i.j.k.# &   . . , . +     . @ # l.m.n.o.p 0 n p.q.r.s.  #   0.. #     r p n o R t.u.v.w.x.y.P x.z.Q A.@   # + . .         C 0 p 0 0 B.%   C.  % } D.E.F.G.H.- % % #     # I.J.K.a L.F M.C N.I., 4           ",
"O.P.Q...n R.o S.0 0 0 0 0 a 0 0 R n J.u.. ^   .   # # %   T.J.n F p 0 0 a 0 p n R F i.k..   # .   + C p o ..U.V.0 0 p o p a 0 0 R a W.X.  . + #         C 0 p 0 o Y.    # .   (.Z.a 0 p C   # =   . u `.R L. +..S.a R.p .+s ++@+          ",
"d n a o 0 #+R F 0 0 0 a p  .n 1.n ^.n $+%+& #   #   . # &+M.p ..0 n F a 0 n n 0 a L.p *+=+.         e ..#+n R n p 1.h o a 0 a ^.p 0 0 0 c.k.            C n S.a p -+#         D 0 0 0 n |.    # % ;+0 o 0 ^.o 0 n ^. .>+F p ^.i.          ",
"(.F ..a 0 ,+'+)+< & % % !+@+~+h {+p 1.b M./ + . % .   ]+o >+a h p ^+/+,   (+_+C 0 /.h o :+/   #     d.0 ^.L.a <+d A.. . . ^ [+i.0 0 o o 0 o.}+#         |+n ^.n p -+#         D 0 0 o n P # .   -+1+..>+o 1.2+3+} u u 4+5+0 o l.          ",
",.n a b a 6+7+  #   % % . . # 8+M.F ..^...C % +     u.M.0 #+p L.9+, % !   @ .   0+p a h 0 a+3 ^   + b+o p n n c+. + # & # #     -+d+R o a R.5+  . ! #   C n p n p -+#         D F o p F P # . % e+p #+^.f+g+7+, % +   #   h+i+#           ",
"(.0 p F 0 D . . # +       .   # 2 n p j+n ..k+  # . C o p p 0 l+        @     #   z.^.n F R m+.   # n+n p p >+D   + +           . =+o n p n a o+.   # + |.h o F p -+#         D n 0 0 n P     8+n a p 0 p+q+.     % )     8 . .           ",
"r+a n n #+D   #     +   + .     - o.p 0 1.o s+- # t+R u+R F 2+@ 4 # # +   +     . l.0 0 a 0 p v+    P o 0 ..a w+& . @   + .   #   + x+y+#+b a g.# % +   r /.z+0 p -+#         D o a b o C . # A+..0 a 0 B+# 8 # . & # , - .               ",
"(.0 a a y+,.+         # #   +   # e ^.L.p p C+  . D+>+a n n E+. # ^ @     ! % . # 4 F+a R.R o G+    P 0 a ^...,.% +   % ^ +   %   # H+I+n F >+^./+% .   P 0 0 ..p -+#         D t 0 a t C ) # J+F ^.0 0 K+=   ! #   +   .   # 4           ",
"Q p 0 0 /.D   . . . + # &       4 L+h F 0 0 d * % M+F ..o u+N+# . .     @ . . # #   O+F p F 0 P+    P ..p p ..Q       +     +   #   . i.0 R.o n Q+  . # C a a 0 p -+#         D t 0 1.o R+% ! } p S+o o T+^   # % % %   . + + #           ",
"(.o p F n D #   # +       ^   &   9 R L...a w+# (+^.a a R a   .   # # %   # # .     =+h 0 ..p U+  . P R F L.0 6+  #             %   . &+S.0 0 a g.  . # n+n p a p -+#         D ..p n o V+    W+#+o p p 1.J.  % *   !   #   )             ",
"D p p p 0 D                       C 0 0 0 0 (.  2 R F p p X+. +                       p 1.o 0 p Y+  V+b F p 0 (.                # .   Z+p n F 0 o # #   E ^.o 0 p -+#         D 0 p 0 p C       `+ @0 ..p n |+2 . .   4   + %   #         ",
"D p p p 0 D                       C 0 0 0 0 (.  .@a n p p y..                         o h o 0 0 +@  P a >+p 0 (.                  .   # p o h a p 8+-   e a p 0 p -+#         D 0 p 0 p C       @@#@#+0 a 0 F h o.m.$@  &   @ #   .       ",
"D p p p 0 D                       C 0 0 0 0 (.  l+0 a 0 o P %                   +   + z+0 o b 0 _ # n+0 o 0 0 ,.                    + % a p 0 a a }     n+o p a p -+#         D 0 p 0 p C         %@&@o 0 s 0 a o 0 L.5+} % #     .       ",
"D p p p 0 D                       C 0 0 0 0 (.  d n 0 0 p d.                          o a p 0 a ( # C F o ..a E.                    . 8 0 b a p s B.!   |+F o 0 p -+#         D 0 p 0 p C       . # # _ h.p n ^...n ^.R n *@k.#       . . ",
"D p p p 0 D                       C 0 0 0 0 (.  D F a b p e                           p 0 p a p 2 # n+n p ..0 E.                    4 . 0 a 0 p 0 }     n+>+p a p -+#         D 0 p 0 p C       +   # #   [ =@`.o ..R o n R -@;@. #   . . ",
"D p p p 0 D                       C 0 0 0 0 (.  &+o 0 /.p L++                         o a p 0 o >@+ |+0 p 0 a D                   +   , n 0 o 0 F v+  + |./.p o p -+#         D 0 p 0 p C         & % . 4   # . | h.n p F p R W.#         ",
"D p p p 0 D                       C 0 0 0 0 (.  -+p p 0 0 ,@                        ! 0 0 o a n !+% C 0 o p 0 ,.                + %   2 F s p 0 '@!     P 0 o o p -+#         D 0 p 0 p C       %     !   #     # . )@o p #+n 0 &+        ",
"D p p p 0 D                       C 0 0 0 0 (.  !@..o 0 0 n +                     # ~@a 0 p n U+# . C 0 p o h Q                   % # {@]@1+n a V+% 4   m ..o p p -+#         D 0 p 0 p C       # . + . . +   #   ) 7+e+p h ^.F F+        ",
"D p p p 0 D                       C 0 0 0 0 (.  = `.h 0 L.0 -+.   . .         .     9+n o .+n ^@  & P ^.R o L.(.# % % # # % % # .   % 5+..^.0 h 3+# . . P 0 >+o p -+#         D n 0 p s C   , % .   # # #     #   + . E...n /@a P .   # . ",
"D p p p 0 D                       C 0 0 0 0 (.  ^ )@p 0 0 F (@  . # #     .       & Q+>+F ^.F _@    d.>+/.0 F E.%             % 7+  l.o R.F ..o :@# . + P 0 <@0 p -+#         D 0 n  .s P . . . %       . . 4   . . [@d R 1.p a P +     & ",
"D p p p 0 D                       C 0 0 0 0 (.    -+p F a b d+Y+.   @ ) + -   #   [ n a p ^.]@W+    |+F n a a (.      # #         # g+p 0 h }@'+, + . + P 0 0 ..p -+#         D ..a p 0 C @ + ,   -     ^ %         . )@F |@/.0 e #   +   ",
"D p p p 0 D                       C 0 0 0 0 (.  +   P ..0 1.n N.  .   &   . @ #   5+F ..#+ @)@.     |.o F 0 ..D % . 4 .   4 +   . &+o a a a :+l.  .   # C a 0 ^.p -+#         D a R 0 n n+    # & % .   #   . @ = # 1@2@p a 0 n 3@    % # ",
"D p p p 0 D                       C 0 0 0 0 (.  .   =+..p n F a D & - , @ . # . i./@n 1+L.a+4@7+%   e n b a p E.-             # s+1.R.#+>+a 5@  .   & # C n F p p -+#         D o 0 F n L+# @ 6@7@2 . . #   + # % N+8@t ..0 #+U+3 .   # 8 ",
"D p p p 0 D                       C 0 0 0 0 (.  # * # O+o ..U.1+ .g.)+>@2 } 9@0@..0 ....1.=+#   . # y...0 n 0 |+_.& 0.. # a@)+b@....0 a ^.c@.   +   #   x.a F o p -+#         D p F p /.C   # (.0 R.<+d@,.< 2 l+e@0 #+a ..L.n f@#   .   . ",
"D p p p 0 D                       C 0 0 0 0 (.      9.# &+n  .n ..n 0 #+a p a n 0 n a g@: . %   % # C n a F R ^.a z+o 1.h a ..R R h@0 i@@+. . +       4 x.a 0 n p -+#         D n 0 ..0 e . j@M.S...p 0 0 o n n n ]@t a L.U+)+- j.k@M+%+C ",
"D p p p 0 D                       C 0 0 0 0 (.  .     #   l@x.m@0 .... .n 1+R p 0 a n@o@        # . _+p@0 n a p h o p a 0 p F n F q@r@(+  % # .       . e R a p p -+#         D n a ^.h C   (+r+s@0 R o n a ..p a s F h t@[ ^     ,.d.M.)@",
"2 D (.D D B.                      &+(.D (.D -+      #         / K+C 0 0 0 p I+C D l.      #             l.&+)@C U+p 0 ..n 0 C i.)+4@            .       &+D D (.D l.          -+D D (.D &+        /+D C W.n a a u@c.s+l.          B.v@w@} "
};





#endif



