/*
 * RCS info
 * $Author: steves $
 * $Locker:  $
 * $Date: 2014/07/30 19:09:45 $
 * $Id: hci_read_l2.h,v 1.5 2014/07/30 19:09:45 steves Exp $
 * $Revision: 1.5 $
 * $State: Exp $
 */

#ifndef HCI_READ_L2_H
#define HCI_READ_L2_H

#include <glib.h>
#include <gtk/gtk.h>
#include <string.h>
#include <infr.h>
#include <orpg.h>
#include <mrpg.h>

enum { STATE = 0, RADAR, COLUMNS };
enum { CATEGORY = 0, CHILD };

typedef struct radar_sites {

   gint type;
   gchar *radar;

} Radar_sites_t;

static Radar_sites_t Radar_sites[] = {
                              { CATEGORY, "Alaska" },
                              { CHILD, "PACG (Sitka/Biorka Island)" },
                              { CHILD, "PAEC (Nome)" },
                              { CHILD, "PAIH (Middleton Island)" },
                              { CHILD, "PAKC (King Salmon)" },
                              { CHILD, "PAHG (Kenai)" },
                              { CHILD, "PAPD (Fairbanks/Pedro Dome)" },
                              { CHILD, "PABC (Bethel)" },
                              { CATEGORY, "Alabama" },
                              { CHILD, "KMOB (Mobile)" },
                              { CHILD, "KMXX (Maxwell AFB)" },
                              { CHILD, "KHTX (Huntsville)" },
                              { CHILD, "KEOX (Fort Rucker)" },
                              { CHILD, "KBMX (Birmingham)" },
                              { CATEGORY, "Arkansas" },
                              { CHILD, "KLZK (Little Rock)" },
                              { CHILD, "KSRX (Fort Smith)" },
                              { CATEGORY, "Arizona" },
                              { CHILD, "KYUX (Yuma)" },
                              { CHILD, "KEMX (Tucson)" },
                              { CHILD, "KIWA (Phoenix)" },
                              { CHILD, "KFSZ (Flagstaff)" },
                              { CATEGORY, "California" },
                              { CHILD, "KVBX (Vandenberg AFB)" },
                              { CHILD, "KSOZ (Santa Ana Mountains)" },
                              { CHILD, "KHNX (San Joaquin Valley)" },
                              { CHILD, "KMUX (San Francisco)" },
                              { CHILD, "KNKX (San Diego)" },
                              { CHILD, "KDAX (Sacramento)" },
                              { CHILD, "KVTX (Los Angeles)" },
                              { CHILD, "KBHX (Eureka)" },
                              { CHILD, "KEYX (Edwards AFB)" },
                              { CHILD, "KBBX (Beale AFB)" },
                              { CATEGORY, "Colorado" },
                              { CHILD, "KPUX (Pueblo)" },
                              { CHILD, "KGJX (Grand Junction)" },
                              { CHILD, "KFTG (Denver)" },
                              { CATEGORY, "Delaware" },
                              { CHILD, "KDOX (Dover AFB)" },
                              { CATEGORY, "Florida" },
                              { CHILD, "KTBW (Tampa)" },
                              { CHILD, "KTLH (Tallahassee)" },
                              { CHILD, "KAMX (Miami)" },
                              { CHILD, "KMLB (Melbourne)" },
                              { CHILD, "KBYX (Key West)" },
                              { CHILD, "KJAX (Jacksonville)" },
                              { CHILD, "KEVX (Eglin AFB)" },
                              { CATEGORY, "Georgia" },
                              { CHILD, "KJGX (Robins AFB)" },
                              { CHILD, "KVAX (Moody AFB)" },
                              { CHILD, "KFFC (Atlanta)" },
                              { CATEGORY, "Guam" },
                              { CHILD, "PGUA (Andersen AFB)" },
                              { CATEGORY, "Hawaii" },
                              { CHILD, "PHWA (South Shore)" },
                              { CHILD, "PHMO (Molokai)" },
                              { CHILD, "PHKM (Kohala)" },
                              { CHILD, "PHKI (Kauai)" },
                              { CATEGORY, "Iowa" },
                              { CHILD, "KDMX (Des Moines)" },
                              { CHILD, "KDVN (Davenport)" },
                              { CATEGORY, "Idaho" },
                              { CHILD, "KSFX (Pocatello/Idaho Falls)" },
                              { CHILD, "KCBX (Boise)" },
                              { CATEGORY, "Illinois" },
                              { CHILD, "KILX (Lincoln)" },
                              { CHILD, "KLOT (Chicago)" },
                              { CATEGORY, "Indiana" },
                              { CHILD, "KIWX (North Webster)" },
                              { CHILD, "KIND (Indianapolis)" },
                              { CHILD, "KVNX (Evansville)" },
                              { CATEGORY, "Kansas" },
                              { CHILD, "KICT (Wichita)" },
                              { CHILD, "KTWX (Topeka)" },
                              { CHILD, "KGLD (Goodland)" },
                              { CHILD, "KDDC (Dodge City)" },
                              { CATEGORY, "Kentucky" },
                              { CHILD, "KPAH (Paducah)" },
                              { CHILD, "KLVX (Louisville)" },
                              { CHILD, "KJKL (Jackson)" },
                              { CHILD, "KHPX (Fort Campbell)" },
                              { CATEGORY, "Louisiana" },
                              { CHILD, "KSHV (Shreveport)" },
                              { CHILD, "KLIX (New Orleans)" },
                              { CHILD, "KLCH (Lake Charles)" },
                              { CHILD, "KPOE (Fort Polk)" },
                              { CATEGORY, "Massachusetts" },
                              { CHILD, "KBOX (Boston)" },
                              { CATEGORY, "Maine" },
                              { CHILD, "KGYX (Portland)" },
                              { CHILD, "KCBW (Loring AFB)" },
                              { CATEGORY, "Michigan" },
                              { CHILD, "KMQT (Marquette)" },
                              { CHILD, "KGRR (Grand Rapids)" },
                              { CHILD, "KAPX (Gaylord)" },
                              { CHILD, "KDTX (Detroit/Pontiac)" },
                              { CATEGORY, "Minnesota" },
                              { CHILD, "KMPX (Minneapolis/St. Paul)" },
                              { CHILD, "KDLH (Duluth)" },
                              { CATEGORY, "Missouri" },
                              { CHILD, "KLSX (St. Louis)" },
                              { CHILD, "KSGF (Springfield)" },
                              { CHILD, "KEAX (Kansas City)" },
                              { CATEGORY, "Mississippi" },
                              { CHILD, "KGWX (Columbus AFB)" },
                              { CHILD, "KDGX (Brandon/Jackson)" },
                              { CATEGORY, "Montana" },
                              { CHILD, "KMSX (Missoula)" },
                              { CHILD, "KTFX (Great Falls)" },
                              { CHILD, "KGGW (Glasgow)" },
                              { CHILD, "KBLX (Billings)" },
                              { CATEGORY, "North Carolina" },
                              { CHILD, "KLTX (Wilmington)" },
                              { CHILD, "KRAX (Carolina,Raleigh/Durham)" },
                              { CHILD, "KMHX (Carolina,Morehead City)" },
                              { CATEGORY, "North Dakota" },
                              { CHILD, "KMBX (Carolina,Minot AFB)" },
                              { CHILD, "KMVX (Grand Forks (Mayville))" },
                              { CHILD, "KBIS (Bismarck)" },
                              { CATEGORY, "Nebraska" },
                              { CHILD, "KOAX (Omaha)" },
                              { CHILD, "KLNX (North Platte)" },
                              { CHILD, "KUEX (Grand Island/Hastings)" },
                              { CATEGORY, "New Mexico" },
                              { CHILD, "KHDX (Holloman AFB)" },
                              { CHILD, "KFDX (Cannon AFB)" },
                              { CHILD, "KABX (Albuquerque)" },
                              { CATEGORY, "Nevada" },
                              { CHILD, "KRGX (Reno)" },
                              { CHILD, "KESX (Las Vegas)" },
                              { CHILD, "KLRX (Elko)" },
                              { CATEGORY, "New York" },
                              { CHILD, "KOKX (New York City)" },
                              { CHILD, "KTYX (Montague)" },
                              { CHILD, "KBUF (Buffalo)" },
                              { CHILD, "KBGM (Binghamton)" },
                              { CHILD, "KENX (Albany)" },
                              { CATEGORY, "Ohio" },
                              { CHILD, "KILN (Wilmington)" },
                              { CHILD, "KCLE (Cleveland)" },
                              { CATEGORY, "Oklahoma" },
                              { CHILD, "KVNX (Vance AFB)" },
                              { CHILD, "KINX (Tulsa)" },
                              { CHILD, "KTLX (Oklahoma City)" },
                              { CHILD, "NOP3 (ROC)" },
                              { CHILD, "NOP4 (ROC)" },
                              { CHILD, "ROP3 (ROC)" },
                              { CHILD, "ROP4 (ROC)" },
                              { CHILD, "FOP1 (ROC)" },
                              { CHILD, "DOP1 (ROC)" },
                              { CHILD, "DAN1 (ROC)" },
                              { CHILD, "KFDR (Frederick)" },
                              { CHILD, "KOUN (NSSL)" },
                              { CATEGORY, "Oregon" },
                              { CHILD, "KRTX (Portland)" },
                              { CHILD, "KPDT (Pendleton)" },
                              { CHILD, "KMAX (Medford)" },
                              { CATEGORY, "Pennsylvania" },
                              { CHILD, "KCCX (State College)" },
                              { CHILD, "KPBZ (Pittsburgh)" },
                              { CHILD, "KDIX (Philadelphia)" },
                              { CATEGORY, "Puerto Rico" },
                              { CHILD, "TJUA (San Juan)" },
                              { CATEGORY, "South Carolina" },
                              { CHILD, "KGSP (Greer)" },
                              { CHILD, "KCAE (Columbia)" },
                              { CHILD, "KCLX (Charleston)" },
                              { CATEGORY, "South Dakota" },
                              { CHILD, "KFSD (Sioux Falls)" },
                              { CHILD, "KUDX (Rapid City)" },
                              { CHILD, "KABR (Aberdeen)" },
                              { CATEGORY, "Tennessee" },
                              { CHILD, "KOHX (Nashville)" },
                              { CHILD, "KNQA (Memphis)" },
                              { CHILD, "KMRX (Knoxville/Tri Cities)" },
                              { CATEGORY, "Texas" },
                              { CHILD, "KSJT (San Angelo)" },
                              { CHILD, "KMAF (Midland/Odessa)" },
                              { CHILD, "KLBB (Lubbock)" },
                              { CHILD, "KDFX (Laughlin AFB)" },
                              { CHILD, "KHGX (Houston/Galveston)" },
                              { CHILD, "KGRK (Fort Hood)" },
                              { CHILD, "KEPZ (El Paso)" },
                              { CHILD, "KDYX (Dyess AFB)" },
                              { CHILD, "KFWS (Dallas/Ft. Worth)" },
                              { CHILD, "KCRP (Corpus Christi)" },
                              { CHILD, "KBRO (Brownsville)" },
                              { CHILD, "KEWX (Austin/San Antonio)" },
                              { CHILD, "KAMA (Amarillo)" },
                              { CATEGORY, "Utah" },
                              { CHILD, "KMRX (Salt Lake City)" },
                              { CHILD, "KICX (Cedar City)" },
                              { CATEGORY, "Virginia" },
                              { CHILD, "KLWX (Sterling)" },
                              { CHILD, "KFCX (Roanoke)" },
                              { CHILD, "KAKQ (Norfolk/Richmond)" },
                              { CATEGORY, "Vermont" },
                              { CHILD, "KCCX (Burlington)" },
                              { CATEGORY, "Washington"},
                              { CHILD, "KOTX (Spokane)" },
                              { CHILD, "KATX (Seattle/Tacoma)" },
                              { CHILD, "KLGX (Langley Hill)" },
                              { CATEGORY, "Wisconsin"},
                              { CHILD, "KMKX (Milwaukee)" },
                              { CHILD, "KARX (La Crosse)" },
                              { CHILD, "KGRB (Green Bay)" },
                              { CATEGORY, "West Virginia" },
                              { CHILD, "KRLX (Charleston)" },
                              { CATEGORY, "Wyoming" },
                              { CHILD, "KRIW (Riverton)" },
                              { CHILD, "KCYS (Cheyenne)" },
                              { CATEGORY, NULL } };

#endif
