#!/bin/sh

# RCS info
# $Author: ccalvert $
# $Locker:  $
# $Date: 2007/02/26 16:03:00 $
# $Id: usage,v 1.4 2007/02/26 16:03:00 ccalvert Exp $
# $Revision: 1.4 $
# $State: Exp $

TEMP_DIR=/tmp

###########################################
#Establish timestamped output file and Path
###########################################

date_string=`date`
day=`echo $date_string | awk '{print $1}'`
month=`echo $date_string | awk '{print $2}'`
numb=`echo $date_string | awk '{print $3}'`
time_string=`echo $date_string | awk '{print $4}'`
zone=`echo $date_string | awk '{print $5}'`
year=`echo $date_string | awk '{print $6}'`
hour=`echo $time_string | awk -F: '{print $1}'`
min=`echo $time_string | awk -F: '{print $2}'`
sec=`echo $time_string | awk -F: '{print $3}'`

exec 2> /dev/null

trap 'echo " "' ERR

if [ $1 = "s" ]
then
  mkdir $ORPGDIR/testing
  Report_file="${ORPGDIR}/testing/usage_${month}${numb}_${hour}.rpt"
  date > $Report_file
  echo
  echo "What is the test being performed?  :"
  read testtype
  TESTTYPE=$testtype
  echo "Test being performed is   :   $TESTTYPE" >> $Report_file
  echo "Timestamped output file is:  $Report_file"
fi

###########################################
#Determine version number
###########################################

echo "Current software account  :  $USER" | tee -a $Report_file
echo "Host is                   :   " | tee -a $Report_file

hostname | tee -a $Report_file

###########################################
#Separate processes by owner
###########################################

ps -A  -y -o fname= -o user= -o pcpu= -o rss= -o vsz= > $TEMP_DIR/Resources.tmp

cat $TEMP_DIR/Resources.tmp |egrep rpg > $TEMP_DIR/User.tmp
cat $TEMP_DIR/Resources.tmp |awk '/root/' > $TEMP_DIR/Root.tmp
cat $TEMP_DIR/Resources.tmp |awk '/daemon/' > $TEMP_DIR/Daemon.tmp

awk '{ val+=$3 } END { print "Total CPU usage           :  ", val, " %" }' $TEMP_DIR/Resources.tmp | tee -a ${Report_file}
awk '{ val+=$3 } END { print "RPG processes CPU usage   :  ", val, " %" }' $TEMP_DIR/User.tmp | tee -a ${Report_file}
awk '{ val+=$3 } END { print "Root processes CPU usage  :  ", val, " %" }' $TEMP_DIR/Root.tmp | tee -a ${Report_file}
awk '{ val+=$3 } END { print "Daemon processes CPU usage:  ", val, " %" }' $TEMP_DIR/Daemon.tmp | tee -a ${Report_file}

###########################################
#Find Failed tasks
###########################################

echo
echo "FAILED RPG tasks:" |tee -a $Report_file

rpg_ps > $TEMP_DIR/Rpgps.tmp

cat $TEMP_DIR/Rpgps.tmp |grep FAIL |tee -a $Report_file

rm $TEMP_DIR/User.tmp
rm $TEMP_DIR/Root.tmp 
rm $TEMP_DIR/Daemon.tmp 
rm $TEMP_DIR/Resources.tmp
rm $TEMP_DIR/Rpgps.tmp
