Bias_table {
   site_id           OUN
   radar_id          CRI
   obs_year         2000	
   obs_month          11	
   obs_day            28	
   obs_hour            8	
   obs_min            35
   obs_sec             5
   gen_year         2000
   gen_month          11
   gen_day            27
   gen_hour           10
   gen_min            40
   gen_sec            25	
   n_rows              2
   mem_span         9900  10000    
   n_pairs           100   2000
   avg_gage        12500   9000
   avg_radar       20000   5000
   bias             5000      1
}

