/********************************************************************************
     nbtcp_smipp.h - This file contains the structure and function declarations 
                     that need the byte swapping code generated by the SMI 
                     Pre-processor. File nbtcp_smipp.c is generated when the SMI
                     Pre-processor is executed on this file.
 ********************************************************************************/

/*
 * RCS info
 * $Author: steves $
 * $Locker:  $
 * $Date: 2005/04/12 14:38:16 $
 * $Id: nbtcp_smipp.c,v 1.3 2005/04/12 14:38:16 steves Exp $
 * $Revision: 1.3 $
 * $State: Exp $
 */

#ifndef NBTCP_SMI_H
#define NBTCP_SMI_H


#include <prod_user_msg.h>
#include <legacy_prod.h>
#include <nbtcp.h>



/****** SMI Structure Definitions ******/

/*     Product Request Message */

/* SMI_struct Pd_request_products; */  /* refer prod_user_msg.h */
/* SMI_struct msg_header; */
/* SMI_struct RPS_block; */

/*     Alert Request Msg */

/* SMI_struct Pd_alert_category_def_msg; */ /* refer prod_user_msg.h */
/* SMI_struct Pd_alert_box_msg; */          /* refer prod_user_msg.h */
/* SMI_struct alert_area_t; */

/*     Bias Table Msg */

/* SMI_struct bias_table_msg_base_t; */
/* SMI_struct Block_id_t; */      /* refer prod_user_msg.h */
/* SMI_struct Memory_span_t; */   /* refer prod_user_msg.h */



/****** SMI Function Definitions ******/


/* SMI_function SWAp_bytes; */

#endif



/* The following is generated by smipp */

#include <smi.h>

static int Need_byte_swap_data = 0;

                                                   

static const char All_names[] = 
"rda_performance_t\0msg_hdr\0RDA_RPG_message_header_t\0\
rpg\0wideband_t\0user\0wideband_t\0data\0bitdata_t\0calibration\0calibration_t\0\
clutter_check\0clutter_check_t\0disk_status\0disk_file_status_t\0device_init\0device_init_t\0\
device_error\0device_io_error_t\0interproc_chan_resp\0short\0spare502\0short\0\
chan_in_cntrl\0short\0spare504\0short\0spare505\0short\0spare506\0short\0\
spare507\0short\0spare508\0short\0spare509\0short\0spare510\0short\0spare511\0short\0\
spare512\0short\0spare513\0short\0spare514\0short\0spare515\0short\0spare516\0short\0\
spare517\0short\0spare518\0short\0spare519\0short\0spare520\0short\0RDA_RPG_console_message_t\0\
msg_hdr\0RDA_RPG_message_header_t\0size\0short\0message\0char\0struct alg_cpu_stats\0\
vol_scan_num\0unsigned int\0elev_cnt\0int\0total_cpu\0float\0avg_cpu\0float\0\
avg_cpu_percent\0float\0Pd_request_products\0divider\0short\0length\0short\0\
prod_id\0short\0flag_bits\0short\0seq_number\0short\0num_products\0short\0\
req_interval\0short\0VS_date\0short\0VS_start_time\0int\0params\0short\0msg_header\0\
msgcode\0short\0date_of_msg\0short\0time_of_msg_msw\0short\0time_of_msg_lsw\0short\0\
length_of_msg_msw\0short\0length_of_msg_lsw\0short\0src_id\0short\0dst_id\0short\0\
no_of_blocks\0short\0RPS_block\0divider\0short\0length_of_blk\0short\0prod_code\0short\0\
flag\0short\0seq_no\0short\0no_of_prods\0short\0req_intrvl\0short\0vol_scan_date\0short\0\
vol_scan_time_msw\0short\0vol_scan_time_lsw\0short\0prod_parms\0short\0Pd_alert_category_def_msg\0\
alert_category\0short\0thd_code\0short\0prod_req_flag\0short\0Pd_alert_box_msg\0\
b1\0short\0b2\0short\0b3\0short\0b4\0short\0alert_area_t\0divider\0short\0\
length\0short\0alert_area_num\0short\0num_category\0short\0bias_table_msg_base_t\0\
awips_id\0char\0radar_id\0char\0obs_yr\0short\0obs_mon\0short\0obs_day\0short\0\
obs_hr\0short\0obs_min\0short\0obs_sec\0short\0gen_yr\0short\0gen_mon\0short\0\
gen_day\0short\0gen_hr\0short\0gen_min\0short\0gen_sec\0short\0n_rows\0short\0\
Block_id_t\0divider\0short\0block_id\0short\0version\0short\0length\0short\0\
Memory_span_t\0mem_span_msw\0short\0mem_span_lsw\0short\0n_pairs_msw\0short\0\
n_pairs_lsw\0short\0avg_gage_msw\0short\0avg_gage_lsw\0short\0avg_radar_msw\0short\0\
avg_radar_lsw\0short\0bias_msw\0short\0bias_lsw\0short\0RDA_RPG_message_header_t\0\
size\0short\0rda_channel\0unsigned char\0type\0unsigned char\0sequence_num\0short\0\
julian_date\0unsigned short\0milliseconds\0int\0num_segs\0short\0seg_num\0short\0\
wideband_t\0dcu_status\0short\0general_error\0short\0svc_15_error\0short\0\
outgoing_frames\0unsigned short\0frames_fcs_errors\0unsigned short\0retrans_i_frames\0unsigned short\0\
polls_sent_recvd\0unsigned short\0poll_timeout_exp\0short\0min_buf_read_pool\0unsigned short\0\
max_buf_read_done\0unsigned short\0loopback_test\0short\0spare12\0short\0\
spare13\0short\0spare14\0short\0spare15\0short\0bitdata_t\0data31\0short\0\
data32\0short\0data33\0short\0data34\0short\0data35\0short\0data36\0short\0\
data37\0short\0out_temp\0unsigned char\0eqp_shelt_temp\0unsigned char\0ac1_air_temp\0unsigned char\0\
trans_air_temp\0unsigned char\0radome_air_temp\0unsigned char\0gen_shelt_temp\0unsigned char\0\
gen_fuel_level\0unsigned char\0spare41l\0unsigned char\0spare42h\0unsigned char\0\
spare42l\0unsigned char\0spare43h\0unsigned char\0spare43l\0unsigned char\0\
spare44h\0unsigned char\0spare44l\0unsigned char\0ac2_air_temp\0unsigned char\0\
spare45l\0unsigned char\0spare46h\0unsigned char\0xmtr_rf_pwr\0unsigned char\0\
ant_rf_pwr\0unsigned char\0spare47l\0unsigned char\0spare48h\0unsigned char\0\
spare48l\0unsigned char\0spare49h\0unsigned char\0ped_p28v_ps\0unsigned char\0\
enc_p5v_ps\0unsigned char\0ped_p15v_ps\0unsigned char\0spare51h\0unsigned char\0\
ped_p5v_ps\0unsigned char\0spare52h\0unsigned char\0spare52l\0unsigned char\0\
sig_proc_p5v_ps\0unsigned char\0spare53l\0unsigned char\0mnt_con_p28v_ps\0unsigned char\0\
mnt_con_p15v_ps\0unsigned char\0mnt_con_p5v_ps\0unsigned char\0spare55l\0unsigned char\0\
spare56h\0unsigned char\0spare56l\0unsigned char\0ped_n15v_ps\0unsigned char\0\
spare57l\0unsigned char\0spare58h\0unsigned char\0mnt_con_n15v_ps\0unsigned char\0\
spare59h\0unsigned char\0dau_test0\0unsigned char\0dau_test1\0unsigned char\0\
dau_test2\0unsigned char\0spare61h\0unsigned char\0spare61l\0unsigned char\0\
dau_interface\0short\0xmtr_sum_stat\0short\0spare64\0short\0spare65\0short\0\
spare66\0short\0spare67\0short\0spare68\0short\0spare69\0short\0spare70\0short\0\
spare71\0short\0spare72\0short\0spare73\0short\0spare74\0short\0spare75\0short\0\
spare76\0short\0spare77\0short\0spare78\0short\0spare79\0short\0spare80\0short\0\
spare81\0short\0spare82\0short\0spare83\0short\0spare84\0short\0spare85\0short\0\
spare86\0short\0spare87\0short\0spare88\0short\0spare89\0short\0spare90\0short\0\
spare91\0short\0spare92\0short\0spare93\0short\0spare94\0short\0spare95\0short\0\
data96\0short\0data97\0short\0data98\0short\0az_pos_corr\0short\0el_pos_corr\0short\0\
spare101\0short\0spare102\0short\0spare103\0short\0spare104\0short\0spare105\0short\0\
spare106h\0unsigned char\0rf_gen_data\0unsigned char\0spare107\0short\0spare108\0short\0\
spare109h\0unsigned char\0parity_alrm_cf\0unsigned char\0spare110\0short\0\
spare111\0short\0prt1_int\0unsigned short\0prt2_int\0unsigned short\0spare114\0short\0\
spare115\0short\0spare116\0short\0spare117\0short\0spare118\0short\0spare119\0short\0\
spare120\0short\0spare121\0short\0spare122\0short\0ant_pk_pwr\0float\0xmtr_pk_pwr\0float\0\
ant_rf_ave_pwr\0float\0xmtr_rf_ave_pwr\0float\0mwave_loss\0float\0ant_pwr_mtr_zero\0float\0\
xmtr_pwr_mtr_zero\0float\0xmtr_rec_cnt\0int\0spare139\0short\0spare140\0short\0\
sh_pulse_lin_chan_noise\0float\0sh_pulse_log_chan_noise\0float\0lo_pulse_lin_chan_noise\0float\0\
lo_pulse_log_chan_noise\0float\0system_noise_temp\0float\0idu_tst_detect\0short\0\
spare152\0short\0calibration_t\0agc_step1_amp\0float\0agc_step2_amp\0float\0\
agc_step3_amp\0float\0agc_step4_amp\0float\0agc_step5_amp\0float\0agc_step6_amp\0float\0\
agc_step1_phase\0float\0agc_step2_phase\0float\0agc_step3_phase\0float\0agc_step4_phase\0float\0\
agc_step5_phase\0float\0agc_step6_phase\0float\0agc_iq_amp_bal\0float\0agc_iq_phase_bal\0float\0\
spare181\0short\0spare182\0short\0spare183\0short\0spare184\0short\0spare185\0short\0\
spare186\0short\0spare187\0short\0spare188\0short\0spare189\0short\0spare190\0short\0\
spare191\0short\0spare192\0short\0spare193\0short\0spare194\0short\0spare195\0short\0\
spare196\0short\0spare197\0short\0spare198\0short\0spare199\0short\0spare200\0short\0\
cw_lin_tgt_exp_amp\0float\0rfd1_lin_tgt_exp_amp\0float\0rfd2_lin_tgt_exp_amp\0float\0\
rfd3_lin_tgt_exp_amp\0float\0cw_log_tgt_exp_amp\0float\0rfd1_log_tgt_exp_amp\0float\0\
rfd2_log_tgt_exp_amp\0float\0rfd3_log_tgt_exp_amp\0float\0cw_lin_tgt_mea_amp\0float\0\
rfd1_lin_tgt_mea_amp\0float\0rfd2_lin_tgt_mea_amp\0float\0rfd3_lin_tgt_mea_amp\0float\0\
cw_log_tgt_mea_amp\0float\0rfd1_log_tgt_mea_amp\0float\0rfd2_log_tgt_mea_amp\0float\0\
rfd3_log_tgt_mea_amp\0float\0short_pulse_lin_syscal\0float\0short_pulse_log_syscal\0float\0\
long_pulse_lin_syscal\0float\0long_pulse_log_syscal\0float\0phase_ram1_exp_vel\0float\0\
phase_ram2_exp_vel\0float\0phase_ram3_exp_vel\0float\0phase_ram4_exp_vel\0float\0\
phase_ram1_mea_vel\0float\0phase_ram2_mea_vel\0float\0phase_ram3_mea_vel\0float\0\
phase_ram4_mea_vel\0float\0phase_ram1_exp_wid\0float\0phase_ram2_exp_wid\0float\0\
phase_ram3_exp_wid\0float\0phase_ram4_exp_wid\0float\0phase_ram1_mea_wid\0float\0\
phase_ram2_mea_wid\0float\0phase_ram3_mea_wid\0float\0phase_ram4_mea_wid\0float\0\
spare273\0short\0spare274\0short\0spare275\0short\0spare276\0short\0spare277\0short\0\
spare278\0short\0spare279\0short\0spare280\0short\0spare281\0short\0spare282\0short\0\
spare283\0short\0spare284\0short\0spare285\0short\0spare286\0short\0spare287\0short\0\
spare288\0short\0spare289\0short\0spare290\0short\0kd1_lin_tgt_exp_amp\0float\0\
kd2_lin_tgt_exp_amp\0float\0kd3_lin_tgt_exp_amp\0float\0kd1_log_tgt_exp_amp\0float\0\
kd2_log_tgt_exp_amp\0float\0kd3_log_tgt_exp_amp\0float\0kd1_lin_tgt_mea_amp\0float\0\
kd2_lin_tgt_mea_amp\0float\0kd3_lin_tgt_mea_amp\0float\0kd1_log_tgt_mea_amp\0float\0\
kd2_log_tgt_mea_amp\0float\0kd3_log_tgt_mea_amp\0float\0spare315\0short\0\
spare316\0short\0spare317\0short\0spare318\0short\0spare319\0short\0spare320\0short\0\
spare321\0short\0spare322\0short\0spare323\0short\0spare324\0short\0spare325\0short\0\
spare326\0short\0spare327\0short\0spare328\0short\0spare329\0short\0spare330\0short\0\
clutter_check_t\0unfilt_lin_chan_pwr\0float\0filt_lin_chan_pwr\0float\0unfilt_log_chan_pwr\0float\0\
filt_log_chan_pwr\0float\0spare339\0short\0spare340\0short\0spare341\0short\0\
spare342\0short\0spare343\0short\0spare344\0short\0spare345\0short\0spare346\0short\0\
spare347\0short\0spare348\0short\0spare349\0short\0spare350\0short\0spare351\0short\0\
spare352\0short\0spare353\0short\0spare354\0short\0spare355\0short\0spare356\0short\0\
spare357\0short\0spare358\0short\0spare359\0short\0spare360\0short\0disk_file_status_t\0\
state_fil_rd_stat\0short\0state_fil_wr_stat\0short\0by_map_fil_rd_stat\0short\0\
by_map_fil_wr_stat\0short\0rdasc_cal_fil_rd_stat\0short\0rdasc_cal_fil_wr_stat\0short\0\
rdasot_cal_fil_rd_stat\0short\0mod_adap_fil_rd_stat\0short\0spare369\0short\0\
cen_zone_fil_rd_stat\0short\0cen_zone_fil_wr_stat\0short\0rem_vcp_fil_wr_stat\0short\0\
rem_vcp_fil_rd_stat\0short\0spare374\0short\0spare375\0short\0spare376\0short\0\
spare377\0short\0spare378\0short\0spare379\0short\0spare380\0short\0spare381\0short\0\
spare382\0short\0spare383\0short\0spare384\0short\0spare385\0short\0spare386\0short\0\
spare387\0short\0spare388\0short\0spare389\0short\0spare390\0short\0spare391\0short\0\
spare392\0short\0spare393\0short\0spare394\0short\0spare395\0short\0spare396\0short\0\
spare397\0short\0spare398\0short\0spare399\0short\0spare400\0short\0device_init_t\0\
dau_init_stat\0short\0maint_con_init_stat\0short\0ped_init_stat\0short\0self_tst1_stat\0short\0\
self_tst2_stat\0short\0self_tst2_data\0short\0sps_init_stat\0short\0sps_download_stat\0short\0\
sps_dim_loop_stat\0short\0sps_smi_loop_stat\0short\0sps_hsp_loop_stat\0short\0\
rpg_link_init_stat\0short\0user_link_init_stat\0short\0spare414\0short\0spare415\0short\0\
spare416\0short\0spare417\0short\0spare418\0short\0spare419\0short\0spare420\0short\0\
spare421\0short\0spare422\0short\0spare423\0short\0spare424\0short\0spare425\0short\0\
spare426\0short\0spare427\0short\0spare428\0short\0spare429\0short\0spare430\0short\0\
device_io_error_t\0dau_io_err_stat\0int\0dau_io_err_date\0int\0dau_io_err_time\0char\0\
mc_io_err_stat\0int\0mc_io_err_date\0int\0mc_io_err_time\0char\0ped_io_err_stat\0int\0\
ped_io_err_date\0int\0ped_io_err_time\0char\0sps_io_err_stat\0int\0sps_io_err_date\0int\0\
sps_io_err_time\0char\0arch2_io_err_stat\0int\0arch2_io_err_date\0int\0arch2_io_err_time\0char\0\
disk_io_err_stat\0int\0disk_io_err_date\0int\0disk_io_err_time\0char\0arch2_sum_err_stat\0int\0\
red_chan_io_err_stat\0int\0red_chan_io_err_date\0int\0red_chan_io_err_time\0char\0\
spare487\0short\0spare488\0short\0spare489\0short\0spare490\0short\0spare491\0short\0\
spare492\0short\0spare493\0short\0spare494\0short\0spare495\0short\0spare496\0short\0\
spare497\0short\0spare498\0short\0spare499\0short\0spare500\0short\0"
;

static const int All_ints[] = {
 sizeof (rda_performance_t), 29, 0, 1, sizeof (RDA_RPG_message_header_t),
 1, sizeof (wideband_t), 1, sizeof (wideband_t), 1, sizeof (bitdata_t), 1, sizeof (calibration_t),
 1, sizeof (clutter_check_t), 1, sizeof (disk_file_status_t), 1, sizeof (device_init_t),
 1, sizeof (device_io_error_t), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), sizeof (RDA_RPG_console_message_t), 3, 0, 1, sizeof (RDA_RPG_message_header_t),
 1, sizeof (short), 404, sizeof (char), sizeof (struct alg_cpu_stats), 5, 0,
 1, sizeof (unsigned int), 1, sizeof (int), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), sizeof (Pd_request_products), 10, 0, 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (int),
 6, sizeof (short), sizeof (msg_header), 9, 0, 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), sizeof (RPS_block), 11, 0,
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 6, sizeof (short), sizeof (Pd_alert_category_def_msg), 3, 0,
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), sizeof (Pd_alert_box_msg), 4, 0,
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 sizeof (alert_area_t), 4, 0, 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), sizeof (bias_table_msg_base_t), 15, 0, 4, sizeof (char),
 4, sizeof (char), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), sizeof (Block_id_t), 4, 0, 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), sizeof (Memory_span_t), 10, 0,
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), sizeof (RDA_RPG_message_header_t), 8, 0,
 1, sizeof (short), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (short), 1, sizeof (unsigned short), 1, sizeof (int), 1, sizeof (short),
 1, sizeof (short), sizeof (wideband_t), 15, 0, 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (unsigned short), 1, sizeof (unsigned short),
 1, sizeof (unsigned short), 1, sizeof (unsigned short), 1, sizeof (short),
 1, sizeof (unsigned short), 1, sizeof (unsigned short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 sizeof (bitdata_t), 135, 0, 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (unsigned char), 1, sizeof (unsigned char), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (unsigned char), 1, sizeof (unsigned char),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (unsigned short), 1, sizeof (unsigned short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (int), 1, sizeof (short), 1, sizeof (short), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (short), 1, sizeof (short), sizeof (calibration_t), 116, 0, 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), sizeof (clutter_check_t), 26, 0,
 1, sizeof (float), 1, sizeof (float), 1, sizeof (float), 1, sizeof (float),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), sizeof (disk_file_status_t), 40, 0,
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 sizeof (device_init_t), 30, 0, 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), sizeof (device_io_error_t), 36, 0,
 1, sizeof (int), 1, sizeof (int), 8, sizeof (char), 1, sizeof (int), 1, sizeof (int),
 8, sizeof (char), 1, sizeof (int), 1, sizeof (int), 8, sizeof (char), 1, sizeof (int),
 1, sizeof (int), 8, sizeof (char), 1, sizeof (int), 1, sizeof (int), 8, sizeof (char),
 1, sizeof (int), 1, sizeof (int), 8, sizeof (char), 1, sizeof (int), 1, sizeof (int),
 1, sizeof (int), 8, sizeof (char), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short),
 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 1, sizeof (short), 
};

static const int All_offs[] = {
 0, 0, 557, 61, 640, 70, 752, 83, 929, 106, 1109, 127, 1313, 152, 1395, 161,
 1448, 172, 1528, 183, 1755, 216, 1822, 227, 2018, 250, 2191, 269, 2551, 302,
 5203, 575, 7573, 810, 8019, 865, 8774, 948, 9339, 1011 
};

/*** Initializes the SMI struct at offset "off" */

static SMI_info_t *Smi_init (int off) {
    SMI_info_t *mi;
    const char *name;
    const int *ip;
    int n_fields, i;
    SMI_field_t *flds;

    name = All_names + All_offs[off];
    ip = All_ints + All_offs[off + 1];
    n_fields = ip[1];
    while ((mi = (SMI_info_t *)malloc 
	(sizeof (SMI_info_t) + n_fields * sizeof (SMI_field_t))) == NULL)
	sleep (1);
    mi->name = (char *)name;
    name += strlen (name) + 1;
    mi->size = *ip;
    ip++;
    mi->n_fields = n_fields;
    ip++;
    mi->n_vsfs = *ip;
    ip++;
    flds = (SMI_field_t *)((char *)mi + sizeof (SMI_info_t));
    mi->fields = flds;
    mi->ci = NULL;

    for (i = 0; i < n_fields; i++) {
	flds[i].name = (char *)name;
	name += strlen (name) + 1;
	flds[i].type = (char *)name;
	name += strlen (name) + 1;
	flds[i].n_items = *ip;
	ip++;
	flds[i].size = *ip;
	ip++;
	flds[i].offset = 0;
	flds[i].ci = NULL;
    }
    return (mi);
}

/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_performance_maintenance.h started at line 841 ***/

static SMI_info_t *rda_performance_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 0;
    SMI_field_t *fmi;
    rda_performance_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->msg_hdr) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->rpg) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->user) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->data) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->calibration) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->clutter_check) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->disk_status) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->device_init) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->device_error) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->interproc_chan_resp) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->spare502) - (char *)tmp;
    fmi[11].offset = (char *)&(tmp->chan_in_cntrl) - (char *)tmp;
    fmi[12].offset = (char *)&(tmp->spare504) - (char *)tmp;
    fmi[13].offset = (char *)&(tmp->spare505) - (char *)tmp;
    fmi[14].offset = (char *)&(tmp->spare506) - (char *)tmp;
    fmi[15].offset = (char *)&(tmp->spare507) - (char *)tmp;
    fmi[16].offset = (char *)&(tmp->spare508) - (char *)tmp;
    fmi[17].offset = (char *)&(tmp->spare509) - (char *)tmp;
    fmi[18].offset = (char *)&(tmp->spare510) - (char *)tmp;
    fmi[19].offset = (char *)&(tmp->spare511) - (char *)tmp;
    fmi[20].offset = (char *)&(tmp->spare512) - (char *)tmp;
    fmi[21].offset = (char *)&(tmp->spare513) - (char *)tmp;
    fmi[22].offset = (char *)&(tmp->spare514) - (char *)tmp;
    fmi[23].offset = (char *)&(tmp->spare515) - (char *)tmp;
    fmi[24].offset = (char *)&(tmp->spare516) - (char *)tmp;
    fmi[25].offset = (char *)&(tmp->spare517) - (char *)tmp;
    fmi[26].offset = (char *)&(tmp->spare518) - (char *)tmp;
    fmi[27].offset = (char *)&(tmp->spare519) - (char *)tmp;
    fmi[28].offset = (char *)&(tmp->spare520) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_rpg_console_message.h started at line 27 ***/

static SMI_info_t *RDA_RPG_console_message_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 2;
    SMI_field_t *fmi;
    RDA_RPG_console_message_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->msg_hdr) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->size) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->message) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/alg_cpu_stats.h started at line 14 ***/

static SMI_info_t *struct_alg_cpu_stats_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 4;
    SMI_field_t *fmi;
    struct alg_cpu_stats *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->vol_scan_num) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->elev_cnt) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->total_cpu) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->avg_cpu) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->avg_cpu_percent) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     ./prod_user_msg.h started at line 298 ***/

static SMI_info_t *Pd_request_products_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 6;
    SMI_field_t *fmi;
    Pd_request_products *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->divider) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->length) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->prod_id) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->flag_bits) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->seq_number) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->num_products) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->req_interval) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->VS_date) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->VS_start_time) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->params) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     ./nbtcp.h started at line 78 ***/

static SMI_info_t *msg_header_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 8;
    SMI_field_t *fmi;
    msg_header *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->msgcode) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->date_of_msg) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->time_of_msg_msw) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->time_of_msg_lsw) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->length_of_msg_msw) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->length_of_msg_lsw) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->src_id) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->dst_id) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->no_of_blocks) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     ./nbtcp.h started at line 90 ***/

static SMI_info_t *RPS_block_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 10;
    SMI_field_t *fmi;
    RPS_block *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->divider) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->length_of_blk) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->prod_code) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->flag) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->seq_no) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->no_of_prods) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->req_intrvl) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->vol_scan_date) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->vol_scan_time_msw) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->vol_scan_time_lsw) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->prod_parms) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     ./prod_user_msg.h started at line 397 ***/

static SMI_info_t *Pd_alert_category_def_msg_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 12;
    SMI_field_t *fmi;
    Pd_alert_category_def_msg *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->alert_category) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->thd_code) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->prod_req_flag) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     ./prod_user_msg.h started at line 403 ***/

static SMI_info_t *Pd_alert_box_msg_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 14;
    SMI_field_t *fmi;
    Pd_alert_box_msg *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->b1) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->b2) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->b3) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->b4) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     ./nbtcp.h started at line 119 ***/

static SMI_info_t *alert_area_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 16;
    SMI_field_t *fmi;
    alert_area_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->divider) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->length) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->alert_area_num) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->num_category) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     ./nbtcp.h started at line 126 ***/

static SMI_info_t *bias_table_msg_base_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 18;
    SMI_field_t *fmi;
    bias_table_msg_base_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->awips_id) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->radar_id) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->obs_yr) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->obs_mon) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->obs_day) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->obs_hr) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->obs_min) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->obs_sec) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->gen_yr) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->gen_mon) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->gen_day) - (char *)tmp;
    fmi[11].offset = (char *)&(tmp->gen_hr) - (char *)tmp;
    fmi[12].offset = (char *)&(tmp->gen_min) - (char *)tmp;
    fmi[13].offset = (char *)&(tmp->gen_sec) - (char *)tmp;
    fmi[14].offset = (char *)&(tmp->n_rows) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     ./prod_user_msg.h started at line 453 ***/

static SMI_info_t *Block_id_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 20;
    SMI_field_t *fmi;
    Block_id_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->divider) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->block_id) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->version) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->length) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     ./prod_user_msg.h started at line 463 ***/

static SMI_info_t *Memory_span_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 22;
    SMI_field_t *fmi;
    Memory_span_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->mem_span_msw) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->mem_span_lsw) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->n_pairs_msw) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->n_pairs_lsw) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->avg_gage_msw) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->avg_gage_lsw) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->avg_radar_msw) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->avg_radar_lsw) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->bias_msw) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->bias_lsw) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_rpg_message_header.h started at line 37 ***/

static SMI_info_t *RDA_RPG_message_header_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 24;
    SMI_field_t *fmi;
    RDA_RPG_message_header_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->size) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->rda_channel) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->type) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->sequence_num) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->julian_date) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->milliseconds) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->num_segs) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->seg_num) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_performance_maintenance.h started at line 24 ***/

static SMI_info_t *wideband_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 26;
    SMI_field_t *fmi;
    wideband_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->dcu_status) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->general_error) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->svc_15_error) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->outgoing_frames) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->frames_fcs_errors) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->retrans_i_frames) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->polls_sent_recvd) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->poll_timeout_exp) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->min_buf_read_pool) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->max_buf_read_done) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->loopback_test) - (char *)tmp;
    fmi[11].offset = (char *)&(tmp->spare12) - (char *)tmp;
    fmi[12].offset = (char *)&(tmp->spare13) - (char *)tmp;
    fmi[13].offset = (char *)&(tmp->spare14) - (char *)tmp;
    fmi[14].offset = (char *)&(tmp->spare15) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_performance_maintenance.h started at line 337 ***/

static SMI_info_t *bitdata_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 28;
    SMI_field_t *fmi;
    bitdata_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->data31) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->data32) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->data33) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->data34) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->data35) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->data36) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->data37) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->out_temp) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->eqp_shelt_temp) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->ac1_air_temp) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->trans_air_temp) - (char *)tmp;
    fmi[11].offset = (char *)&(tmp->radome_air_temp) - (char *)tmp;
    fmi[12].offset = (char *)&(tmp->gen_shelt_temp) - (char *)tmp;
    fmi[13].offset = (char *)&(tmp->gen_fuel_level) - (char *)tmp;
    fmi[14].offset = (char *)&(tmp->spare41l) - (char *)tmp;
    fmi[15].offset = (char *)&(tmp->spare42h) - (char *)tmp;
    fmi[16].offset = (char *)&(tmp->spare42l) - (char *)tmp;
    fmi[17].offset = (char *)&(tmp->spare43h) - (char *)tmp;
    fmi[18].offset = (char *)&(tmp->spare43l) - (char *)tmp;
    fmi[19].offset = (char *)&(tmp->spare44h) - (char *)tmp;
    fmi[20].offset = (char *)&(tmp->spare44l) - (char *)tmp;
    fmi[21].offset = (char *)&(tmp->ac2_air_temp) - (char *)tmp;
    fmi[22].offset = (char *)&(tmp->spare45l) - (char *)tmp;
    fmi[23].offset = (char *)&(tmp->spare46h) - (char *)tmp;
    fmi[24].offset = (char *)&(tmp->xmtr_rf_pwr) - (char *)tmp;
    fmi[25].offset = (char *)&(tmp->ant_rf_pwr) - (char *)tmp;
    fmi[26].offset = (char *)&(tmp->spare47l) - (char *)tmp;
    fmi[27].offset = (char *)&(tmp->spare48h) - (char *)tmp;
    fmi[28].offset = (char *)&(tmp->spare48l) - (char *)tmp;
    fmi[29].offset = (char *)&(tmp->spare49h) - (char *)tmp;
    fmi[30].offset = (char *)&(tmp->ped_p28v_ps) - (char *)tmp;
    fmi[31].offset = (char *)&(tmp->enc_p5v_ps) - (char *)tmp;
    fmi[32].offset = (char *)&(tmp->ped_p15v_ps) - (char *)tmp;
    fmi[33].offset = (char *)&(tmp->spare51h) - (char *)tmp;
    fmi[34].offset = (char *)&(tmp->ped_p5v_ps) - (char *)tmp;
    fmi[35].offset = (char *)&(tmp->spare52h) - (char *)tmp;
    fmi[36].offset = (char *)&(tmp->spare52l) - (char *)tmp;
    fmi[37].offset = (char *)&(tmp->sig_proc_p5v_ps) - (char *)tmp;
    fmi[38].offset = (char *)&(tmp->spare53l) - (char *)tmp;
    fmi[39].offset = (char *)&(tmp->mnt_con_p28v_ps) - (char *)tmp;
    fmi[40].offset = (char *)&(tmp->mnt_con_p15v_ps) - (char *)tmp;
    fmi[41].offset = (char *)&(tmp->mnt_con_p5v_ps) - (char *)tmp;
    fmi[42].offset = (char *)&(tmp->spare55l) - (char *)tmp;
    fmi[43].offset = (char *)&(tmp->spare56h) - (char *)tmp;
    fmi[44].offset = (char *)&(tmp->spare56l) - (char *)tmp;
    fmi[45].offset = (char *)&(tmp->ped_n15v_ps) - (char *)tmp;
    fmi[46].offset = (char *)&(tmp->spare57l) - (char *)tmp;
    fmi[47].offset = (char *)&(tmp->spare58h) - (char *)tmp;
    fmi[48].offset = (char *)&(tmp->mnt_con_n15v_ps) - (char *)tmp;
    fmi[49].offset = (char *)&(tmp->spare59h) - (char *)tmp;
    fmi[50].offset = (char *)&(tmp->dau_test0) - (char *)tmp;
    fmi[51].offset = (char *)&(tmp->dau_test1) - (char *)tmp;
    fmi[52].offset = (char *)&(tmp->dau_test2) - (char *)tmp;
    fmi[53].offset = (char *)&(tmp->spare61h) - (char *)tmp;
    fmi[54].offset = (char *)&(tmp->spare61l) - (char *)tmp;
    fmi[55].offset = (char *)&(tmp->dau_interface) - (char *)tmp;
    fmi[56].offset = (char *)&(tmp->xmtr_sum_stat) - (char *)tmp;
    fmi[57].offset = (char *)&(tmp->spare64) - (char *)tmp;
    fmi[58].offset = (char *)&(tmp->spare65) - (char *)tmp;
    fmi[59].offset = (char *)&(tmp->spare66) - (char *)tmp;
    fmi[60].offset = (char *)&(tmp->spare67) - (char *)tmp;
    fmi[61].offset = (char *)&(tmp->spare68) - (char *)tmp;
    fmi[62].offset = (char *)&(tmp->spare69) - (char *)tmp;
    fmi[63].offset = (char *)&(tmp->spare70) - (char *)tmp;
    fmi[64].offset = (char *)&(tmp->spare71) - (char *)tmp;
    fmi[65].offset = (char *)&(tmp->spare72) - (char *)tmp;
    fmi[66].offset = (char *)&(tmp->spare73) - (char *)tmp;
    fmi[67].offset = (char *)&(tmp->spare74) - (char *)tmp;
    fmi[68].offset = (char *)&(tmp->spare75) - (char *)tmp;
    fmi[69].offset = (char *)&(tmp->spare76) - (char *)tmp;
    fmi[70].offset = (char *)&(tmp->spare77) - (char *)tmp;
    fmi[71].offset = (char *)&(tmp->spare78) - (char *)tmp;
    fmi[72].offset = (char *)&(tmp->spare79) - (char *)tmp;
    fmi[73].offset = (char *)&(tmp->spare80) - (char *)tmp;
    fmi[74].offset = (char *)&(tmp->spare81) - (char *)tmp;
    fmi[75].offset = (char *)&(tmp->spare82) - (char *)tmp;
    fmi[76].offset = (char *)&(tmp->spare83) - (char *)tmp;
    fmi[77].offset = (char *)&(tmp->spare84) - (char *)tmp;
    fmi[78].offset = (char *)&(tmp->spare85) - (char *)tmp;
    fmi[79].offset = (char *)&(tmp->spare86) - (char *)tmp;
    fmi[80].offset = (char *)&(tmp->spare87) - (char *)tmp;
    fmi[81].offset = (char *)&(tmp->spare88) - (char *)tmp;
    fmi[82].offset = (char *)&(tmp->spare89) - (char *)tmp;
    fmi[83].offset = (char *)&(tmp->spare90) - (char *)tmp;
    fmi[84].offset = (char *)&(tmp->spare91) - (char *)tmp;
    fmi[85].offset = (char *)&(tmp->spare92) - (char *)tmp;
    fmi[86].offset = (char *)&(tmp->spare93) - (char *)tmp;
    fmi[87].offset = (char *)&(tmp->spare94) - (char *)tmp;
    fmi[88].offset = (char *)&(tmp->spare95) - (char *)tmp;
    fmi[89].offset = (char *)&(tmp->data96) - (char *)tmp;
    fmi[90].offset = (char *)&(tmp->data97) - (char *)tmp;
    fmi[91].offset = (char *)&(tmp->data98) - (char *)tmp;
    fmi[92].offset = (char *)&(tmp->az_pos_corr) - (char *)tmp;
    fmi[93].offset = (char *)&(tmp->el_pos_corr) - (char *)tmp;
    fmi[94].offset = (char *)&(tmp->spare101) - (char *)tmp;
    fmi[95].offset = (char *)&(tmp->spare102) - (char *)tmp;
    fmi[96].offset = (char *)&(tmp->spare103) - (char *)tmp;
    fmi[97].offset = (char *)&(tmp->spare104) - (char *)tmp;
    fmi[98].offset = (char *)&(tmp->spare105) - (char *)tmp;
    fmi[99].offset = (char *)&(tmp->spare106h) - (char *)tmp;
    fmi[100].offset = (char *)&(tmp->rf_gen_data) - (char *)tmp;
    fmi[101].offset = (char *)&(tmp->spare107) - (char *)tmp;
    fmi[102].offset = (char *)&(tmp->spare108) - (char *)tmp;
    fmi[103].offset = (char *)&(tmp->spare109h) - (char *)tmp;
    fmi[104].offset = (char *)&(tmp->parity_alrm_cf) - (char *)tmp;
    fmi[105].offset = (char *)&(tmp->spare110) - (char *)tmp;
    fmi[106].offset = (char *)&(tmp->spare111) - (char *)tmp;
    fmi[107].offset = (char *)&(tmp->prt1_int) - (char *)tmp;
    fmi[108].offset = (char *)&(tmp->prt2_int) - (char *)tmp;
    fmi[109].offset = (char *)&(tmp->spare114) - (char *)tmp;
    fmi[110].offset = (char *)&(tmp->spare115) - (char *)tmp;
    fmi[111].offset = (char *)&(tmp->spare116) - (char *)tmp;
    fmi[112].offset = (char *)&(tmp->spare117) - (char *)tmp;
    fmi[113].offset = (char *)&(tmp->spare118) - (char *)tmp;
    fmi[114].offset = (char *)&(tmp->spare119) - (char *)tmp;
    fmi[115].offset = (char *)&(tmp->spare120) - (char *)tmp;
    fmi[116].offset = (char *)&(tmp->spare121) - (char *)tmp;
    fmi[117].offset = (char *)&(tmp->spare122) - (char *)tmp;
    fmi[118].offset = (char *)&(tmp->ant_pk_pwr) - (char *)tmp;
    fmi[119].offset = (char *)&(tmp->xmtr_pk_pwr) - (char *)tmp;
    fmi[120].offset = (char *)&(tmp->ant_rf_ave_pwr) - (char *)tmp;
    fmi[121].offset = (char *)&(tmp->xmtr_rf_ave_pwr) - (char *)tmp;
    fmi[122].offset = (char *)&(tmp->mwave_loss) - (char *)tmp;
    fmi[123].offset = (char *)&(tmp->ant_pwr_mtr_zero) - (char *)tmp;
    fmi[124].offset = (char *)&(tmp->xmtr_pwr_mtr_zero) - (char *)tmp;
    fmi[125].offset = (char *)&(tmp->xmtr_rec_cnt) - (char *)tmp;
    fmi[126].offset = (char *)&(tmp->spare139) - (char *)tmp;
    fmi[127].offset = (char *)&(tmp->spare140) - (char *)tmp;
    fmi[128].offset = (char *)&(tmp->sh_pulse_lin_chan_noise) - (char *)tmp;
    fmi[129].offset = (char *)&(tmp->sh_pulse_log_chan_noise) - (char *)tmp;
    fmi[130].offset = (char *)&(tmp->lo_pulse_lin_chan_noise) - (char *)tmp;
    fmi[131].offset = (char *)&(tmp->lo_pulse_log_chan_noise) - (char *)tmp;
    fmi[132].offset = (char *)&(tmp->system_noise_temp) - (char *)tmp;
    fmi[133].offset = (char *)&(tmp->idu_tst_detect) - (char *)tmp;
    fmi[134].offset = (char *)&(tmp->spare152) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_performance_maintenance.h started at line 62 ***/

static SMI_info_t *calibration_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 30;
    SMI_field_t *fmi;
    calibration_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->agc_step1_amp) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->agc_step2_amp) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->agc_step3_amp) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->agc_step4_amp) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->agc_step5_amp) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->agc_step6_amp) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->agc_step1_phase) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->agc_step2_phase) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->agc_step3_phase) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->agc_step4_phase) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->agc_step5_phase) - (char *)tmp;
    fmi[11].offset = (char *)&(tmp->agc_step6_phase) - (char *)tmp;
    fmi[12].offset = (char *)&(tmp->agc_iq_amp_bal) - (char *)tmp;
    fmi[13].offset = (char *)&(tmp->agc_iq_phase_bal) - (char *)tmp;
    fmi[14].offset = (char *)&(tmp->spare181) - (char *)tmp;
    fmi[15].offset = (char *)&(tmp->spare182) - (char *)tmp;
    fmi[16].offset = (char *)&(tmp->spare183) - (char *)tmp;
    fmi[17].offset = (char *)&(tmp->spare184) - (char *)tmp;
    fmi[18].offset = (char *)&(tmp->spare185) - (char *)tmp;
    fmi[19].offset = (char *)&(tmp->spare186) - (char *)tmp;
    fmi[20].offset = (char *)&(tmp->spare187) - (char *)tmp;
    fmi[21].offset = (char *)&(tmp->spare188) - (char *)tmp;
    fmi[22].offset = (char *)&(tmp->spare189) - (char *)tmp;
    fmi[23].offset = (char *)&(tmp->spare190) - (char *)tmp;
    fmi[24].offset = (char *)&(tmp->spare191) - (char *)tmp;
    fmi[25].offset = (char *)&(tmp->spare192) - (char *)tmp;
    fmi[26].offset = (char *)&(tmp->spare193) - (char *)tmp;
    fmi[27].offset = (char *)&(tmp->spare194) - (char *)tmp;
    fmi[28].offset = (char *)&(tmp->spare195) - (char *)tmp;
    fmi[29].offset = (char *)&(tmp->spare196) - (char *)tmp;
    fmi[30].offset = (char *)&(tmp->spare197) - (char *)tmp;
    fmi[31].offset = (char *)&(tmp->spare198) - (char *)tmp;
    fmi[32].offset = (char *)&(tmp->spare199) - (char *)tmp;
    fmi[33].offset = (char *)&(tmp->spare200) - (char *)tmp;
    fmi[34].offset = (char *)&(tmp->cw_lin_tgt_exp_amp) - (char *)tmp;
    fmi[35].offset = (char *)&(tmp->rfd1_lin_tgt_exp_amp) - (char *)tmp;
    fmi[36].offset = (char *)&(tmp->rfd2_lin_tgt_exp_amp) - (char *)tmp;
    fmi[37].offset = (char *)&(tmp->rfd3_lin_tgt_exp_amp) - (char *)tmp;
    fmi[38].offset = (char *)&(tmp->cw_log_tgt_exp_amp) - (char *)tmp;
    fmi[39].offset = (char *)&(tmp->rfd1_log_tgt_exp_amp) - (char *)tmp;
    fmi[40].offset = (char *)&(tmp->rfd2_log_tgt_exp_amp) - (char *)tmp;
    fmi[41].offset = (char *)&(tmp->rfd3_log_tgt_exp_amp) - (char *)tmp;
    fmi[42].offset = (char *)&(tmp->cw_lin_tgt_mea_amp) - (char *)tmp;
    fmi[43].offset = (char *)&(tmp->rfd1_lin_tgt_mea_amp) - (char *)tmp;
    fmi[44].offset = (char *)&(tmp->rfd2_lin_tgt_mea_amp) - (char *)tmp;
    fmi[45].offset = (char *)&(tmp->rfd3_lin_tgt_mea_amp) - (char *)tmp;
    fmi[46].offset = (char *)&(tmp->cw_log_tgt_mea_amp) - (char *)tmp;
    fmi[47].offset = (char *)&(tmp->rfd1_log_tgt_mea_amp) - (char *)tmp;
    fmi[48].offset = (char *)&(tmp->rfd2_log_tgt_mea_amp) - (char *)tmp;
    fmi[49].offset = (char *)&(tmp->rfd3_log_tgt_mea_amp) - (char *)tmp;
    fmi[50].offset = (char *)&(tmp->short_pulse_lin_syscal) - (char *)tmp;
    fmi[51].offset = (char *)&(tmp->short_pulse_log_syscal) - (char *)tmp;
    fmi[52].offset = (char *)&(tmp->long_pulse_lin_syscal) - (char *)tmp;
    fmi[53].offset = (char *)&(tmp->long_pulse_log_syscal) - (char *)tmp;
    fmi[54].offset = (char *)&(tmp->phase_ram1_exp_vel) - (char *)tmp;
    fmi[55].offset = (char *)&(tmp->phase_ram2_exp_vel) - (char *)tmp;
    fmi[56].offset = (char *)&(tmp->phase_ram3_exp_vel) - (char *)tmp;
    fmi[57].offset = (char *)&(tmp->phase_ram4_exp_vel) - (char *)tmp;
    fmi[58].offset = (char *)&(tmp->phase_ram1_mea_vel) - (char *)tmp;
    fmi[59].offset = (char *)&(tmp->phase_ram2_mea_vel) - (char *)tmp;
    fmi[60].offset = (char *)&(tmp->phase_ram3_mea_vel) - (char *)tmp;
    fmi[61].offset = (char *)&(tmp->phase_ram4_mea_vel) - (char *)tmp;
    fmi[62].offset = (char *)&(tmp->phase_ram1_exp_wid) - (char *)tmp;
    fmi[63].offset = (char *)&(tmp->phase_ram2_exp_wid) - (char *)tmp;
    fmi[64].offset = (char *)&(tmp->phase_ram3_exp_wid) - (char *)tmp;
    fmi[65].offset = (char *)&(tmp->phase_ram4_exp_wid) - (char *)tmp;
    fmi[66].offset = (char *)&(tmp->phase_ram1_mea_wid) - (char *)tmp;
    fmi[67].offset = (char *)&(tmp->phase_ram2_mea_wid) - (char *)tmp;
    fmi[68].offset = (char *)&(tmp->phase_ram3_mea_wid) - (char *)tmp;
    fmi[69].offset = (char *)&(tmp->phase_ram4_mea_wid) - (char *)tmp;
    fmi[70].offset = (char *)&(tmp->spare273) - (char *)tmp;
    fmi[71].offset = (char *)&(tmp->spare274) - (char *)tmp;
    fmi[72].offset = (char *)&(tmp->spare275) - (char *)tmp;
    fmi[73].offset = (char *)&(tmp->spare276) - (char *)tmp;
    fmi[74].offset = (char *)&(tmp->spare277) - (char *)tmp;
    fmi[75].offset = (char *)&(tmp->spare278) - (char *)tmp;
    fmi[76].offset = (char *)&(tmp->spare279) - (char *)tmp;
    fmi[77].offset = (char *)&(tmp->spare280) - (char *)tmp;
    fmi[78].offset = (char *)&(tmp->spare281) - (char *)tmp;
    fmi[79].offset = (char *)&(tmp->spare282) - (char *)tmp;
    fmi[80].offset = (char *)&(tmp->spare283) - (char *)tmp;
    fmi[81].offset = (char *)&(tmp->spare284) - (char *)tmp;
    fmi[82].offset = (char *)&(tmp->spare285) - (char *)tmp;
    fmi[83].offset = (char *)&(tmp->spare286) - (char *)tmp;
    fmi[84].offset = (char *)&(tmp->spare287) - (char *)tmp;
    fmi[85].offset = (char *)&(tmp->spare288) - (char *)tmp;
    fmi[86].offset = (char *)&(tmp->spare289) - (char *)tmp;
    fmi[87].offset = (char *)&(tmp->spare290) - (char *)tmp;
    fmi[88].offset = (char *)&(tmp->kd1_lin_tgt_exp_amp) - (char *)tmp;
    fmi[89].offset = (char *)&(tmp->kd2_lin_tgt_exp_amp) - (char *)tmp;
    fmi[90].offset = (char *)&(tmp->kd3_lin_tgt_exp_amp) - (char *)tmp;
    fmi[91].offset = (char *)&(tmp->kd1_log_tgt_exp_amp) - (char *)tmp;
    fmi[92].offset = (char *)&(tmp->kd2_log_tgt_exp_amp) - (char *)tmp;
    fmi[93].offset = (char *)&(tmp->kd3_log_tgt_exp_amp) - (char *)tmp;
    fmi[94].offset = (char *)&(tmp->kd1_lin_tgt_mea_amp) - (char *)tmp;
    fmi[95].offset = (char *)&(tmp->kd2_lin_tgt_mea_amp) - (char *)tmp;
    fmi[96].offset = (char *)&(tmp->kd3_lin_tgt_mea_amp) - (char *)tmp;
    fmi[97].offset = (char *)&(tmp->kd1_log_tgt_mea_amp) - (char *)tmp;
    fmi[98].offset = (char *)&(tmp->kd2_log_tgt_mea_amp) - (char *)tmp;
    fmi[99].offset = (char *)&(tmp->kd3_log_tgt_mea_amp) - (char *)tmp;
    fmi[100].offset = (char *)&(tmp->spare315) - (char *)tmp;
    fmi[101].offset = (char *)&(tmp->spare316) - (char *)tmp;
    fmi[102].offset = (char *)&(tmp->spare317) - (char *)tmp;
    fmi[103].offset = (char *)&(tmp->spare318) - (char *)tmp;
    fmi[104].offset = (char *)&(tmp->spare319) - (char *)tmp;
    fmi[105].offset = (char *)&(tmp->spare320) - (char *)tmp;
    fmi[106].offset = (char *)&(tmp->spare321) - (char *)tmp;
    fmi[107].offset = (char *)&(tmp->spare322) - (char *)tmp;
    fmi[108].offset = (char *)&(tmp->spare323) - (char *)tmp;
    fmi[109].offset = (char *)&(tmp->spare324) - (char *)tmp;
    fmi[110].offset = (char *)&(tmp->spare325) - (char *)tmp;
    fmi[111].offset = (char *)&(tmp->spare326) - (char *)tmp;
    fmi[112].offset = (char *)&(tmp->spare327) - (char *)tmp;
    fmi[113].offset = (char *)&(tmp->spare328) - (char *)tmp;
    fmi[114].offset = (char *)&(tmp->spare329) - (char *)tmp;
    fmi[115].offset = (char *)&(tmp->spare330) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_performance_maintenance.h started at line 183 ***/

static SMI_info_t *clutter_check_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 32;
    SMI_field_t *fmi;
    clutter_check_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->unfilt_lin_chan_pwr) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->filt_lin_chan_pwr) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->unfilt_log_chan_pwr) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->filt_log_chan_pwr) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->spare339) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->spare340) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->spare341) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->spare342) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->spare343) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->spare344) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->spare345) - (char *)tmp;
    fmi[11].offset = (char *)&(tmp->spare346) - (char *)tmp;
    fmi[12].offset = (char *)&(tmp->spare347) - (char *)tmp;
    fmi[13].offset = (char *)&(tmp->spare348) - (char *)tmp;
    fmi[14].offset = (char *)&(tmp->spare349) - (char *)tmp;
    fmi[15].offset = (char *)&(tmp->spare350) - (char *)tmp;
    fmi[16].offset = (char *)&(tmp->spare351) - (char *)tmp;
    fmi[17].offset = (char *)&(tmp->spare352) - (char *)tmp;
    fmi[18].offset = (char *)&(tmp->spare353) - (char *)tmp;
    fmi[19].offset = (char *)&(tmp->spare354) - (char *)tmp;
    fmi[20].offset = (char *)&(tmp->spare355) - (char *)tmp;
    fmi[21].offset = (char *)&(tmp->spare356) - (char *)tmp;
    fmi[22].offset = (char *)&(tmp->spare357) - (char *)tmp;
    fmi[23].offset = (char *)&(tmp->spare358) - (char *)tmp;
    fmi[24].offset = (char *)&(tmp->spare359) - (char *)tmp;
    fmi[25].offset = (char *)&(tmp->spare360) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_performance_maintenance.h started at line 214 ***/

static SMI_info_t *disk_file_status_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 34;
    SMI_field_t *fmi;
    disk_file_status_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->state_fil_rd_stat) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->state_fil_wr_stat) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->by_map_fil_rd_stat) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->by_map_fil_wr_stat) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->rdasc_cal_fil_rd_stat) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->rdasc_cal_fil_wr_stat) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->rdasot_cal_fil_rd_stat) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->mod_adap_fil_rd_stat) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->spare369) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->cen_zone_fil_rd_stat) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->cen_zone_fil_wr_stat) - (char *)tmp;
    fmi[11].offset = (char *)&(tmp->rem_vcp_fil_wr_stat) - (char *)tmp;
    fmi[12].offset = (char *)&(tmp->rem_vcp_fil_rd_stat) - (char *)tmp;
    fmi[13].offset = (char *)&(tmp->spare374) - (char *)tmp;
    fmi[14].offset = (char *)&(tmp->spare375) - (char *)tmp;
    fmi[15].offset = (char *)&(tmp->spare376) - (char *)tmp;
    fmi[16].offset = (char *)&(tmp->spare377) - (char *)tmp;
    fmi[17].offset = (char *)&(tmp->spare378) - (char *)tmp;
    fmi[18].offset = (char *)&(tmp->spare379) - (char *)tmp;
    fmi[19].offset = (char *)&(tmp->spare380) - (char *)tmp;
    fmi[20].offset = (char *)&(tmp->spare381) - (char *)tmp;
    fmi[21].offset = (char *)&(tmp->spare382) - (char *)tmp;
    fmi[22].offset = (char *)&(tmp->spare383) - (char *)tmp;
    fmi[23].offset = (char *)&(tmp->spare384) - (char *)tmp;
    fmi[24].offset = (char *)&(tmp->spare385) - (char *)tmp;
    fmi[25].offset = (char *)&(tmp->spare386) - (char *)tmp;
    fmi[26].offset = (char *)&(tmp->spare387) - (char *)tmp;
    fmi[27].offset = (char *)&(tmp->spare388) - (char *)tmp;
    fmi[28].offset = (char *)&(tmp->spare389) - (char *)tmp;
    fmi[29].offset = (char *)&(tmp->spare390) - (char *)tmp;
    fmi[30].offset = (char *)&(tmp->spare391) - (char *)tmp;
    fmi[31].offset = (char *)&(tmp->spare392) - (char *)tmp;
    fmi[32].offset = (char *)&(tmp->spare393) - (char *)tmp;
    fmi[33].offset = (char *)&(tmp->spare394) - (char *)tmp;
    fmi[34].offset = (char *)&(tmp->spare395) - (char *)tmp;
    fmi[35].offset = (char *)&(tmp->spare396) - (char *)tmp;
    fmi[36].offset = (char *)&(tmp->spare397) - (char *)tmp;
    fmi[37].offset = (char *)&(tmp->spare398) - (char *)tmp;
    fmi[38].offset = (char *)&(tmp->spare399) - (char *)tmp;
    fmi[39].offset = (char *)&(tmp->spare400) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_performance_maintenance.h started at line 259 ***/

static SMI_info_t *device_init_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 36;
    SMI_field_t *fmi;
    device_init_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->dau_init_stat) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->maint_con_init_stat) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->ped_init_stat) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->self_tst1_stat) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->self_tst2_stat) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->self_tst2_data) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->sps_init_stat) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->sps_download_stat) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->sps_dim_loop_stat) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->sps_smi_loop_stat) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->sps_hsp_loop_stat) - (char *)tmp;
    fmi[11].offset = (char *)&(tmp->rpg_link_init_stat) - (char *)tmp;
    fmi[12].offset = (char *)&(tmp->user_link_init_stat) - (char *)tmp;
    fmi[13].offset = (char *)&(tmp->spare414) - (char *)tmp;
    fmi[14].offset = (char *)&(tmp->spare415) - (char *)tmp;
    fmi[15].offset = (char *)&(tmp->spare416) - (char *)tmp;
    fmi[16].offset = (char *)&(tmp->spare417) - (char *)tmp;
    fmi[17].offset = (char *)&(tmp->spare418) - (char *)tmp;
    fmi[18].offset = (char *)&(tmp->spare419) - (char *)tmp;
    fmi[19].offset = (char *)&(tmp->spare420) - (char *)tmp;
    fmi[20].offset = (char *)&(tmp->spare421) - (char *)tmp;
    fmi[21].offset = (char *)&(tmp->spare422) - (char *)tmp;
    fmi[22].offset = (char *)&(tmp->spare423) - (char *)tmp;
    fmi[23].offset = (char *)&(tmp->spare424) - (char *)tmp;
    fmi[24].offset = (char *)&(tmp->spare425) - (char *)tmp;
    fmi[25].offset = (char *)&(tmp->spare426) - (char *)tmp;
    fmi[26].offset = (char *)&(tmp->spare427) - (char *)tmp;
    fmi[27].offset = (char *)&(tmp->spare428) - (char *)tmp;
    fmi[28].offset = (char *)&(tmp->spare429) - (char *)tmp;
    fmi[29].offset = (char *)&(tmp->spare430) - (char *)tmp;

    return (mi);
}


/*** The next function is generated using code in file
     /import/orpg/last_good_build/include/rda_performance_maintenance.h started at line 296 ***/

static SMI_info_t *device_io_error_t_info_ (void *dt) {
    static SMI_info_t *mi = NULL;
    static int off = 38;
    SMI_field_t *fmi;
    device_io_error_t *tmp = NULL;

    if (mi == NULL)
	mi = Smi_init (off);

    fmi = mi->fields;
    fmi[0].offset = (char *)&(tmp->dau_io_err_stat) - (char *)tmp;
    fmi[1].offset = (char *)&(tmp->dau_io_err_date) - (char *)tmp;
    fmi[2].offset = (char *)&(tmp->dau_io_err_time) - (char *)tmp;
    fmi[3].offset = (char *)&(tmp->mc_io_err_stat) - (char *)tmp;
    fmi[4].offset = (char *)&(tmp->mc_io_err_date) - (char *)tmp;
    fmi[5].offset = (char *)&(tmp->mc_io_err_time) - (char *)tmp;
    fmi[6].offset = (char *)&(tmp->ped_io_err_stat) - (char *)tmp;
    fmi[7].offset = (char *)&(tmp->ped_io_err_date) - (char *)tmp;
    fmi[8].offset = (char *)&(tmp->ped_io_err_time) - (char *)tmp;
    fmi[9].offset = (char *)&(tmp->sps_io_err_stat) - (char *)tmp;
    fmi[10].offset = (char *)&(tmp->sps_io_err_date) - (char *)tmp;
    fmi[11].offset = (char *)&(tmp->sps_io_err_time) - (char *)tmp;
    fmi[12].offset = (char *)&(tmp->arch2_io_err_stat) - (char *)tmp;
    fmi[13].offset = (char *)&(tmp->arch2_io_err_date) - (char *)tmp;
    fmi[14].offset = (char *)&(tmp->arch2_io_err_time) - (char *)tmp;
    fmi[15].offset = (char *)&(tmp->disk_io_err_stat) - (char *)tmp;
    fmi[16].offset = (char *)&(tmp->disk_io_err_date) - (char *)tmp;
    fmi[17].offset = (char *)&(tmp->disk_io_err_time) - (char *)tmp;
    fmi[18].offset = (char *)&(tmp->arch2_sum_err_stat) - (char *)tmp;
    fmi[19].offset = (char *)&(tmp->red_chan_io_err_stat) - (char *)tmp;
    fmi[20].offset = (char *)&(tmp->red_chan_io_err_date) - (char *)tmp;
    fmi[21].offset = (char *)&(tmp->red_chan_io_err_time) - (char *)tmp;
    fmi[22].offset = (char *)&(tmp->spare487) - (char *)tmp;
    fmi[23].offset = (char *)&(tmp->spare488) - (char *)tmp;
    fmi[24].offset = (char *)&(tmp->spare489) - (char *)tmp;
    fmi[25].offset = (char *)&(tmp->spare490) - (char *)tmp;
    fmi[26].offset = (char *)&(tmp->spare491) - (char *)tmp;
    fmi[27].offset = (char *)&(tmp->spare492) - (char *)tmp;
    fmi[28].offset = (char *)&(tmp->spare493) - (char *)tmp;
    fmi[29].offset = (char *)&(tmp->spare494) - (char *)tmp;
    fmi[30].offset = (char *)&(tmp->spare495) - (char *)tmp;
    fmi[31].offset = (char *)&(tmp->spare496) - (char *)tmp;
    fmi[32].offset = (char *)&(tmp->spare497) - (char *)tmp;
    fmi[33].offset = (char *)&(tmp->spare498) - (char *)tmp;
    fmi[34].offset = (char *)&(tmp->spare499) - (char *)tmp;
    fmi[35].offset = (char *)&(tmp->spare500) - (char *)tmp;

    return (mi);
}


SMI_info_t *SWAp_bytes (char *type_name, void *data) {
    static struct {
	SMI_info_t *(*func) (void *);
	char *name;
    } type_list [] = {
	{ Block_id_t_info_, "Block_id_t"},
	{ Memory_span_t_info_, "Memory_span_t"},
	{ Pd_alert_box_msg_info_, "Pd_alert_box_msg"},
	{ Pd_alert_category_def_msg_info_, "Pd_alert_category_def_msg"},
	{ Pd_request_products_info_, "Pd_request_products"},
	{ RDA_RPG_console_message_t_info_, "RDA_RPG_console_message_t"},
	{ RDA_RPG_message_header_t_info_, "RDA_RPG_message_header_t"},
	{ RPS_block_info_, "RPS_block"},
	{ alert_area_t_info_, "alert_area_t"},
	{ struct_alg_cpu_stats_info_, "alg_cpu_stats_t"},
	{ bias_table_msg_base_t_info_, "bias_table_msg_base_t"},
	{ bitdata_t_info_, "bitdata_t"},
	{ calibration_t_info_, "calibration_t"},
	{ clutter_check_t_info_, "clutter_check_t"},
	{ device_init_t_info_, "device_init_t"},
	{ device_io_error_t_info_, "device_io_error_t"},
	{ disk_file_status_t_info_, "disk_file_status_t"},
	{ msg_header_info_, "msg_header"},
	{ rda_performance_t_info_, "rda_performance_t"},
	{ wideband_t_info_, "wideband_t"},
    };
    static int n_types = 20;
    int st, end, ind, i;

    if (type_name == NULL) {
	if (data == NULL)
	    Need_byte_swap_data = 0;
	else
	    Need_byte_swap_data = 1;
	return (NULL);
    }
    /* binary search */
    st = 0;
    end = n_types - 1;
    ind = -1;
    while (1) {
	i = (st + end) >> 1;
	if (st == i) {
	    if (strcmp (type_name, type_list[st].name) == 0)
		ind = st;
	    else if (strcmp (type_name, type_list[end].name) == 0)
		ind = end;
	    break;
	}
	if (strcmp (type_name, type_list[i].name) <= 0)
	    end = i;
	else
	    st = i;
    }
    if (ind < 0)
	return (NULL);
    else 
	return (type_list[ind].func (data));
}

static int N_id_types = 3;

static const int Majors[] = {
 ORPGDAT_RDA_PERF_MAIN, ORPGDAT_RDA_CONSOLE_MSG, ORPGDAT_ALG_CPU_STATS,};

static const int Minors[] = {
 -1, -1, -1,};

static const char *Id_type_names[] = {
 "rda_performance_t", "RDA_RPG_console_message_t", "alg_cpu_stats_t",};

char *SWAp_bytes_type_by_id (int major, int minor) {    int ind, i;

    ind = -1;
    for (i = 0; i < N_id_types; i++) {
	if (Majors[i] == major) {
	    if (minor >= 0 && Minors[i] == minor)
		return ((char *)Id_type_names[i]);
	    if (Minors[i] < 0 && ind < 0) {
		ind = i;
		if (minor < 0)
		    break;
	    }
	}
    }
    if (ind >= 0)
	return ((char *)Id_type_names[ind]);
    return (NULL);
}

int SWAp_bytes_get_all_ids (int **major, int **minor, char ***type) {    *major = (int *)Majors;
    *minor = (int *)Minors;
    *type = (char **)Id_type_names;
    return (N_id_types);
}

