/********************************************************************************
     nbtcp_smipp.h - This file contains the structure and function declarations 
                     that need the byte swapping code generated by the SMI 
                     Pre-processor. File nbtcp_smipp.c is generated when the SMI
                     Pre-processor is executed on this file.
 ********************************************************************************/

/*
 * RCS info
 * $Author: garyg $
 * $Locker:  $
 * $Date: 2002/08/21 20:54:44 $
 * $Id: nbtcp_smipp.h,v 1.2 2002/08/21 20:54:44 garyg Exp $
 * $Revision: 1.2 $
 * $State: Exp $
 */

#ifndef NBTCP_SMI_H
#define NBTCP_SMI_H


#include <prod_user_msg.h>
#include <legacy_prod.h>
#include <nbtcp.h>



/****** SMI Structure Definitions ******/

/*     Product Request Message */

/* SMI_struct Pd_request_products; */  /* refer prod_user_msg.h */
/* SMI_struct msg_header; */
/* SMI_struct RPS_block; */

/*     Alert Request Msg */

/* SMI_struct Pd_alert_category_def_msg; */ /* refer prod_user_msg.h */
/* SMI_struct Pd_alert_box_msg; */          /* refer prod_user_msg.h */
/* SMI_struct alert_area_t; */

/*     Bias Table Msg */

/* SMI_struct bias_table_msg_base_t; */
/* SMI_struct Block_id_t; */      /* refer prod_user_msg.h */
/* SMI_struct Memory_span_t; */   /* refer prod_user_msg.h */



/****** SMI Function Definitions ******/


/* SMI_function SWAp_bytes; */

#endif
