1    19    R     Base Reflectivity: 16 level/0.54 nm                 UNU      UNU      5        UNU      UNU      UNU      
13   20    R     Base Reflectivity: 16 level/1.1 nm                  UNU      UNU      5        UNU      UNU      UNU      
37   28    SW    Base Spectrum Width: 8 level/0.13 nm                UNU      UNU      5        UNU      UNU      UNU      
49   30    SW    Base Spectrum Width: 8 level/0.54 nm                UNU      UNU      5        UNU      UNU      UNU      
79   27    V     Base Velocity: 16 level/0.54 nm                     UNU      UNU      5        UNU      UNU      UNU      
91   37    CR    Composite Reflectivity: 16 level/0.54 nm            UNU      UNU      UNU      UNU      UNU      UNU      
93   38    CR    Composite Reflectivity: 16 level/2.2 nm             UNU      UNU      UNU      UNU      UNU      UNU      
94   36    CR    Composite Reflectivity: 8 level/2.2 nm              UNU      UNU      UNU      UNU      UNU      UNU      
95   41    ET    Echo Tops: 16 level/2.2 nm                          UNU      UNU      UNU      UNU      UNU      UNU      
96   59    HI    Hail Index                                          UNU      UNU      UNU      UNU      UNU      UNU      
97   48    VWP   VAD Wind Profile                                    UNU      UNU      UNU      UNU      UNU      UNU      
100  65    LRM   Layer Composite Reflectivity (Layer 1 Maximum)      UNU      UNU      UNU      UNU      UNU      UNU      
101  66    LRM   Layer Composite Reflectivity (Layer 2 Maximum)      UNU      UNU      UNU      UNU      UNU      UNU      
102  67    APR   Layer Composite Reflectivity - AP Removed: 8 level  UNU      UNU      UNU      UNU      UNU      UNU      
103  62    SS    Storm Structure                                     UNU      UNU      UNU      UNU      UNU      UNU      
104  58    STI   Storm Tracking Information                          UNU      UNU      UNU      UNU      UNU      UNU      
106  32    DHR   Digital Hybrid Scan Reflectivity: 256 level/0.54 n  UNU      UNU      UNU      UNU      UNU      UNU      
108  56    SRM   Storm Relative Velocity (Map): 16 level/0.54 nm     UNU      UNU      5        -1       1800     UNU      
109  56    SRM   Storm Relative Velocity (Map): 16 level/0.54 nm     UNU      UNU      15       -1       1800     UNU      
110  56    SRM   Storm Relative Velocity (Map): 16 level/0.54 nm     UNU      UNU      24       -1       1800     UNU      
111  56    SRM   Storm Relative Velocity (Map): 16 level/0.54 nm     UNU      UNU      33       -1       1800     UNU      
120  61    TVS   Tornado Vortex Signature                            UNU      UNU      UNU      UNU      UNU      UNU      
123  57    VIL   Vertically Integrated Liquid: 16 level/2.2 nm       UNU      UNU      UNU      UNU      UNU      UNU      
130  94    DR    Base Reflectivity Data Array Product: 256 level/0.  UNU      UNU      5        UNU      UNU      UNU      
131  94    DR    Base Reflectivity Data Array Product: 256 level/0.  UNU      UNU      9        UNU      UNU      UNU      
132  94    DR    Base Reflectivity Data Array Product: 256 level/0.  UNU      UNU      13       UNU      UNU      UNU      
133  94    DR    Base Reflectivity Data Array Product: 256 level/0.  UNU      UNU      18       UNU      UNU      UNU      
134  94    DR    Base Reflectivity Data Array Product: 256 level/0.  UNU      UNU      25       UNU      UNU      UNU      
135  94    DR    Base Reflectivity Data Array Product: 256 level/0.  UNU      UNU      34       UNU      UNU      UNU      
135  94    DR    Base Reflectivity Data Array Product: 256 level/0.  UNU      UNU      16389    UNU      UNU      UNU      
136  99    DV    Base Velocity Data Array Product: 256 level/0.13 n  UNU      UNU      5        UNU      UNU      UNU      
137  99    DV    Base Velocity Data Array Product: 256 level/0.13 n  UNU      UNU      9        UNU      UNU      UNU      
138  99    DV    Base Velocity Data Array Product: 256 level/0.13 n  UNU      UNU      13       UNU      UNU      UNU      
139  99    DV    Base Velocity Data Array Product: 256 level/0.13 n  UNU      UNU      18       UNU      UNU      UNU      
140  99    DV    Base Velocity Data Array Product: 256 level/0.13 n  UNU      UNU      24       UNU      UNU      UNU      
141  99    DV    Base Velocity Data Array Product: 256 level/0.13 n  UNU      UNU      34       UNU      UNU      UNU      
141  99    DV    Base Velocity Data Array Product: 256 level/0.13 n  UNU      UNU      16389    UNU      UNU      UNU      
142  78    OHP   Surface Rainfall Accumulation (1 hr): 16 level/1.1  UNU      UNU      UNU      UNU      UNU      UNU      
143  79    THP   Surface Rainfall Accumulation (3 hr): 16 level/1.1  UNU      UNU      UNU      UNU      UNU      UNU      
144  80    STP   Storm Total Rainfall Accumulation: 16 level/1.1 nm  UNU      UNU      UNU      UNU      UNU      UNU      
145  81    DPA   Hourly Digital Precip Array: 256 level              UNU      UNU      UNU      UNU      UNU      UNU      
146  82    SPD   Supplemental Precipitation Data                     UNU      UNU      UNU      UNU      UNU      UNU      
151  90    LRM   Layer Composite Reflectivity (Layer 3 Maximum): 8   UNU      UNU      UNU      UNU      UNU      UNU      
152  34    CFC   Clutter Filter Control: 8 level/0.54 nm             0        UNU      UNU      UNU      UNU      UNU      
157  74    RCM   Radar Coded Message                                 UNU      UNU      UNU      UNU      UNU      UNU      
170  134   DVL   High Resolution Digital VIL: 256 level/0.54 nm      UNU      UNU      UNU      UNU      UNU      UNU      
171  135   EET   Enhanced Echo Tops: 71 level/0.54 nm                UNU      UNU      UNU      UNU      UNU      UNU      
174  138   DSP   Digital Storm Total Rainfall Accumulation: 256 lev  UNU      UNU      UNU      UNU      UNU      UNU      
176  141   MD    Mesocyclone Detection Product                       UNU      UNU      UNU      UNU      UNU      UNU      
231  159   DZD   Differential Reflectivity Data Array Product: 256   UNU      UNU      5        UNU      UNU      UNU      
232  159   DZD   Differential Reflectivity Data Array Product: 256   UNU      UNU      9        UNU      UNU      UNU      
233  159   DZD   Differential Reflectivity Data Array Product: 256   UNU      UNU      13       UNU      UNU      UNU      
234  159   DZD   Differential Reflectivity Data Array Product: 256   UNU      UNU      18       UNU      UNU      UNU      
235  159   DZD   Differential Reflectivity Data Array Product: 256   UNU      UNU      24       UNU      UNU      UNU      
236  159   DZD   Differential Reflectivity Data Array Product: 256   UNU      UNU      34       UNU      UNU      UNU      
236  159   DZD   Differential Reflectivity Data Array Product: 256   UNU      UNU      16389    UNU      UNU      UNU      
243  161   DCC   Correlation Coefficient Data Array Product: 256 le  UNU      UNU      5        UNU      UNU      UNU      
244  161   DCC   Correlation Coefficient Data Array Product: 256 le  UNU      UNU      9        UNU      UNU      UNU      
245  161   DCC   Correlation Coefficient Data Array Product: 256 le  UNU      UNU      13       UNU      UNU      UNU      
246  161   DCC   Correlation Coefficient Data Array Product: 256 le  UNU      UNU      18       UNU      UNU      UNU      
247  161   DCC   Correlation Coefficient Data Array Product: 256 le  UNU      UNU      24       UNU      UNU      UNU      
248  161   DCC   Correlation Coefficient Data Array Product: 256 le  UNU      UNU      34       UNU      UNU      UNU      
248  161   DCC   Correlation Coefficient Data Array Product: 256 le  UNU      UNU      16389    UNU      UNU      UNU      
255  163   DKD   Specific Differential Phase Data Array Product: 25  UNU      UNU      5        UNU      UNU      UNU      
256  163   DKD   Specific Differential Phase Data Array Product: 25  UNU      UNU      9        UNU      UNU      UNU      
257  163   DKD   Specific Differential Phase Data Array Product: 25  UNU      UNU      13       UNU      UNU      UNU      
258  163   DKD   Specific Differential Phase Data Array Product: 25  UNU      UNU      18       UNU      UNU      UNU      
259  163   DKD   Specific Differential Phase Data Array Product: 25  UNU      UNU      24       UNU      UNU      UNU      
260  163   DKD   Specific Differential Phase Data Array Product: 25  UNU      UNU      34       UNU      UNU      UNU      
260  163   DKD   Specific Differential Phase Data Array Product: 25  UNU      UNU      16389    UNU      UNU      UNU      
267  165   DHC   Hydrometeor Classification Data Array Product: 256  UNU      UNU      5        UNU      UNU      UNU      
268  165   DHC   Hydrometeor Classification Data Array Product: 256  UNU      UNU      9        UNU      UNU      UNU      
269  165   DHC   Hydrometeor Classification Data Array Product: 256  UNU      UNU      13       UNU      UNU      UNU      
270  165   DHC   Hydrometeor Classification Data Array Product: 256  UNU      UNU      18       UNU      UNU      UNU      
271  165   DHC   Hydrometeor Classification Data Array Product: 256  UNU      UNU      24       UNU      UNU      UNU      
272  165   DHC   Hydrometeor Classification Data Array Product: 256  UNU      UNU      34       UNU      UNU      UNU      
272  165   DHC   Hydrometeor Classification Data Array Product: 256  UNU      UNU      16389    UNU      UNU      UNU      
273  166   ML    Melting Layer Contours: 4 contours/0.13 nm          UNU      UNU      5        UNU      UNU      UNU      
274  166   ML    Melting Layer Contours: 4 contours/0.13 nm          UNU      UNU      9        UNU      UNU      UNU      
275  166   ML    Melting Layer Contours: 4 contours/0.13 nm          UNU      UNU      13       UNU      UNU      UNU      
276  166   ML    Melting Layer Contours: 4 contours/0.13 nm          UNU      UNU      18       UNU      UNU      UNU      
277  166   ML    Melting Layer Contours: 4 contours/0.13 nm          UNU      UNU      24       UNU      UNU      UNU      
278  166   ML    Melting Layer Contours: 4 contours/0.13 nm          UNU      UNU      34       UNU      UNU      UNU      
278  166   ML    Melting Layer Contours: 4 contours/0.13 nm          UNU      UNU      16389    UNU      UNU      UNU      
279  169   OHA   Dual Pol One Hour Accumulation 16 Data Levels       UNU      UNU      UNU      UNU      UNU      UNU      
280  170   DAA   Dual Pol Digital Accumulation Array 256 Data Level  UNU      UNU      UNU      UNU      UNU      UNU      
281  171   STA   Dual Pol Storm Total Accumulation 16 Data Levels    UNU      UNU      UNU      UNU      UNU      UNU      
282  172   DSA   Dual Pol Digital Storm Total Accumulation 256 Data  UNU      UNU      UNU      UNU      UNU      UNU      
283  173   DUA   Dual Pol Digital User Selectable Accumulation Prod  0        0        UNU      UNU      UNU      UNU      
284  174   DOD   Dual Pol Digital One-Hour Difference Accum 256 Dat  UNU      UNU      UNU      UNU      UNU      UNU      
285  175   DSD   Dual Pol Digital Storm Total Difference Accum 256   UNU      UNU      UNU      UNU      UNU      UNU      
286  176   DPR   Digital Precipitation Rate Data: 65536 level/ 0.13  UNU      UNU      UNU      UNU      UNU      UNU      
287  177   HHC   Hybrid Hydrometeor Classification Data Array Produ  UNU      UNU      UNU      UNU      UNU      UNU      
