/* RCS info */
/* $Author: cmn $ */
/* $Locker:  $ */
/* $Date: 2011/05/22 17:12:19 $ */
/* $Id: test_base_prods_8bit_main.c,v 1.1 2011/05/22 17:12:19 cmn Exp $ */
/* $Revision: 1.1 $ */
/* $State: Exp $ */

#include <test_base_prods_8bit.h>

static void Initialize_prod_info();

/*************************************************************************
  The main function for the Test Base Products Products Generation task.
*************************************************************************/

int main( int argc, char *argv[] )
{
  Siteadp_adpt_t Siteadp;

  /* Specify inputs and outputs */

  RPGC_reg_io( argc, argv );

  /* Register scan summary array */

  RPGC_reg_scan_summary();

  /* Register for site info adaptation data. */

  RPGC_reg_site_info( &Siteadp.rda_lat );

  /* Tell system we are ready to go ...... */

  RPGC_task_init( ELEVATION_BASED, argc, argv );

  /* Initialize product-specific information. */

  Initialize_prod_info();

  /* Do Forever .... */

  while(1)
  {
    RPGC_wait_act( WAIT_DRIVING_INPUT );
    Test_base_prods_8bit_buffer_control();
  }

  return 0;
}

/*************************************************************************
  Initialize product-specific information.
*************************************************************************/

static void Initialize_prod_info()
{
  /* --- REF --- */

  Prod_info[REF_PROD_INDEX].code = RPGC_get_code_from_id( Prod_info[REF_PROD_INDEX].id );
  Prod_info[REF_PROD_INDEX].name = "TEST_BASE_PRODS_REF8BIT";
  Prod_info[REF_PROD_INDEX].max_prod_size = MAX_460_PROD_SIZE;
  Prod_info[REF_PROD_INDEX].data_offset = 66.0;
  Prod_info[REF_PROD_INDEX].data_scale = 2.0;
  Prod_info[REF_PROD_INDEX].data_precision = 1.0;
  strcpy( Prod_info[REF_PROD_INDEX].moment, "DREF" );

  /* --- VEL --- */

  Prod_info[VEL_PROD_INDEX].code = RPGC_get_code_from_id( Prod_info[VEL_PROD_INDEX].id );
  Prod_info[VEL_PROD_INDEX].name = "TEST_BASE_PRODS_VEL8BIT";
  Prod_info[VEL_PROD_INDEX].max_prod_size = MAX_300_PROD_SIZE;
  Prod_info[VEL_PROD_INDEX].data_offset = 129.0;
  Prod_info[VEL_PROD_INDEX].data_scale = 2.0;
  Prod_info[VEL_PROD_INDEX].data_precision = 1.0;
  strcpy( Prod_info[VEL_PROD_INDEX].moment, "DVEL" );

  /* --- SPW --- */

  Prod_info[SPW_PROD_INDEX].code = RPGC_get_code_from_id( Prod_info[SPW_PROD_INDEX].id );
  Prod_info[SPW_PROD_INDEX].name = "TEST_BASE_PRODS_SWP8BIT";
  Prod_info[SPW_PROD_INDEX].max_prod_size = MAX_300_PROD_SIZE;
  Prod_info[SPW_PROD_INDEX].data_offset = 129.0;
  Prod_info[SPW_PROD_INDEX].data_scale = 2.0;
  Prod_info[SPW_PROD_INDEX].data_precision = 1.0;
  strcpy( Prod_info[SPW_PROD_INDEX].moment, "DSPW" );

  /* --- ZDR --- */

  Prod_info[ZDR_PROD_INDEX].code = RPGC_get_code_from_id( Prod_info[ZDR_PROD_INDEX].id );
  Prod_info[ZDR_PROD_INDEX].name = "TEST_BASE_PRODS_ZDR8BIT";
  Prod_info[ZDR_PROD_INDEX].max_prod_size = MAX_300_PROD_SIZE;
  Prod_info[ZDR_PROD_INDEX].data_offset = 128.0;
  Prod_info[ZDR_PROD_INDEX].data_scale = 16.0;
  Prod_info[ZDR_PROD_INDEX].data_precision = 0.1;
  strcpy( Prod_info[ZDR_PROD_INDEX].moment, "DZDR" );

  /* --- PHI --- */

  Prod_info[PHI_PROD_INDEX].code = RPGC_get_code_from_id( Prod_info[PHI_PROD_INDEX].id );
  Prod_info[PHI_PROD_INDEX].name = "TEST_BASE_PRODS_PHI8BIT";
  Prod_info[PHI_PROD_INDEX].max_prod_size = MAX_300_PROD_SIZE;
  Prod_info[PHI_PROD_INDEX].data_offset = 2.0;
  Prod_info[PHI_PROD_INDEX].data_scale = 2.8361; /* 10-bit */
  Prod_info[PHI_PROD_INDEX].data_scale = 0.70277; /* 8-bit */
  Prod_info[PHI_PROD_INDEX].data_precision = 0.05;
  strcpy( Prod_info[PHI_PROD_INDEX].moment, "DPHI" );

  /* --- RHO --- */

  Prod_info[RHO_PROD_INDEX].code = RPGC_get_code_from_id( Prod_info[RHO_PROD_INDEX].id );
  Prod_info[RHO_PROD_INDEX].name = "TEST_BASE_PRODS_RHO8BIT";
  Prod_info[RHO_PROD_INDEX].max_prod_size = MAX_300_PROD_SIZE;
  Prod_info[RHO_PROD_INDEX].data_offset = -60.0;
  Prod_info[RHO_PROD_INDEX].data_scale = 300.0;
  Prod_info[RHO_PROD_INDEX].data_precision = 0.00333;
  strcpy( Prod_info[RHO_PROD_INDEX].moment, "DRHO" );

  /* Get the product IDs for all product generated by the task. */

  if( (Prod_info[REF_PROD_INDEX].id = RPGC_get_id_from_name( Prod_info[REF_PROD_INDEX].name )) < 0 )
  {
    sprintf( Msg_buf, "RPGC_get_id_from_name(%s) failed (%d)", Prod_info[REF_PROD_INDEX].name, Prod_info[REF_PROD_INDEX].id );
    RPGC_log_msg( GL_ERROR, "%s", Msg_buf );
    RPGC_abort_task();
  }

  if( (Prod_info[VEL_PROD_INDEX].id = RPGC_get_id_from_name( Prod_info[VEL_PROD_INDEX].name )) < 0 )
  {
    sprintf( Msg_buf, "RPGC_get_id_from_name(%s) failed (%d)", Prod_info[VEL_PROD_INDEX].name, Prod_info[VEL_PROD_INDEX].id );
    RPGC_log_msg( GL_ERROR, "%s", Msg_buf );
    RPGC_abort_task();
  }

  if( (Prod_info[SPW_PROD_INDEX].id = RPGC_get_id_from_name( Prod_info[SPW_PROD_INDEX].name )) < 0 )
  {
    sprintf( Msg_buf, "RPGC_get_id_from_name(%s) failed (%d)", Prod_info[SPW_PROD_INDEX].name, Prod_info[SPW_PROD_INDEX].id );
    RPGC_log_msg( GL_ERROR, "%s", Msg_buf );
    RPGC_abort_task();
  }

  if( (Prod_info[ZDR_PROD_INDEX].id = RPGC_get_id_from_name( Prod_info[ZDR_PROD_INDEX].name )) < 0 )
  {
    sprintf( Msg_buf, "RPGC_get_id_from_name(%s) failed (%d)", Prod_info[ZDR_PROD_INDEX].name, Prod_info[ZDR_PROD_INDEX].id );
    RPGC_log_msg( GL_ERROR, "%s", Msg_buf );
    RPGC_abort_task();
  }

  if( (Prod_info[PHI_PROD_INDEX].id = RPGC_get_id_from_name( Prod_info[PHI_PROD_INDEX].name )) < 0 )
  {
    sprintf( Msg_buf, "RPGC_get_id_from_name(%s) failed (%d)", Prod_info[PHI_PROD_INDEX].name, Prod_info[PHI_PROD_INDEX].id );
    RPGC_log_msg( GL_ERROR, "%s", Msg_buf );
    RPGC_abort_task();
  }

  if( (Prod_info[RHO_PROD_INDEX].id = RPGC_get_id_from_name( Prod_info[RHO_PROD_INDEX].name )) < 0 )
  {
    sprintf( Msg_buf, "RPGC_get_id_from_name(%s) failed (%d)", Prod_info[RHO_PROD_INDEX].name, Prod_info[RHO_PROD_INDEX].id );
    RPGC_log_msg( GL_ERROR, "%s", Msg_buf );
    RPGC_abort_task();
  }
}

