#!/bin/sh
#
# Purpose: 
## This script generates links for library manpages.
## Libraries may have a single manpage for all the callable routines
## in it.  But for the man utility to access the page when called 
## with the routine names, there must be a link created with the
## routine name pointing to the library.
## For example, the file lb.3 is the man page describing the linear
## buffer library routines, one of which is LB_open.  To get the
## page when "man LB_open" is entered, there must be a link from
## LB_open.3 to lb.3.

## To generate these links, at the bottom of this file, enter
## link_it followed by the library man page name, followed by
## the routines described in it.  All files are assumed to
## be in the current directory, and have the suffix of ".3"

# RCS info
# $Author: cmn $
# $Locker:  $
# $Date: 2006/08/18 18:43:25 $
# $Id: link_man_3,v 1.10 2006/08/18 18:43:25 cmn Exp $
# $Revision: 1.10 $
# $State: Exp $



link_it ()

{ 
  for file in $*
  {
  
# if the file already exists, don't create the link.
  if test ! -f $file.3
  then 
# skip the first argument
    if [ $1 != $file ]
    then
        ln -s $1.3 $file.3 
    fi
  fi
  }
}

link_it cs CS_error CS_entry  CS_level  CS_event CS_cfg_name  CS_control  CS_error  CS_report  CS_entry_int_key 
link_it en EN_cntl EN_deregister EN_post EN_register EN_register_obj
link_it lb LB_open LB_FILE  LB_MEMORY LB_REPLACE LB_NORMAL LB_MUST_READ  LB_NORMAL LB_SINGLE_WRITER LB_NORMAL LB_DIRECT  LB_READ LB_WRITE LB_CREATE LB_NORMAL LB_BAD_ARGUMENT LB_OPEN_FAILED LB_DIFFER LB_UPDATE_FAILED LB_TOO_MANY_WRITERS LB_FTOK_FAILED LB_SHMGET_FAILED LB_FTRUNCATE_FAILED LB_OPEN_LOCK_FILE_FAILED LB_read  LB_read_window  LB_write  LB_close  LB_FULL LB_BAD_ID LB_BAD_ACCESS LB_MSG_TOO_LARGE LB_LENGTH_ERROR LB_close  LB_remove  LB_seek  LB_clear  LB_stat  LB_list  LB_register  LB_set_tag  LB_size LB_direct  LB_lock  LB_previous_msgid  LB_PREV_MSGID_FAILED LB_set_poll  LB_mark       
link_it le  LE_init  LE_instance  LE_send_msg  LE_terminate 
link_it malrm  MALRM_cancel  MALRM_deregister  MALRM_register  MALRM_set
link_it misc  unix_time  msleep  MISC_bswap  MISC_sig_raise MISC_sig_signal MISC_string_basename  MISC_string_date_time MISC_string_dirname MISC_string_fit MISC_string_fqdn_to_simple  MISC_string_strpnlnz MISC_string_time
link_it orpg  CFG_DIR  CFG_SRC  LE_DIR_EVENT  ORPGDIR
link_it orpgcmi ORPGCMI_rda_request   ORPGCMI_rda_response  ORPGCMI_request  ORPGCMI_response 
link_it orpgda  ORPGDA_read  ORPGDA_write ORPGDA_info  ORPGDA_changed  ORPGDA_list  ORPGDA_lbfd  ORPGDA_group  ORPGDA_update  ORPGDA_close 
link_it orpgcfg ORPGCFG_dataid_to_path ORPGCFG_path_to_dataid
link_it orpginfo ORPGINFO_get_nodeid ORPGINFO_statefl_flag
link_it orpgtask  ORPGTASK_exit  ORPGTASK_init ORPGTASK_reg_term_hdlr ORPGTASK_state_change ORPGTASK_whoami
link_it orpgtat  ORPGTAT_get_entry ORPGTAT_read_ascii_tbl ORPGTAT_read_tbl ORPGTAT_set_mem_ary
link_it rmt   RMT_create_connection   RMT_set_current  RMT_check_connection  RMT_terminate_service  RMT_messages  RMT_port_number  RMT_time_out  RMT_set_password  RMT_close_connection  RMT_lock_connection  RMT_ask_password  RMT_use_buffer  RMT_send_log RMT_get_conf_file  RMT_free_user_buffer 
link_it rpg RPG_in_data RPG_in_opt RPG_out_data RPG_out_data_wevent  RPG_reg_adpt  register_adapt  RPG_reg_scan_summary  RPG_read_scan_summary  RPG_task_init  RPG_wait_act  BUFFER_CONTROL  RPG_wait_for_event  get_inbuf  rel_inbuf  get_outbuf  rel_outbuf  rel_inbuf  RPG_itc_in  RPG_itc_out RPG_itc_read  RPG_itc_write  RPG_itc_callback  A31168__ABORT_ME_BECAUSE  A31145__ABORT_ME  A31169__ABORT_DATATYPE_BECAUSE  a3cm40 a3cm41  RPG_data_access_group  RPG_data_access_update RPG_data_access_read  RPG_data_access_write
link_it rss_file  RSS_close  RSS_copy  RSS_lseek  RSS_open  RSS_read  RSS_rename  RSS_unlink  RSS_write 
link_it rss_lb  RSS_LB_open  RSS_LB_read  RSS_LB_write  RSS_LB_close  RSS_LB_remove  RSS_LB_seek  RSS_LB_clear  RSS_LB_stat  RSS_LB_list RSS_LB_mark  RSS_LB_size  RSS_LB_previous_msgid 
link_it rss_sys_clib   RSS_exec  RSS_kill  RSS_process  RSS_system  RSS_time 
link_it rss_util  RSS_test_rpc 
link_it orpgumc  UMC_from_ICD UMC_to_ICD  UMC_from_ICD_RDA 
exit 0
