# RCS info
# $Author$
# $Locker$
# $Date$
# $Id$
# $Revision$
# $State$

include $(MAKEINC)/make.common
include $(MAKEINC)/make.$(ARCH)

BINMAKEFILES = sample3_t2.mak

include $(MAKEINC)/make.parent_bin

