/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

/******************************************************************************
 * Description:
 *      This function creates the GUI for the main window.  It creates all 
 *      of the widgets, registers the callbacks, and also registers everything
 *      with the GLADE_HOOKUP_OBJECT function.
 * Input:
 *      Nothing
 * Output:
 *      The main window's GUI
 * Returns:
 *      The outer_window widget
 * Notes:
 *      This has some custom renderers, so if you are rebuilding with Glade, 
 *      you will overwrite somet things if you are not careful.  Meld is 
 *      a good suggestion.
 *****************************************************************************/
GtkWidget*
create_outer_window (void)
{
  GtkWidget *outer_window;
  GtkWidget *product_viewer_vbox;
  GtkWidget *choose_data_frame;
  GtkWidget *choose_data_alignment;
  GtkWidget *choose_data_vbox;
  GtkWidget *choose_data_main_hbox;
  GtkWidget *choose_data_left_vbox;
  GtkWidget *choose_data_radar_message_hbox;
  GtkWidget *choose_data_radar_message_labels_vbox;
  GtkWidget *radar_label;
  GtkWidget *start_product_label;
  GtkWidget *end_product_label;
  GtkWidget *choose_data_radar_message_combos_vbox;
  GtkWidget *radar_combo;
  GtkWidget *start_product_combo;
  GtkWidget *end_product_combo;
  GtkWidget *choose_data_horiz_separator;
  GtkWidget *choose_data_choose_file_dir_label_hbox;
  GtkWidget *choose_file_directory_label;
  GtkWidget *choose_data_path_text_hbox;
  GtkWidget *file_directory_text;
  GtkWidget *open_button;
  GtkWidget *open_icon;
  GtkWidget *go_button;
  GtkWidget *choose_data_right_hbox;
  GtkWidget *choose_data_vert_separator;
  GtkWidget *choose_data_icons_vbox;
  GtkWidget *add_packet_to_list_button;
  GtkWidget *plus_sign_image;
  GtkWidget *subtrack_packet_from_list_button;
  GtkWidget *minus_sign_image;
  GtkWidget *selected_packets_scroll_window;
  GtkWidget *selected_packets_tree_view;
  GtkWidget *choose_frame_label;
  GtkWidget *filter_and_other_hbox;
  GtkWidget *filter_frame;
  GtkWidget *filter_alignment;
  GtkWidget *filters_hbox;
  GtkWidget *pre_message_filter_spacing;
  GtkWidget *message_filter_button;
  GtkWidget *pre_search_label_spacing;
  GtkWidget *search_label;
  GtkWidget *search_text;
  GtkWidget *pre_clear_button_spacing;
  GtkWidget *clear_button;
  GtkWidget *filter_frame_label;
  GtkWidget *other_frame;
  GtkWidget *alignment1;
  GtkWidget *other_hbox;
  GtkWidget *clear_all_button;
  GtkWidget *help_button;
  GtkWidget *other_label;
  GtkWidget *messages_frame;
  GtkWidget *messages_alignment;
  GtkWidget *message_scroll_window;
  GtkWidget *message_tree;
  GtkWidget *messages_frame_label;
  GtkWidget *status_bar;
  GtkTooltips *tooltips;

  /* Added variables */
  GtkTreeStore *message_tree_tree_store;
  GtkCellRenderer *cell_renderer;
  GtkTreeModel *filter;

  tooltips = gtk_tooltips_new ();
  outer_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (outer_window), _("Product Viewer"));

  product_viewer_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (product_viewer_vbox);
  gtk_container_add (GTK_CONTAINER (outer_window), product_viewer_vbox);

  choose_data_frame = gtk_frame_new (NULL);
  gtk_widget_show (choose_data_frame);
  gtk_box_pack_start (GTK_BOX (product_viewer_vbox), choose_data_frame, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (choose_data_frame), 1);

  choose_data_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (choose_data_alignment);
  gtk_container_add (GTK_CONTAINER (choose_data_frame), choose_data_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (choose_data_alignment), 0, 0, 12, 0);

  choose_data_vbox = gtk_vbox_new (FALSE, 16);
  gtk_widget_show (choose_data_vbox);
  gtk_container_add (GTK_CONTAINER (choose_data_alignment), choose_data_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (choose_data_vbox), 13);

  choose_data_main_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (choose_data_main_hbox);
  gtk_box_pack_start (GTK_BOX (choose_data_vbox), choose_data_main_hbox, TRUE, TRUE, 0);

  choose_data_left_vbox = gtk_vbox_new (FALSE, 1);
  gtk_widget_show (choose_data_left_vbox);
  gtk_box_pack_start (GTK_BOX (choose_data_main_hbox), choose_data_left_vbox, FALSE, FALSE, 0);

  choose_data_radar_message_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (choose_data_radar_message_hbox);
  gtk_box_pack_start (GTK_BOX (choose_data_left_vbox), choose_data_radar_message_hbox, FALSE, FALSE, 0);

  choose_data_radar_message_labels_vbox = gtk_vbox_new (FALSE, 9);
  gtk_widget_show (choose_data_radar_message_labels_vbox);
  gtk_box_pack_start (GTK_BOX (choose_data_radar_message_hbox), choose_data_radar_message_labels_vbox, FALSE, FALSE, 0);

  radar_label = gtk_label_new (_("Radar:"));
  gtk_widget_show (radar_label);
  gtk_box_pack_start (GTK_BOX (choose_data_radar_message_labels_vbox), radar_label, FALSE, FALSE, 1);
  gtk_label_set_justify (GTK_LABEL (radar_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (radar_label), 0, 3);

  start_product_label = gtk_label_new (_("Start Product: "));
  gtk_widget_show (start_product_label);
  gtk_box_pack_start (GTK_BOX (choose_data_radar_message_labels_vbox), start_product_label, FALSE, FALSE, 1);
  gtk_label_set_justify (GTK_LABEL (start_product_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (start_product_label), 3, 1);

  end_product_label = gtk_label_new (_("End Product: "));
  gtk_widget_show (end_product_label);
  gtk_box_pack_start (GTK_BOX (choose_data_radar_message_labels_vbox), end_product_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (end_product_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (end_product_label), 0, 2);

  choose_data_radar_message_combos_vbox = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (choose_data_radar_message_combos_vbox);
  gtk_box_pack_start (GTK_BOX (choose_data_radar_message_hbox), choose_data_radar_message_combos_vbox, FALSE, FALSE, 0);

  /* These are not new_text_entry widgets, which makes a difference */
  radar_combo = gtk_combo_box_entry_new_text ();
  gtk_widget_show (radar_combo);
  gtk_box_pack_start (GTK_BOX (choose_data_radar_message_combos_vbox), radar_combo, FALSE, FALSE, 0);

  start_product_combo = gtk_combo_box_new_text ();
  gtk_widget_show (start_product_combo);
  gtk_box_pack_start (GTK_BOX (choose_data_radar_message_combos_vbox), start_product_combo, FALSE, FALSE, 0);
  gtk_widget_set_size_request (start_product_combo, 265, -1);

  end_product_combo = gtk_combo_box_new_text ();
  gtk_widget_show (end_product_combo);
  gtk_box_pack_start (GTK_BOX (choose_data_radar_message_combos_vbox), end_product_combo, TRUE, TRUE, 0);

  choose_data_horiz_separator = gtk_hseparator_new ();
  gtk_widget_show (choose_data_horiz_separator);
  gtk_box_pack_start (GTK_BOX (choose_data_left_vbox), choose_data_horiz_separator, FALSE, FALSE, 7);

  choose_data_choose_file_dir_label_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (choose_data_choose_file_dir_label_hbox);
  gtk_box_pack_start (GTK_BOX (choose_data_left_vbox), choose_data_choose_file_dir_label_hbox, TRUE, TRUE, 0);

  choose_file_directory_label = gtk_label_new (_("Choose File/Directory:"));
  gtk_widget_show (choose_file_directory_label);
  gtk_box_pack_start (GTK_BOX (choose_data_choose_file_dir_label_hbox), choose_file_directory_label, FALSE, FALSE, 0);

  choose_data_path_text_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (choose_data_path_text_hbox);
  gtk_box_pack_start (GTK_BOX (choose_data_left_vbox), choose_data_path_text_hbox, FALSE, FALSE, 0);

  file_directory_text = gtk_entry_new ();
  gtk_widget_show (file_directory_text);
  gtk_box_pack_start (GTK_BOX (choose_data_path_text_hbox), file_directory_text, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, file_directory_text, _("Enter in a file/directory or use the file manager to the right."), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (file_directory_text), 8226);
  gtk_entry_set_width_chars (GTK_ENTRY (file_directory_text), 40);

  open_button = gtk_button_new ();
  gtk_widget_show (open_button);
  gtk_box_pack_start (GTK_BOX (choose_data_path_text_hbox), open_button, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, open_button, _("Bring up a file manager to select a file."), NULL);

  open_icon = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (open_icon);
  gtk_container_add (GTK_CONTAINER (open_button), open_icon);

  go_button = gtk_button_new_with_mnemonic (_("Go"));
  gtk_widget_show (go_button);
  gtk_box_pack_start (GTK_BOX (choose_data_path_text_hbox), go_button, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (go_button), 2);
  gtk_tooltips_set_tip (tooltips, go_button, _("Parse the file listed in the text field."), NULL);

  choose_data_right_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (choose_data_right_hbox);
  gtk_box_pack_start (GTK_BOX (choose_data_main_hbox), choose_data_right_hbox, TRUE, TRUE, 0);

  choose_data_vert_separator = gtk_vseparator_new ();
  gtk_widget_show (choose_data_vert_separator);
  gtk_box_pack_start (GTK_BOX (choose_data_right_hbox), choose_data_vert_separator, FALSE, FALSE, 2);

  choose_data_icons_vbox = gtk_vbox_new (FALSE, 1);
  gtk_widget_show (choose_data_icons_vbox);
  gtk_box_pack_start (GTK_BOX (choose_data_right_hbox), choose_data_icons_vbox, FALSE, FALSE, 2);

  add_packet_to_list_button = gtk_button_new ();
  gtk_widget_show (add_packet_to_list_button);
  gtk_box_pack_start (GTK_BOX (choose_data_icons_vbox), add_packet_to_list_button, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, add_packet_to_list_button, _("Add the packet in the Start Product box to the list."), NULL);

  plus_sign_image = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (plus_sign_image);
  gtk_container_add (GTK_CONTAINER (add_packet_to_list_button), plus_sign_image);

  subtrack_packet_from_list_button = gtk_button_new ();
  gtk_widget_show (subtrack_packet_from_list_button);
  gtk_box_pack_start (GTK_BOX (choose_data_icons_vbox), subtrack_packet_from_list_button, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, subtrack_packet_from_list_button, _("Remove the selected packet from the list."), NULL);

  minus_sign_image = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (minus_sign_image);
  gtk_container_add (GTK_CONTAINER (subtrack_packet_from_list_button), minus_sign_image);

  selected_packets_scroll_window = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (selected_packets_scroll_window);
  gtk_box_pack_start (GTK_BOX (choose_data_right_hbox), selected_packets_scroll_window, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (selected_packets_scroll_window), GTK_SHADOW_IN);

  /* This creates the selected packets list.*/
  selected_packets_tree_view = gtk_tree_view_new ();
  cell_renderer = gtk_cell_renderer_text_new();
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(selected_packets_tree_view), 0, "RADAR", cell_renderer, "text", 0, NULL);
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(selected_packets_tree_view), 1, "PACKET", cell_renderer, "text", 1, NULL);
  message_tree_tree_store = gtk_tree_store_new(3, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);
  gtk_tree_view_set_model(GTK_TREE_VIEW(selected_packets_tree_view), GTK_TREE_MODEL(message_tree_tree_store));
  gtk_tree_sortable_set_sort_column_id(GTK_TREE_SORTABLE(GTK_TREE_MODEL(message_tree_tree_store)), 1, GTK_SORT_DESCENDING);
  gtk_tree_view_set_rubber_banding(GTK_TREE_VIEW(selected_packets_tree_view), TRUE);
  gtk_tree_selection_set_mode(gtk_tree_view_get_selection(GTK_TREE_VIEW(selected_packets_tree_view)), GTK_SELECTION_MULTIPLE);

  g_object_set(G_OBJECT(selected_packets_tree_view), "level-indentation", 0, "show-expanders", FALSE, NULL);
  gtk_widget_show (selected_packets_tree_view);
  gtk_container_add (GTK_CONTAINER (selected_packets_scroll_window), selected_packets_tree_view);
  gtk_tooltips_set_tip (tooltips, selected_packets_tree_view, _("All packets in this list will be displayed."), NULL);

  choose_frame_label = gtk_label_new (_("<b>Choose Data</b>"));
  gtk_widget_show (choose_frame_label);
  gtk_frame_set_label_widget (GTK_FRAME (choose_data_frame), choose_frame_label);
  gtk_label_set_use_markup (GTK_LABEL (choose_frame_label), TRUE);

  filter_and_other_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (filter_and_other_hbox);
  gtk_box_pack_start (GTK_BOX (product_viewer_vbox), filter_and_other_hbox, TRUE, TRUE, 0);

  filter_frame = gtk_frame_new (NULL);
  gtk_widget_show (filter_frame);
  gtk_box_pack_start (GTK_BOX (filter_and_other_hbox), filter_frame, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (filter_frame), 1);

  filter_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (filter_alignment);
  gtk_container_add (GTK_CONTAINER (filter_frame), filter_alignment);
  gtk_container_set_border_width (GTK_CONTAINER (filter_alignment), 10);
  gtk_alignment_set_padding (GTK_ALIGNMENT (filter_alignment), 0, 0, 12, 0);

  filters_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (filters_hbox);
  gtk_container_add (GTK_CONTAINER (filter_alignment), filters_hbox);

  pre_message_filter_spacing = gtk_label_new (_("                       "));
  gtk_widget_show (pre_message_filter_spacing);
  gtk_box_pack_start (GTK_BOX (filters_hbox), pre_message_filter_spacing, FALSE, FALSE, 0);

  message_filter_button = gtk_button_new_with_mnemonic (_("Message Filter"));
  gtk_widget_show (message_filter_button);
  gtk_box_pack_start (GTK_BOX (filters_hbox), message_filter_button, FALSE, FALSE, 0);

  pre_search_label_spacing = gtk_label_new (_("                                    "));
  gtk_widget_show (pre_search_label_spacing);
  gtk_box_pack_start (GTK_BOX (filters_hbox), pre_search_label_spacing, FALSE, FALSE, 0);

  search_label = gtk_label_new (_("Search:   "));
  gtk_widget_show (search_label);
  gtk_box_pack_start (GTK_BOX (filters_hbox), search_label, FALSE, FALSE, 0);

  search_text = gtk_entry_new ();
  gtk_widget_show (search_text);
  gtk_box_pack_start (GTK_BOX (filters_hbox), search_text, FALSE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (search_text), 8226);

  pre_clear_button_spacing = gtk_label_new (_("     "));
  gtk_widget_show (pre_clear_button_spacing);
  gtk_box_pack_start (GTK_BOX (filters_hbox), pre_clear_button_spacing, FALSE, FALSE, 0);

  clear_button = gtk_button_new_with_mnemonic (_("Clear"));
  gtk_widget_show (clear_button);
  gtk_box_pack_start (GTK_BOX (filters_hbox), clear_button, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, clear_button, _("Clears the search filter."), NULL);

  filter_frame_label = gtk_label_new (_("<b>Filter</b>"));
  gtk_widget_show (filter_frame_label);
  gtk_frame_set_label_widget (GTK_FRAME (filter_frame), filter_frame_label);
  gtk_label_set_use_markup (GTK_LABEL (filter_frame_label), TRUE);

  other_frame = gtk_frame_new (NULL);
  gtk_widget_show (other_frame);
  gtk_box_pack_start (GTK_BOX (filter_and_other_hbox), other_frame, TRUE, TRUE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (other_frame), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  other_hbox = gtk_hbox_new (FALSE, 15);
  gtk_widget_show (other_hbox);
  gtk_container_add (GTK_CONTAINER (alignment1), other_hbox);
  gtk_container_set_border_width (GTK_CONTAINER (other_hbox), 11);

  clear_all_button = gtk_button_new_with_mnemonic (_("Clear All"));
  gtk_widget_show (clear_all_button);
  gtk_box_pack_start (GTK_BOX (other_hbox), clear_all_button, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, clear_all_button, _("Clears all fields and filters."), NULL);

  help_button = gtk_button_new_with_mnemonic (_("Help"));
  gtk_widget_show (help_button);
  gtk_box_pack_start (GTK_BOX (other_hbox), help_button, FALSE, FALSE, 0);
  gtk_widget_set_size_request (help_button, 44, -1);
  gtk_tooltips_set_tip (tooltips, help_button, _("Bring up the help instructions."), NULL);

  other_label = gtk_label_new (_("<b>Other</b>"));
  gtk_widget_show (other_label);
  gtk_frame_set_label_widget (GTK_FRAME (other_frame), other_label);
  gtk_label_set_use_markup (GTK_LABEL (other_label), TRUE);

  messages_frame = gtk_frame_new (NULL);
  gtk_widget_show (messages_frame);
  gtk_box_pack_start (GTK_BOX (product_viewer_vbox), messages_frame, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (messages_frame), 1);
  gtk_frame_set_shadow_type (GTK_FRAME (messages_frame), GTK_SHADOW_NONE);

  messages_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (messages_alignment);
  gtk_container_add (GTK_CONTAINER (messages_frame), messages_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (messages_alignment), 0, 0, 12, 0);

  message_scroll_window = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (message_scroll_window);
  gtk_container_add (GTK_CONTAINER (messages_alignment), message_scroll_window);
  gtk_widget_set_size_request (message_scroll_window, -1, 600);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (message_scroll_window), GTK_SHADOW_IN);

  message_tree_tree_store = gtk_tree_store_new(5, G_TYPE_STRING, G_TYPE_STRING, 
      G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);

  filter = gtk_tree_model_filter_new(GTK_TREE_MODEL(message_tree_tree_store), NULL);

  gtk_tree_model_filter_set_visible_func(GTK_TREE_MODEL_FILTER(filter), 
        (GtkTreeModelFilterVisibleFunc)main_tree_filter_callback, selected_packets_tree_view, NULL);
 
  message_tree = gtk_tree_view_new_with_model (filter);
  cell_renderer = gtk_cell_renderer_text_new();
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(message_tree), 
                                              0, "DATE", cell_renderer, "text", 
                                              0, "background", 3, NULL);

  cell_renderer = gtk_cell_renderer_text_new();
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(message_tree), 
                                              1, "TIME", cell_renderer, "text", 
                                              1, "background", 3, NULL);

  cell_renderer = gtk_cell_renderer_text_new();
  gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(message_tree), 
                                              2, "MESSAGE", cell_renderer, "text", 
                                              2, "background", 3, NULL);
  

  g_object_set(G_OBJECT(message_tree), "level-indentation", 0, "show-expanders", FALSE, NULL);
  gtk_widget_show (message_tree);
  gtk_container_add (GTK_CONTAINER (message_scroll_window), message_tree);
  g_object_unref(G_OBJECT(message_tree_tree_store));
  g_object_unref(G_OBJECT(filter));
  gtk_tooltips_set_tip (tooltips, message_tree, _("The filtered file(s)."), NULL);

  messages_frame_label = gtk_label_new (_("<b>Messages</b>"));
  gtk_widget_show (messages_frame_label);
  gtk_frame_set_label_widget (GTK_FRAME (messages_frame), messages_frame_label);
  gtk_label_set_use_markup (GTK_LABEL (messages_frame_label), TRUE);

  status_bar = gtk_statusbar_new ();
  gtk_widget_show (status_bar);
  gtk_box_pack_start (GTK_BOX (product_viewer_vbox), status_bar, FALSE, FALSE, 0);

  gtk_widget_add_events(end_product_combo, GDK_BUTTON_PRESS_MASK);
  gtk_widget_add_events(outer_window, GDK_BUTTON_PRESS_MASK);

  g_signal_connect ((gpointer) outer_window, "show",
                    G_CALLBACK (on_outer_window_show),
                    NULL);
  g_signal_connect ((gpointer) radar_combo, "changed",
                    G_CALLBACK (on_radar_combo_changed),
                    NULL);
  g_signal_connect ((gpointer) start_product_combo, "changed",
                    G_CALLBACK (on_start_product_combo_changed),
                    NULL);
  g_signal_connect ((gpointer) end_product_combo, "changed",
                    G_CALLBACK (on_end_product_combo_changed),
                    NULL);
  g_signal_connect ((gpointer) open_button, "clicked",
                    G_CALLBACK (on_open_button_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) go_button, "clicked",
                            G_CALLBACK (on_go_button_clicked),
                            GTK_OBJECT (file_directory_text));
  g_signal_connect ((gpointer) add_packet_to_list_button, "clicked",
                    G_CALLBACK (on_add_packet_to_list_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) subtrack_packet_from_list_button, "clicked",
                    G_CALLBACK (on_subtrack_packet_from_list_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) message_filter_button, "clicked",
                    G_CALLBACK (on_message_filter_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) search_text, "changed",
                    G_CALLBACK (on_search_text_changed),
                    NULL);
  g_signal_connect ((gpointer) clear_button, "clicked",
                    G_CALLBACK (on_clear_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) status_bar, "text_popped",
                    G_CALLBACK (on_status_bar_text_popped),
                    NULL);
  g_signal_connect ((gpointer) status_bar, "text_pushed",
                    G_CALLBACK (on_status_bar_text_pushed),
                    NULL);
  g_signal_connect ((gpointer) status_bar, "add",
                    G_CALLBACK (on_status_bar_add),
                    NULL);
  g_signal_connect ((gpointer) status_bar, "remove",
                    G_CALLBACK (on_status_bar_remove),
                    NULL);
  g_signal_connect ((gpointer) clear_all_button, "clicked",
                    G_CALLBACK (on_clear_all_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) help_button, "clicked",
                    G_CALLBACK (on_help_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (outer_window, outer_window, "outer_window");
  GLADE_HOOKUP_OBJECT (outer_window, product_viewer_vbox, "product_viewer_vbox");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_frame, "choose_data_frame");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_alignment, "choose_data_alignment");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_vbox, "choose_data_vbox");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_main_hbox, "choose_data_main_hbox");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_left_vbox, "choose_data_left_vbox");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_radar_message_hbox, "choose_data_radar_message_hbox");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_radar_message_labels_vbox, "choose_data_radar_message_labels_vbox");
  GLADE_HOOKUP_OBJECT (outer_window, radar_label, "radar_label");
  GLADE_HOOKUP_OBJECT (outer_window, start_product_label, "start_product_label");
  GLADE_HOOKUP_OBJECT (outer_window, end_product_label, "end_product_label");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_radar_message_combos_vbox, "choose_data_radar_message_combos_vbox");
  GLADE_HOOKUP_OBJECT (outer_window, radar_combo, "radar_combo");
  GLADE_HOOKUP_OBJECT (outer_window, start_product_combo, "start_product_combo");
  GLADE_HOOKUP_OBJECT (outer_window, end_product_combo, "end_product_combo");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_horiz_separator, "choose_data_horiz_separator");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_choose_file_dir_label_hbox, "choose_data_choose_file_dir_label_hbox");
  GLADE_HOOKUP_OBJECT (outer_window, choose_file_directory_label, "choose_file_directory_label");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_path_text_hbox, "choose_data_path_text_hbox");
  GLADE_HOOKUP_OBJECT (outer_window, file_directory_text, "file_directory_text");
  GLADE_HOOKUP_OBJECT (outer_window, open_button, "open_button");
  GLADE_HOOKUP_OBJECT (outer_window, open_icon, "open_icon");
  GLADE_HOOKUP_OBJECT (outer_window, go_button, "go_button");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_right_hbox, "choose_data_right_hbox");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_vert_separator, "choose_data_vert_separator");
  GLADE_HOOKUP_OBJECT (outer_window, choose_data_icons_vbox, "choose_data_icons_vbox");
  GLADE_HOOKUP_OBJECT (outer_window, add_packet_to_list_button, "add_packet_to_list_button");
  GLADE_HOOKUP_OBJECT (outer_window, plus_sign_image, "plus_sign_image");
  GLADE_HOOKUP_OBJECT (outer_window, subtrack_packet_from_list_button, "subtrack_packet_from_list_button");
  GLADE_HOOKUP_OBJECT (outer_window, minus_sign_image, "minus_sign_image");
  GLADE_HOOKUP_OBJECT (outer_window, selected_packets_scroll_window, "selected_packets_scroll_window");
  GLADE_HOOKUP_OBJECT (outer_window, selected_packets_tree_view, "selected_packets_tree_view");
  GLADE_HOOKUP_OBJECT (outer_window, choose_frame_label, "choose_frame_label");
  GLADE_HOOKUP_OBJECT (outer_window, filter_and_other_hbox, "filter_and_other_hbox");
  GLADE_HOOKUP_OBJECT (outer_window, filter_frame, "filter_frame");
  GLADE_HOOKUP_OBJECT (outer_window, filter_alignment, "filter_alignment");
  GLADE_HOOKUP_OBJECT (outer_window, filters_hbox, "filters_hbox");
  GLADE_HOOKUP_OBJECT (outer_window, pre_message_filter_spacing, "pre_message_filter_spacing");
  GLADE_HOOKUP_OBJECT (outer_window, message_filter_button, "message_filter_button");
  GLADE_HOOKUP_OBJECT (outer_window, pre_search_label_spacing, "pre_search_label_spacing");
  GLADE_HOOKUP_OBJECT (outer_window, search_label, "search_label");
  GLADE_HOOKUP_OBJECT (outer_window, search_text, "search_text");
  GLADE_HOOKUP_OBJECT (outer_window, pre_clear_button_spacing, "pre_clear_button_spacing");
  GLADE_HOOKUP_OBJECT (outer_window, clear_button, "clear_button");
  GLADE_HOOKUP_OBJECT (outer_window, filter_frame_label, "filter_frame_label");
  GLADE_HOOKUP_OBJECT (outer_window, other_frame, "other_frame");
  GLADE_HOOKUP_OBJECT (outer_window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (outer_window, other_hbox, "other_hbox");
  GLADE_HOOKUP_OBJECT (outer_window, clear_all_button, "clear_all_button");
  GLADE_HOOKUP_OBJECT (outer_window, help_button, "help_button");
  GLADE_HOOKUP_OBJECT (outer_window, other_label, "other_label");
  GLADE_HOOKUP_OBJECT (outer_window, messages_frame, "messages_frame");
  GLADE_HOOKUP_OBJECT (outer_window, messages_alignment, "messages_alignment");
  GLADE_HOOKUP_OBJECT (outer_window, message_scroll_window, "message_scroll_window");
  GLADE_HOOKUP_OBJECT (outer_window, message_tree, "message_tree");
  GLADE_HOOKUP_OBJECT (outer_window, messages_frame_label, "messages_frame_label");
  GLADE_HOOKUP_OBJECT (outer_window, status_bar, "status_bar");
  GLADE_HOOKUP_OBJECT_NO_REF(outer_window, cell_renderer, "cell_renderer");
  GLADE_HOOKUP_OBJECT_NO_REF(outer_window, message_tree_tree_store, "message_tree_tree_store");
  GLADE_HOOKUP_OBJECT_NO_REF (outer_window, tooltips, "tooltips");

  return outer_window;
}

/******************************************************************************
 * Description: 
 *      This is the GUI for the file chooser dialog that occurs when 
 *      the user clicks the folder button.
 * Input:
 *      Nothing
 * Output:
 *      Brings up the file chooser dialog
 * Returns:
 *      The filechooserdialog1 object
 * Notes:
 *****************************************************************************/
GtkWidget*
create_filechooserdialog1 (void)
{
  GtkWidget *filechooserdialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *button1;
  GtkWidget *button2;

  filechooserdialog1 = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL, NULL);
  GTK_WINDOW (filechooserdialog1)->type = GTK_WINDOW_POPUP;
  gtk_window_set_position (GTK_WINDOW (filechooserdialog1), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (filechooserdialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (filechooserdialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  button1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button1);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, filechooserdialog1, "filechooserdialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button1, "button1");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button2, "button2");

  gtk_widget_grab_default (button2);
  return filechooserdialog1;
}

/******************************************************************************
 * Description:
 *      This function creates the GUI for the filter window.  It creates all 
 *      of the widgets, registers the callbacks, and also registers everything
 *      with the GLADE_HOOKUP_OBJECT function.
 * Input:
 *      Nothing
 * Output:
 *      The filter window's GUI
 * Returns:
 *      The filter_window widget
 * Notes:
 *****************************************************************************/
GtkWidget*
create_filter_window (void)
{
  GtkWidget *filter_window;
  GtkWidget *filter_main_vbox;
  GtkWidget *select_rpg_message_frame;
  GtkWidget *select_rpg_message_frame_alignment;
  GtkWidget *select_rpg_message_vbox;
  GtkWidget *informational_checkbutton_hbox;
  GtkWidget *informational_checkbutton;
  GtkWidget *informational_label;
  GtkWidget *general_status_checkbutton_hbox;
  GtkWidget *general_status_checkbutton;
  GtkWidget *general_status_label;
  GtkWidget *narrowband_communications_checkbutton_hbox;
  GtkWidget *narrowband_communications_checkbutton;
  GtkWidget *warnings_errors_checkbutton_hbox;
  GtkWidget *warnings_errors_checkbutton;
  GtkWidget *select_rpg_message_label;
  GtkWidget *select_rpg_alarm_frame;
  GtkWidget *select_rpg_alarm_alignment;
  GtkWidget *select_rpg_alarm_vbox;
  GtkWidget *load_shed_checkbutton_hbox;
  GtkWidget *load_shed_checkbutton;
  GtkWidget *maintenance_required_checkbutton_hbox;
  GtkWidget *maintenance_required_checkbutton;
  GtkWidget *maintenance_mandatory_checkbutton_hbox;
  GtkWidget *maintenance_mandatory_checkbutton;
  GtkWidget *select_rpg_alarm_label;
  GtkWidget *select_rda_alarm_frame;
  GtkWidget *select_rda_alarm_label_alignment;
  GtkWidget *rda_alarm_vbox;
  GtkWidget *secondary_rda_alarm_checkbutton_hbox;
  GtkWidget *secondary_rda_alarm_checkbutton;
  GtkWidget *maintenance_required_rda_alarm_checkbutton_hbox;
  GtkWidget *maintenance_required_rda_alarm_checkbutton;
  GtkWidget *maintenance_mandatory_rda_alarm_checkbutton_hbox;
  GtkWidget *maintenance_mandatory_rda_alarm_checkbutton;
  GtkWidget *inoperable_rda_alarm_checkbutton_hbox;
  GtkWidget *inoperable_rda_alarm_checkbutton;
  GtkWidget *select_rda_alarm_label;
  GtkWidget *select_dates_frame;
  GtkWidget *select_dates_alignment;
  GtkWidget *select_dates_vbox;
  GtkWidget *select_dates_range;
  GtkWidget *select_dates_range_alignment;
  GtkWidget *select_dates_range_start_hbox;
  GtkWidget *select_dates_range_year_start_label;
  GtkObject *select_dates_range_year_start_spinbutton_adj;
  GtkWidget *select_dates_range_year_start_spinbutton;
  GtkWidget *select_dates_range_month_start_label;
  GtkObject *select_dates_range_month_start_spinbutton_adj;
  GtkWidget *select_dates_range_month_start_spinbutton;
  GtkWidget *select_dates_range_day_start_label;
  GtkObject *select_dates_range_day_start_spinbutton_adj;
  GtkWidget *select_dates_range_day_start_spinbutton;
  GtkWidget *select_dates_range_hour_start_label;
  GtkObject *select_dates_range_hour_start_spinbutton_adj;
  GtkWidget *select_dates_range_hour_start_spinbutton;
  GtkWidget *select_dates_range_minute_start_label;
  GtkObject *select_dates_range_minute_start_spinbutton_adj;
  GtkWidget *select_dates_range_minute_start_spinbutton;
  GtkWidget *select_dates_range_second_start_label;
  GtkObject *select_dates_range_second_start_spinbutton_adj;
  GtkWidget *select_dates_range_second_start_spinbutton;
  GtkWidget *select_dates_range_start_label;
  GtkWidget *select_dates_range_end_frame;
  GtkWidget *select_dates_range_end_alignment;
  GtkWidget *select_dates_range_end_hbox;
  GtkWidget *select_dates_range_year_end_label;
  GtkObject *select_dates_range_year_end_spinbutton_adj;
  GtkWidget *select_dates_range_year_end_spinbutton;
  GtkWidget *select_dates_range_month_end_label;
  GtkObject *select_dates_range_month_end_spinbutton_adj;
  GtkWidget *select_dates_range_month_end_spinbutton;
  GtkWidget *select_dates_range_day_end_label;
  GtkObject *select_dates_range_day_end_spinbutton_adj;
  GtkWidget *select_dates_range_day_end_spinbutton;
  GtkWidget *select_dates_range_hour_end_label;
  GtkObject *select_dates_range_hour_end_spinbutton_adj;
  GtkWidget *select_dates_range_hour_end_spinbutton;
  GtkWidget *select_dates_range_minute_end_label;
  GtkObject *select_dates_range_minute_end_spinbutton_adj;
  GtkWidget *select_dates_range_minute_end_spinbutton;
  GtkWidget *select_dates_range_second_end_label;
  GtkObject *select_dates_range_second_end_spinbutton_adj;
  GtkWidget *select_dates_range_second_end_spinbutton;
  GtkWidget *select_dates_range_end_label;
  GtkWidget *select_dates_range_button_hbox;
  GtkWidget *filter_ranges_button;
  GtkWidget *select_dates_hseparator;
  GtkWidget *select_dates_match_frame;
  GtkWidget *select_dates_match_alignment;
  GtkWidget *select_dates_match_vbox;
  GtkWidget *select_dates_match_spinbutton_hbox;
  GtkWidget *select_dates_match_year_label;
  GtkObject *select_dates_match_year_spinbutton_adj;
  GtkWidget *select_dates_match_year_spinbutton;
  GtkWidget *select_dates_match_month_label;
  GtkObject *select_dates_match_month_spinbutton_adj;
  GtkWidget *select_dates_match_month_spinbutton;
  GtkWidget *select_dates_match_day_label;
  GtkObject *select_dates_match_day_spinbutton_adj;
  GtkWidget *select_dates_match_day_spinbutton;
  GtkWidget *select_dates_match_hour_label;
  GtkObject *select_dates_match_hour_spinbutton_adj;
  GtkWidget *select_dates_match_hour_spinbutton;
  GtkWidget *select_dates_match_minute_label;
  GtkObject *select_dates_match_minute_spinbutton_adj;
  GtkWidget *select_dates_match_minute_spinbutton;
  GtkWidget *select_dates_match_second_label;
  GtkObject *select_dates_match_second_spinbutton_adj;
  GtkWidget *select_dates_match_second_spinbutton;
  GtkWidget *select_dates_match_label;
  GtkWidget *select_dates_match_button_hbox;
  GtkWidget *filter_match_button;
  GtkWidget *select_dates_label;
  GdkPixbuf *color_pixbuf;
  GdkPixbuf *pixbuf;
  GtkWidget *image;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();


  filter_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (filter_window), 2);
  gtk_window_set_title (GTK_WINDOW (filter_window), _("filter_window"));
  gtk_window_set_position (GTK_WINDOW (filter_window), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_resizable (GTK_WINDOW (filter_window), FALSE);

  filter_main_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (filter_main_vbox);
  gtk_container_add (GTK_CONTAINER (filter_window), filter_main_vbox);

  select_rpg_message_frame = gtk_frame_new (NULL);
  gtk_widget_show (select_rpg_message_frame);
  gtk_box_pack_start (GTK_BOX (filter_main_vbox), select_rpg_message_frame, FALSE, FALSE, 0);

  select_rpg_message_frame_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (select_rpg_message_frame_alignment);
  gtk_container_add (GTK_CONTAINER (select_rpg_message_frame), select_rpg_message_frame_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (select_rpg_message_frame_alignment), 0, 0, 12, 0);

  select_rpg_message_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (select_rpg_message_vbox);
  gtk_container_add (GTK_CONTAINER (select_rpg_message_frame_alignment), select_rpg_message_vbox);

  informational_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (informational_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (select_rpg_message_vbox), informational_checkbutton_hbox, TRUE, TRUE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0xBEBEBEFF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(informational_checkbutton_hbox), image, FALSE, FALSE, 0);

  informational_checkbutton = gtk_check_button_new ();
  gtk_widget_show (informational_checkbutton);
  gtk_box_pack_start (GTK_BOX (informational_checkbutton_hbox), informational_checkbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, informational_checkbutton, _("Uncheck to filter out the Informational messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (informational_checkbutton), TRUE);

  informational_label = gtk_label_new (_("Informational"));
  gtk_widget_show (informational_label);
  gtk_container_add (GTK_CONTAINER (informational_checkbutton), informational_label);

  general_status_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (general_status_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (select_rpg_message_vbox), general_status_checkbutton_hbox, FALSE, FALSE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0xD2B48CFF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(general_status_checkbutton_hbox), image, FALSE, FALSE, 0);

  general_status_checkbutton = gtk_check_button_new ();
  gtk_widget_show (general_status_checkbutton);
  gtk_box_pack_start (GTK_BOX (general_status_checkbutton_hbox), general_status_checkbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, general_status_checkbutton, _("Uncheck to filter out the General Status messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (general_status_checkbutton), TRUE);

  general_status_label = gtk_label_new (_("General Status"));
  gtk_widget_show (general_status_label);
  gtk_container_add (GTK_CONTAINER (general_status_checkbutton), general_status_label);

  narrowband_communications_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (narrowband_communications_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (select_rpg_message_vbox), narrowband_communications_checkbutton_hbox, FALSE, FALSE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0x00CD00FF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(narrowband_communications_checkbutton_hbox), image, FALSE, FALSE, 0);

  narrowband_communications_checkbutton = gtk_check_button_new_with_mnemonic (_("Narrowband Communications"));
  gtk_widget_show (narrowband_communications_checkbutton);
  gtk_box_pack_start (GTK_BOX (narrowband_communications_checkbutton_hbox), narrowband_communications_checkbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, narrowband_communications_checkbutton, _("Uncheck to filter out the Narrowband Communications messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (narrowband_communications_checkbutton), TRUE);

  warnings_errors_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (warnings_errors_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (select_rpg_message_vbox), warnings_errors_checkbutton_hbox, FALSE, FALSE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0xFFFF00FF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(warnings_errors_checkbutton_hbox), image, FALSE, FALSE, 0);

  warnings_errors_checkbutton = gtk_check_button_new_with_mnemonic (_("Warnings/Errors"));
  gtk_widget_show (warnings_errors_checkbutton);
  gtk_box_pack_start (GTK_BOX (warnings_errors_checkbutton_hbox), warnings_errors_checkbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, warnings_errors_checkbutton, _("Uncheck to filter out the Warnings/Error messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (warnings_errors_checkbutton), TRUE);

  select_rpg_message_label = gtk_label_new (_("<b>Select RPG Message</b>"));
  gtk_widget_show (select_rpg_message_label);
  gtk_frame_set_label_widget (GTK_FRAME (select_rpg_message_frame), select_rpg_message_label);
  gtk_label_set_use_markup (GTK_LABEL (select_rpg_message_label), TRUE);

  select_rpg_alarm_frame = gtk_frame_new (NULL);
  gtk_widget_show (select_rpg_alarm_frame);
  gtk_box_pack_start (GTK_BOX (filter_main_vbox), select_rpg_alarm_frame, FALSE, FALSE, 0);

  select_rpg_alarm_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (select_rpg_alarm_alignment);
  gtk_container_add (GTK_CONTAINER (select_rpg_alarm_frame), select_rpg_alarm_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (select_rpg_alarm_alignment), 0, 0, 12, 0);

  select_rpg_alarm_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (select_rpg_alarm_vbox);
  gtk_container_add (GTK_CONTAINER (select_rpg_alarm_alignment), select_rpg_alarm_vbox);

  load_shed_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (load_shed_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (select_rpg_alarm_vbox), load_shed_checkbutton_hbox, TRUE, TRUE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0x00BFFFFF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(load_shed_checkbutton_hbox), image, FALSE, FALSE, 0);

  load_shed_checkbutton = gtk_check_button_new_with_mnemonic (_("Load Shed (LS)"));
  gtk_widget_show (load_shed_checkbutton);
  gtk_box_pack_start (GTK_BOX (load_shed_checkbutton_hbox), load_shed_checkbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, load_shed_checkbutton, _("Uncheck to filter out the RPG Load Shed messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (load_shed_checkbutton), TRUE);

  maintenance_required_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (maintenance_required_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (select_rpg_alarm_vbox), maintenance_required_checkbutton_hbox, FALSE, FALSE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0xFFFF00FF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(maintenance_required_checkbutton_hbox), image, FALSE, FALSE, 0);

  maintenance_required_checkbutton = gtk_check_button_new_with_mnemonic (_("Maintenance Required (MR)"));
  gtk_widget_show (maintenance_required_checkbutton);
  gtk_box_pack_start (GTK_BOX (maintenance_required_checkbutton_hbox), maintenance_required_checkbutton, FALSE, FALSE, 0);

  gtk_tooltips_set_tip (tooltips, maintenance_required_checkbutton, _("Uncheck to filter out the RPG Maintenance Required messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (maintenance_required_checkbutton), TRUE);

  maintenance_mandatory_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (maintenance_mandatory_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (select_rpg_alarm_vbox), maintenance_mandatory_checkbutton_hbox, FALSE, FALSE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0xFFA500FF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(maintenance_mandatory_checkbutton_hbox), image, FALSE, FALSE, 0);

  maintenance_mandatory_checkbutton = gtk_check_button_new_with_mnemonic (_("Maintenance Mandatory (MM)"));
  gtk_widget_show (maintenance_mandatory_checkbutton);
  gtk_box_pack_start (GTK_BOX (maintenance_mandatory_checkbutton_hbox), maintenance_mandatory_checkbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, maintenance_mandatory_checkbutton, _("Uncheck to filter out the RPG Maintenance Mandatory messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (maintenance_mandatory_checkbutton), TRUE);

  select_rpg_alarm_label = gtk_label_new (_("<b>Select RPG Alarm</b>"));
  gtk_widget_show (select_rpg_alarm_label);
  gtk_frame_set_label_widget (GTK_FRAME (select_rpg_alarm_frame), select_rpg_alarm_label);
  gtk_label_set_use_markup (GTK_LABEL (select_rpg_alarm_label), TRUE);

  select_rda_alarm_frame = gtk_frame_new (NULL);
  gtk_widget_show (select_rda_alarm_frame);
  gtk_box_pack_start (GTK_BOX (filter_main_vbox), select_rda_alarm_frame, FALSE, FALSE, 0);

  select_rda_alarm_label_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (select_rda_alarm_label_alignment);
  gtk_container_add (GTK_CONTAINER (select_rda_alarm_frame), select_rda_alarm_label_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (select_rda_alarm_label_alignment), 0, 0, 12, 0);

  rda_alarm_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (rda_alarm_vbox);
  gtk_container_add (GTK_CONTAINER (select_rda_alarm_label_alignment), rda_alarm_vbox);

  secondary_rda_alarm_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (secondary_rda_alarm_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (rda_alarm_vbox), secondary_rda_alarm_checkbutton_hbox, TRUE, TRUE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0xFFFFFFFF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(secondary_rda_alarm_checkbutton_hbox), image, FALSE, FALSE, 0);

  secondary_rda_alarm_checkbutton = gtk_check_button_new_with_mnemonic (_("Secondary (SEC)"));
  gtk_widget_show (secondary_rda_alarm_checkbutton);
  gtk_box_pack_start (GTK_BOX (secondary_rda_alarm_checkbutton_hbox), secondary_rda_alarm_checkbutton, FALSE, FALSE, 0);

  gtk_tooltips_set_tip (tooltips, secondary_rda_alarm_checkbutton, _("Uncheck to filter out the RDA Secondary messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (secondary_rda_alarm_checkbutton), TRUE);

  maintenance_required_rda_alarm_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (maintenance_required_rda_alarm_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (rda_alarm_vbox), maintenance_required_rda_alarm_checkbutton_hbox, FALSE, FALSE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0xFFFF00FF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(maintenance_required_rda_alarm_checkbutton_hbox), image, FALSE, FALSE, 0);

  maintenance_required_rda_alarm_checkbutton = gtk_check_button_new_with_mnemonic (_("Maintenance Required (MR)"));
  gtk_widget_show (maintenance_required_rda_alarm_checkbutton);
  gtk_box_pack_start (GTK_BOX (maintenance_required_rda_alarm_checkbutton_hbox), maintenance_required_rda_alarm_checkbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, maintenance_required_rda_alarm_checkbutton, _("Uncheck to filter out the RDA Maintenance Required messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (maintenance_required_rda_alarm_checkbutton), TRUE);


  maintenance_mandatory_rda_alarm_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (maintenance_mandatory_rda_alarm_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (rda_alarm_vbox), maintenance_mandatory_rda_alarm_checkbutton_hbox, FALSE, FALSE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0xFFA500FF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(maintenance_mandatory_rda_alarm_checkbutton_hbox), image, FALSE, FALSE, 0);
 

  maintenance_mandatory_rda_alarm_checkbutton = gtk_check_button_new_with_mnemonic (_("Maintenance Mandatory (MM)"));
  gtk_widget_show (maintenance_mandatory_rda_alarm_checkbutton);
  gtk_box_pack_start (GTK_BOX (maintenance_mandatory_rda_alarm_checkbutton_hbox), maintenance_mandatory_rda_alarm_checkbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, maintenance_mandatory_rda_alarm_checkbutton, _("Uncheck to filter out the RDA Maintenance Mandatory messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (maintenance_mandatory_rda_alarm_checkbutton), TRUE);


  inoperable_rda_alarm_checkbutton_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (inoperable_rda_alarm_checkbutton_hbox);
  gtk_box_pack_start (GTK_BOX (rda_alarm_vbox), inoperable_rda_alarm_checkbutton_hbox, FALSE, FALSE, 0);

  pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 15, 15);
  gdk_pixbuf_fill(pixbuf, 0x000000FF);
  color_pixbuf = gdk_pixbuf_new( GDK_COLORSPACE_RGB, FALSE, 8, 13, 13);
  gdk_pixbuf_fill(color_pixbuf, 0xFF0000FF);
  gdk_pixbuf_copy_area(color_pixbuf, 0, 0, 13, 13, pixbuf, 1, 1);
  g_object_unref(G_OBJECT(color_pixbuf));
  image = gtk_image_new_from_pixbuf(pixbuf);
  g_object_unref(G_OBJECT(pixbuf));
  gtk_widget_show(image);
  gtk_box_pack_start(GTK_BOX(inoperable_rda_alarm_checkbutton_hbox), image, FALSE, FALSE, 0);

  inoperable_rda_alarm_checkbutton = gtk_check_button_new_with_mnemonic (_("Inoperable (INOP)"));
  gtk_widget_show (inoperable_rda_alarm_checkbutton);
  gtk_box_pack_start (GTK_BOX (inoperable_rda_alarm_checkbutton_hbox), inoperable_rda_alarm_checkbutton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, inoperable_rda_alarm_checkbutton, _("Uncheck to filter out the RDA Inoperable messages."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (inoperable_rda_alarm_checkbutton), TRUE);

  select_rda_alarm_label = gtk_label_new (_("<b>Select RDA Alarm</b>"));
  gtk_widget_show (select_rda_alarm_label);
  gtk_frame_set_label_widget (GTK_FRAME (select_rda_alarm_frame), select_rda_alarm_label);
  gtk_label_set_use_markup (GTK_LABEL (select_rda_alarm_label), TRUE);

  select_dates_frame = gtk_frame_new (NULL);
  gtk_widget_show (select_dates_frame);
  gtk_box_pack_start (GTK_BOX (filter_main_vbox), select_dates_frame, FALSE, FALSE, 0);

  select_dates_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (select_dates_alignment);
  gtk_container_add (GTK_CONTAINER (select_dates_frame), select_dates_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (select_dates_alignment), 0, 0, 12, 0);

  select_dates_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (select_dates_vbox);
  gtk_container_add (GTK_CONTAINER (select_dates_alignment), select_dates_vbox);

  select_dates_range = gtk_frame_new (NULL);
  gtk_widget_show (select_dates_range);
  gtk_box_pack_start (GTK_BOX (select_dates_vbox), select_dates_range, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (select_dates_range), GTK_SHADOW_NONE);

  select_dates_range_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (select_dates_range_alignment);
  gtk_container_add (GTK_CONTAINER (select_dates_range), select_dates_range_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (select_dates_range_alignment), 0, 0, 12, 0);

  select_dates_range_start_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (select_dates_range_start_hbox);
  gtk_container_add (GTK_CONTAINER (select_dates_range_alignment), select_dates_range_start_hbox);

  select_dates_range_year_start_label = gtk_label_new (_("YY:"));
  gtk_widget_show (select_dates_range_year_start_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_year_start_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_year_start_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_year_start_label), 3, 0);

  select_dates_range_year_start_spinbutton_adj = gtk_adjustment_new (1, 0, 20, 1, 10, 10);
  select_dates_range_year_start_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_year_start_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_year_start_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_year_start_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_year_start_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_year_start_spinbutton, _("Select the most recent year in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_year_start_spinbutton), TRUE);

  select_dates_range_month_start_label = gtk_label_new (_("MM:"));
  gtk_widget_show (select_dates_range_month_start_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_month_start_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_month_start_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_month_start_label), 5, 0);

  select_dates_range_month_start_spinbutton_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  select_dates_range_month_start_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_month_start_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_month_start_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_month_start_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_month_start_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_month_start_spinbutton, _("Select the most recent month in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_month_start_spinbutton), TRUE);

  select_dates_range_day_start_label = gtk_label_new (_("DD:"));
  gtk_widget_show (select_dates_range_day_start_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_day_start_label, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_day_start_label), 5, 0);

  select_dates_range_day_start_spinbutton_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  select_dates_range_day_start_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_day_start_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_day_start_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_day_start_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_day_start_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_day_start_spinbutton, _("Select the most recent day in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_day_start_spinbutton), TRUE);

  select_dates_range_hour_start_label = gtk_label_new (_("hh:"));
  gtk_widget_show (select_dates_range_hour_start_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_hour_start_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_hour_start_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_hour_start_label), 5, 0);

  select_dates_range_hour_start_spinbutton_adj = gtk_adjustment_new (1, 0, 23, 1, 10, 10);
  select_dates_range_hour_start_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_hour_start_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_hour_start_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_hour_start_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_hour_start_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_hour_start_spinbutton, _("Select the most recent hour in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_hour_start_spinbutton), TRUE);

  select_dates_range_minute_start_label = gtk_label_new (_("mm:"));
  gtk_widget_show (select_dates_range_minute_start_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_minute_start_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_minute_start_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_minute_start_label), 5, 0);

  select_dates_range_minute_start_spinbutton_adj = gtk_adjustment_new (1, 0, 59, 1, 10, 10);
  select_dates_range_minute_start_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_minute_start_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_minute_start_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_minute_start_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_minute_start_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_minute_start_spinbutton, _("Select the most recent minute in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_minute_start_spinbutton), TRUE);

  select_dates_range_second_start_label = gtk_label_new (_("ss:"));
  gtk_widget_show (select_dates_range_second_start_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_second_start_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_second_start_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_second_start_label), 5, 0);

  select_dates_range_second_start_spinbutton_adj = gtk_adjustment_new (1, 0, 59, 1, 10, 10);
  select_dates_range_second_start_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_second_start_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_second_start_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_start_hbox), select_dates_range_second_start_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_second_start_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_second_start_spinbutton, _("Select the most recent second in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_second_start_spinbutton), TRUE);

  select_dates_range_start_label = gtk_label_new (_("<b>Range Start</b>"));
  gtk_widget_show (select_dates_range_start_label);
  gtk_frame_set_label_widget (GTK_FRAME (select_dates_range), select_dates_range_start_label);
  gtk_label_set_use_markup (GTK_LABEL (select_dates_range_start_label), TRUE);

  select_dates_range_end_frame = gtk_frame_new (NULL);
  gtk_widget_show (select_dates_range_end_frame);
  gtk_box_pack_start (GTK_BOX (select_dates_vbox), select_dates_range_end_frame, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (select_dates_range_end_frame), GTK_SHADOW_NONE);

  select_dates_range_end_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (select_dates_range_end_alignment);
  gtk_container_add (GTK_CONTAINER (select_dates_range_end_frame), select_dates_range_end_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (select_dates_range_end_alignment), 0, 0, 12, 0);

  select_dates_range_end_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (select_dates_range_end_hbox);
  gtk_container_add (GTK_CONTAINER (select_dates_range_end_alignment), select_dates_range_end_hbox);

  select_dates_range_year_end_label = gtk_label_new (_("YY:"));
  gtk_widget_show (select_dates_range_year_end_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_year_end_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_year_end_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_year_end_label), 3, 0);

  select_dates_range_year_end_spinbutton_adj = gtk_adjustment_new (1, 0, 20, 1, 10, 10);
  select_dates_range_year_end_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_year_end_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_year_end_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_year_end_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_year_end_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_year_end_spinbutton, _("Select the oldest year in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_year_end_spinbutton), TRUE);

  select_dates_range_month_end_label = gtk_label_new (_("MM:"));
  gtk_widget_show (select_dates_range_month_end_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_month_end_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_month_end_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_month_end_label), 5, 0);

  select_dates_range_month_end_spinbutton_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  select_dates_range_month_end_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_month_end_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_month_end_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_month_end_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_month_end_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_month_end_spinbutton, _("Select the oldest month in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_month_end_spinbutton), TRUE);

  select_dates_range_day_end_label = gtk_label_new (_("DD:"));
  gtk_widget_show (select_dates_range_day_end_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_day_end_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_day_end_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_day_end_label), 5, 0);

  select_dates_range_day_end_spinbutton_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  select_dates_range_day_end_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_day_end_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_day_end_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_day_end_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_day_end_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_day_end_spinbutton, _("Select the oldest day in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_day_end_spinbutton), TRUE);

  select_dates_range_hour_end_label = gtk_label_new (_("hh:"));
  gtk_widget_show (select_dates_range_hour_end_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_hour_end_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_hour_end_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_hour_end_label), 5, 0);

  select_dates_range_hour_end_spinbutton_adj = gtk_adjustment_new (1, 0, 23, 1, 10, 10);
  select_dates_range_hour_end_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_hour_end_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_hour_end_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_hour_end_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_hour_end_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_hour_end_spinbutton, _("Select the oldest hour in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_hour_end_spinbutton), TRUE);

  select_dates_range_minute_end_label = gtk_label_new (_("mm:"));
  gtk_widget_show (select_dates_range_minute_end_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_minute_end_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_minute_end_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_minute_end_label), 5, 0);

  select_dates_range_minute_end_spinbutton_adj = gtk_adjustment_new (1, 0, 59, 1, 10, 10);
  select_dates_range_minute_end_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_minute_end_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_minute_end_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_minute_end_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_minute_end_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_minute_end_spinbutton, _("Select the oldest minute in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_minute_end_spinbutton), TRUE);

  select_dates_range_second_end_label = gtk_label_new (_("ss:"));
  gtk_widget_show (select_dates_range_second_end_label);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_second_end_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_range_second_end_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_range_second_end_label), 5, 0);

  select_dates_range_second_end_spinbutton_adj = gtk_adjustment_new (1, 0, 59, 1, 10, 10);
  select_dates_range_second_end_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_range_second_end_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_range_second_end_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_range_end_hbox), select_dates_range_second_end_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_range_second_end_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_range_second_end_spinbutton, _("Select the oldest second in the range."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_range_second_end_spinbutton), TRUE);

  select_dates_range_end_label = gtk_label_new (_("<b>Range End</b>"));
  gtk_widget_show (select_dates_range_end_label);
  gtk_frame_set_label_widget (GTK_FRAME (select_dates_range_end_frame), select_dates_range_end_label);
  gtk_label_set_use_markup (GTK_LABEL (select_dates_range_end_label), TRUE);

  select_dates_range_button_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (select_dates_range_button_hbox);
  gtk_box_pack_start (GTK_BOX (select_dates_vbox), select_dates_range_button_hbox, FALSE, FALSE, 0);

  filter_ranges_button = gtk_button_new_with_mnemonic (_("Filter Ranges "));
  gtk_widget_show (filter_ranges_button);
  gtk_box_pack_start (GTK_BOX (select_dates_range_button_hbox), filter_ranges_button, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, filter_ranges_button, _("Select to filter out all rows that do not exist between the dates specified above."), NULL);

  select_dates_hseparator = gtk_hseparator_new ();
  gtk_widget_show (select_dates_hseparator);
  gtk_box_pack_start (GTK_BOX (select_dates_vbox), select_dates_hseparator, FALSE, FALSE, 8);

  select_dates_match_frame = gtk_frame_new (NULL);
  gtk_widget_show (select_dates_match_frame);
  gtk_box_pack_start (GTK_BOX (select_dates_vbox), select_dates_match_frame, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (select_dates_match_frame), GTK_SHADOW_NONE);

  select_dates_match_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (select_dates_match_alignment);
  gtk_container_add (GTK_CONTAINER (select_dates_match_frame), select_dates_match_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (select_dates_match_alignment), 0, 0, 12, 0);

  select_dates_match_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (select_dates_match_vbox);
  gtk_container_add (GTK_CONTAINER (select_dates_match_alignment), select_dates_match_vbox);

  select_dates_match_spinbutton_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (select_dates_match_spinbutton_hbox);
  gtk_box_pack_start (GTK_BOX (select_dates_match_vbox), select_dates_match_spinbutton_hbox, TRUE, TRUE, 0);

  select_dates_match_year_label = gtk_label_new (_("YY:"));
  gtk_widget_show (select_dates_match_year_label);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_year_label, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (select_dates_match_year_label), 3, 0);

  select_dates_match_year_spinbutton_adj = gtk_adjustment_new (1, -1, 20, 1, 10, 10);
  select_dates_match_year_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_match_year_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_match_year_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_year_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_match_year_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_match_year_spinbutton, _("Select the year to match. A value of '-1' will match all years."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_match_year_spinbutton), TRUE);

  select_dates_match_month_label = gtk_label_new (_("MM:"));
  gtk_widget_show (select_dates_match_month_label);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_month_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (select_dates_match_month_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (select_dates_match_month_label), 5, 0);

  select_dates_match_month_spinbutton_adj = gtk_adjustment_new (1, -1, 12, 1, 10, 10);
  select_dates_match_month_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_match_month_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_match_month_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_month_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_match_month_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_match_month_spinbutton, _("Select the month to match. A value of '-1' will match all months."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_match_month_spinbutton), TRUE);

  select_dates_match_day_label = gtk_label_new (_("DD:"));
  gtk_widget_show (select_dates_match_day_label);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_day_label, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (select_dates_match_day_label), 5, 0);

  select_dates_match_day_spinbutton_adj = gtk_adjustment_new (1, -1, 31, 1, 10, 10);
  select_dates_match_day_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_match_day_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_match_day_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_day_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_match_day_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_match_day_spinbutton, _("Select the day to match. A value of '-1' will match all days."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_match_day_spinbutton), TRUE);

  select_dates_match_hour_label = gtk_label_new (_("hh:"));
  gtk_widget_show (select_dates_match_hour_label);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_hour_label, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (select_dates_match_hour_label), 5, 0);

  select_dates_match_hour_spinbutton_adj = gtk_adjustment_new (1, -1, 23, 1, 10, 10);
  select_dates_match_hour_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_match_hour_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_match_hour_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_hour_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_match_hour_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_match_hour_spinbutton, _("Select the hour to match. A value of '-1' will match all hours."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_match_hour_spinbutton), TRUE);

  select_dates_match_minute_label = gtk_label_new (_("mm:"));
  gtk_widget_show (select_dates_match_minute_label);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_minute_label, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (select_dates_match_minute_label), 5, 0);

  select_dates_match_minute_spinbutton_adj = gtk_adjustment_new (1, -1, 59, 1, 10, 10);
  select_dates_match_minute_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_match_minute_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_match_minute_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_minute_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_match_minute_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_match_minute_spinbutton, _("Select the minute to match. A value of '-1' will match all minutes."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_match_minute_spinbutton), TRUE);

  select_dates_match_second_label = gtk_label_new (_("ss:"));
  gtk_widget_show (select_dates_match_second_label);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_second_label, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (select_dates_match_second_label), 5, 0);

  select_dates_match_second_spinbutton_adj = gtk_adjustment_new (1, -1, 59, 1, 10, 10);
  select_dates_match_second_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (select_dates_match_second_spinbutton_adj), 1, 0);
  gtk_widget_show (select_dates_match_second_spinbutton);
  gtk_box_pack_start (GTK_BOX (select_dates_match_spinbutton_hbox), select_dates_match_second_spinbutton, FALSE, FALSE, 0);
  gtk_widget_set_size_request (select_dates_match_second_spinbutton, 45, -1);
  gtk_tooltips_set_tip (tooltips, select_dates_match_second_spinbutton, _("Select the second to match. A value of '-1' will match all seconds."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (select_dates_match_second_spinbutton), TRUE);

  select_dates_match_label = gtk_label_new (_("<b>Match</b>"));
  gtk_widget_show (select_dates_match_label);
  gtk_frame_set_label_widget (GTK_FRAME (select_dates_match_frame), select_dates_match_label);
  gtk_label_set_use_markup (GTK_LABEL (select_dates_match_label), TRUE);

  select_dates_match_button_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (select_dates_match_button_hbox);
  gtk_box_pack_start (GTK_BOX (select_dates_vbox), select_dates_match_button_hbox, TRUE, TRUE, 0);

  filter_match_button = gtk_button_new_with_mnemonic (_("Filter Matches"));
  gtk_widget_show (filter_match_button);
  gtk_box_pack_start (GTK_BOX (select_dates_match_button_hbox), filter_match_button, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, filter_match_button, _("Select to filter out all rows that do not match the exact dates listed.  All '-1' values are interpreted as wildcards."), NULL);

  select_dates_label = gtk_label_new (_("<b>Select Date(s)</b>"));
  gtk_widget_show (select_dates_label);
  gtk_frame_set_label_widget (GTK_FRAME (select_dates_frame), select_dates_label);
  gtk_label_set_use_markup (GTK_LABEL (select_dates_label), TRUE);

  g_signal_connect ((gpointer) filter_window, "destroy",
                    G_CALLBACK (on_filter_window_destroy),
                    NULL);
  g_signal_connect ((gpointer) filter_window, "show",
                    G_CALLBACK (on_filter_window_show),
                    NULL);
  g_signal_connect ((gpointer) informational_checkbutton, "toggled",
                    G_CALLBACK (on_informational_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) general_status_checkbutton, "toggled",
                    G_CALLBACK (on_general_status_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) narrowband_communications_checkbutton, "toggled",
                    G_CALLBACK (on_narrowband_communications_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) warnings_errors_checkbutton, "toggled",
                    G_CALLBACK (on_warnings_errors_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) load_shed_checkbutton, "toggled",
                    G_CALLBACK (on_load_shed_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) maintenance_required_checkbutton, "toggled",
                    G_CALLBACK (on_maintenance_required_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) maintenance_mandatory_checkbutton, "toggled",
                    G_CALLBACK (on_maintenance_mandatory_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) secondary_rda_alarm_checkbutton, "toggled",
                    G_CALLBACK (on_secondary_rda_alarm_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) maintenance_required_rda_alarm_checkbutton, "toggled",
                    G_CALLBACK (on_maintenance_required_rda_alarm_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) maintenance_mandatory_rda_alarm_checkbutton, "toggled",
                    G_CALLBACK (on_maintenance_mandatory_rda_alarm_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) inoperable_rda_alarm_checkbutton, "toggled",
                    G_CALLBACK (on_inoperable_rda_alarm_checkbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) filter_ranges_button, "clicked",
                    G_CALLBACK (on_filter_ranges_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) filter_match_button, "clicked",
                    G_CALLBACK (on_filter_match_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filter_window, filter_window, "filter_window");
  GLADE_HOOKUP_OBJECT (filter_window, filter_main_vbox, "filter_main_vbox");
  GLADE_HOOKUP_OBJECT (filter_window, select_rpg_message_frame, "select_rpg_message_frame");
  GLADE_HOOKUP_OBJECT (filter_window, select_rpg_message_frame_alignment, "select_rpg_message_frame_alignment");
  GLADE_HOOKUP_OBJECT (filter_window, select_rpg_message_vbox, "select_rpg_message_vbox");
  GLADE_HOOKUP_OBJECT (filter_window, informational_checkbutton_hbox, "informational_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, informational_checkbutton, "informational_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, informational_label, "informational_label");
  GLADE_HOOKUP_OBJECT (filter_window, general_status_checkbutton_hbox, "general_status_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, general_status_checkbutton, "general_status_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, general_status_label, "general_status_label");
  GLADE_HOOKUP_OBJECT (filter_window, narrowband_communications_checkbutton_hbox, "narrowband_communications_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, narrowband_communications_checkbutton, "narrowband_communications_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, warnings_errors_checkbutton_hbox, "warnings_errors_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, warnings_errors_checkbutton, "warnings_errors_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_rpg_message_label, "select_rpg_message_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_rpg_alarm_frame, "select_rpg_alarm_frame");
  GLADE_HOOKUP_OBJECT (filter_window, select_rpg_alarm_alignment, "select_rpg_alarm_alignment");
  GLADE_HOOKUP_OBJECT (filter_window, select_rpg_alarm_vbox, "select_rpg_alarm_vbox");
  GLADE_HOOKUP_OBJECT (filter_window, load_shed_checkbutton_hbox, "load_shed_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, load_shed_checkbutton, "load_shed_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, maintenance_required_checkbutton_hbox, "maintenance_required_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, maintenance_required_checkbutton, "maintenance_required_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, maintenance_mandatory_checkbutton_hbox, "maintenance_mandatory_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, maintenance_mandatory_checkbutton, "maintenance_mandatory_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_rpg_alarm_label, "select_rpg_alarm_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_rda_alarm_frame, "select_rda_alarm_frame");
  GLADE_HOOKUP_OBJECT (filter_window, select_rda_alarm_label_alignment, "select_rda_alarm_label_alignment");
  GLADE_HOOKUP_OBJECT (filter_window, rda_alarm_vbox, "rda_alarm_vbox");
  GLADE_HOOKUP_OBJECT (filter_window, secondary_rda_alarm_checkbutton_hbox, "secondary_rda_alarm_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, secondary_rda_alarm_checkbutton, "secondary_rda_alarm_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, maintenance_required_rda_alarm_checkbutton_hbox, "maintenance_required_rda_alarm_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, maintenance_required_rda_alarm_checkbutton, "maintenance_required_rda_alarm_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, maintenance_mandatory_rda_alarm_checkbutton_hbox, "maintenance_mandatory_rda_alarm_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, maintenance_mandatory_rda_alarm_checkbutton, "maintenance_mandatory_rda_alarm_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, inoperable_rda_alarm_checkbutton_hbox, "inoperable_rda_alarm_checkbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, inoperable_rda_alarm_checkbutton, "inoperable_rda_alarm_checkbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_rda_alarm_label, "select_rda_alarm_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_frame, "select_dates_frame");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_alignment, "select_dates_alignment");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_vbox, "select_dates_vbox");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range, "select_dates_range");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_alignment, "select_dates_range_alignment");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_start_hbox, "select_dates_range_start_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_year_start_label, "select_dates_range_year_start_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_year_start_spinbutton, "select_dates_range_year_start_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_month_start_label, "select_dates_range_month_start_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_month_start_spinbutton, "select_dates_range_month_start_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_day_start_label, "select_dates_range_day_start_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_day_start_spinbutton, "select_dates_range_day_start_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_hour_start_label, "select_dates_range_hour_start_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_hour_start_spinbutton, "select_dates_range_hour_start_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_minute_start_label, "select_dates_range_minute_start_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_minute_start_spinbutton, "select_dates_range_minute_start_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_second_start_label, "select_dates_range_second_start_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_second_start_spinbutton, "select_dates_range_second_start_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_start_label, "select_dates_range_start_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_end_frame, "select_dates_range_end_frame");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_end_alignment, "select_dates_range_end_alignment");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_end_hbox, "select_dates_range_end_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_year_end_label, "select_dates_range_year_end_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_year_end_spinbutton, "select_dates_range_year_end_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_month_end_label, "select_dates_range_month_end_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_month_end_spinbutton, "select_dates_range_month_end_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_day_end_label, "select_dates_range_day_end_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_day_end_spinbutton, "select_dates_range_day_end_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_hour_end_label, "select_dates_range_hour_end_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_hour_end_spinbutton, "select_dates_range_hour_end_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_minute_end_label, "select_dates_range_minute_end_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_minute_end_spinbutton, "select_dates_range_minute_end_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_second_end_label, "select_dates_range_second_end_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_second_end_spinbutton, "select_dates_range_second_end_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_end_label, "select_dates_range_end_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_range_button_hbox, "select_dates_range_button_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, filter_ranges_button, "filter_ranges_button");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_hseparator, "select_dates_hseparator");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_frame, "select_dates_match_frame");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_alignment, "select_dates_match_alignment");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_vbox, "select_dates_match_vbox");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_spinbutton_hbox, "select_dates_match_spinbutton_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_year_label, "select_dates_match_year_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_year_spinbutton, "select_dates_match_year_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_month_label, "select_dates_match_month_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_month_spinbutton, "select_dates_match_month_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_day_label, "select_dates_match_day_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_day_spinbutton, "select_dates_match_day_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_hour_label, "select_dates_match_hour_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_hour_spinbutton, "select_dates_match_hour_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_minute_label, "select_dates_match_minute_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_minute_spinbutton, "select_dates_match_minute_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_second_label, "select_dates_match_second_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_second_spinbutton, "select_dates_match_second_spinbutton");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_label, "select_dates_match_label");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_match_button_hbox, "select_dates_match_button_hbox");
  GLADE_HOOKUP_OBJECT (filter_window, filter_match_button, "filter_match_button");
  GLADE_HOOKUP_OBJECT (filter_window, select_dates_label, "select_dates_label");
  GLADE_HOOKUP_OBJECT_NO_REF (filter_window, tooltips, "tooltips");

  return filter_window;
}

