#!/usr/bin/ksh
#
# FILE: install_sample_alg
#
#
################################################################
#
# This script installs the sample algorithms. It should be in  
# the ~/src/cpc305 directory after un tared.  It must be 
# executed from that directory.
#
#################################################################

print "\nInstalling sample algorithm \n"
print "Must be executed from the cpc level directory\n"

# create directory extensions in ~/cfg
mkdir -p ~/cfg/extensions

# cp files to proper location
print "\nCopy files to proper location \n"

cp -f -p ./*.sample_snippet ~/cfg/extensions

#cp -f -p ~/src/cpc305/tsk001/sample1_dig.alg ~/cfg/dea
cp -f -p ./tsk001/sample1_dig.alg ~/cfg/dea

#cp -f -p ~/src/cpc305/tsk004/sample3_t2.alg ~/cfg/dea
cp -f -p ./tsk004/sample3_t2.alg ~/cfg/dea

print "\nCompiling sample algorithm...\n"

#cd ~/src/cpc305
csh -c "make clean"
csh -c "make all"
csh -c "make install"

print "\n Done\n"

