#!/bin/sh

# $Author: jing $
# $Locker:  $
# $Date: 2007/08/03 18:48:35 $
# $Id: f2lb,v 1.1 2007/08/03 18:48:35 jing Exp $
# $Revision: 1.1 $
# $State: Exp $
#

##################################################
# print usage info
##################################################

print_usage () {
  echo "Usage: `basename $0` -f input_file -l output_LB [options]"
  echo "    Copy file \"input_file\" to existing LB \"output_LB\". The message"
  echo "    ID in the LB is specified by the -i option. The default is LB_ANY."
  echo "    Options:"
  echo "    -h (Print usage information)"
  echo "    -i msg_id (Message ID to write to)"
}

#
# The main function starts here
#
input_file=
output_lb=
msg_id=

# read options
while getopts f:l:hi: input
do
    case $input in
	f) input_file="$OPTARG" ;;
	l) output_lb="$OPTARG" ;;
	i) msg_id="$OPTARG" ;;
	h) print_usage; exit 0 ;;
	\?) print_usage; exit 1 ;;
    esac
done

# Validate input argments
if [ -z "$input_file" ]
then
    echo "Input file name is required"
    exit 1
fi
if [ -z "$output_lb" ]
then
    echo "Output LB name is required"
    exit 1
fi

if [ -z "$msg_id" ]
then
    lb_cat -w $output_lb < $input_file
else
    lb_cat -w -i $msg_id $output_lb < $input_file
fi
