#!/bin/sh
#
# RCS info
# $Author: cmn $
# $Locker:  $
# $Date: 2008/10/07 11:44:20 $
# $Id: print_log,v 1.5 2008/10/07 11:44:20 cmn Exp $
# $Revision: 1.5 $
# $State: Exp $
#
# File name:            print_log
# Author:               David Priegnitz  
# Creation Date:	01/31/01
#
# This script accepts a plain ASCII text file as its sole argument.
# This file is converted to a PostScript format using an OS specific utility.
# It was created to support the HCI print status log function.
# The HCI makes a call to "system (print_log <filename>)" to
# print the log which is saved as a temporary text file.
#

if [ `uname` = "Linux" ]
then
  a2ps --medium=Letter $1
else # assume SUN
  /usr/openwin/bin/mp $1 | lp
fi

