# RCS info
# $Author: steves $
# $Locker:  $
# $Date: 2014/03/10 19:31:43 $
# $Id: bash_profile,v 1.2 2014/03/10 19:31:43 steves Exp $
# $Revision: 1.2 $
# $State: Exp $
#
# File: orpg.profile
#
# This is a template to use for the RPG .profile file.
# When logging in under the Bash shell, the .profile file is
# automatically sourced by the shell.
#

# Standard location of the configuration files.
export CFG_DIR=$HOME/cfg

# Standard location of the EPSS files.
export EPSS_DIR=$HOME/epss

# Standard location of the product data. It is specified # this way to allow product data to be maintained on a hard disk different than the one used for programs.
export ORPGDIR=$HOME/data

# Standard location of task-private files and/or data stores.
export WORK_DIR=$HOME/tmp

# Standard location of ORDA-related files.
export ORDA_HOME=$HOME/orda

# The following variable is the port number used by the remote HCI.
export RMTPORT=50000

# Location of LogError LB files. Event code is event to be posted upon receipt of critical LE messages.
# IMPORTANT: the event code should match ORPGEVT_LE_CRITICAL in orpgevt.h!!!
export LE_DIR_EVENT=$ORPGDIR"/logs:18"

# Determine OS.
myos=`uname`

# Set corresponding paths.
export LD_LIBRARY_PATH=$HOME/lib/lnux_x86
PATH=$HOME/bin:$HOME/bin/lnux_x86:/usr/local/java/bin:$HOME/tools/bin/:$HOME/tools/bin/lnux_x86
export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
export MANPATH=$HOME/man:/usr/local/man:/usr/share/man
export MAKEINC=$HOME/conf
export MAKETOP=$HOME
export LOCALTOP=$HOME
export ARCH=lnux_x86
export ORPG_NONOPERATIONAL=

# Set misc system variables.
umask 022            # Default umask.
PS1='\h ~\u:${PWD}>'     # Primary prompt that we want.
PS2='\h ~\u:${PWD}>'     # Secondary prompt that we want.
HISTSIZE=64          # Number of previous commands to remember.
TMOUT=0              # Amount of time to wait for input.
alias h='fc -l -50'  # Alias 'history' to 'h'.
alias which='type -a'  # Alias 'history' to 'h'.
unset SESSION_MANAGER DBUS_SESSION_BUS_ADDRESS # Allow ~rpg to run Gnome apps

# Variables for development tools

# For CVG
export ORPG_PRODUCTS_DATABASE=$ORPGDIR/pdist/product_data_base.lb
export CVG_DEF_PREF_DIR=$HOME
